# Generated by Django 5.1.4 on 2026-08-17 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(max_length=100)),
                ('dimension', models.JSONField(blank=True, default=dict)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'analytics_daily_aggregate',
                'constraints': [models.UniqueConstraint(fields=('date', 'metric', 'dimension'), name='uniq_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx')],
            },
        ),
    ]
