# Generated by Django 5.1.4 on 2026-08-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('courses', '0004_fileasset_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.fileasset'),
        ),
    ]
