# Generated by Django 5.1.4 on 2026-08-17 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push (FCM)'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_template',
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='uniq_template_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push (FCM)'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_dispatch',
                'indexes': [models.Index(fields=['user', 'event'], name='notificatio_user_id_6d89b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push (FCM)'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
                'constraints': [models.UniqueConstraint(fields=('user', 'event', 'channel'), name='uniq_user_event_channel')],
            },
        ),
    ]
