# Generated by Django 5.1.4 on 2026-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationdispatch_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdispatch',
            name='event',
            field=models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('homework_assigned', 'Yangi vazifa yuborildi'), ('test_assigned', 'Yangi test yuborildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('homework_assigned', 'Yangi vazifa yuborildi'), ('test_assigned', 'Yangi test yuborildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('lesson_unlocked', 'Yangi dars ochildi'), ('deadline_24h', 'Deadline 24 soat qoldi'), ('deadline_2h', 'Deadline 2 soat qoldi'), ('assignment_graded', 'Vazifa tekshirildi'), ('homework_assigned', 'Yangi vazifa yuborildi'), ('test_assigned', 'Yangi test yuborildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_succeeded', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor'), ('video_ready', 'Video tayyor'), ('otp_code', 'OTP kod'), ('email_verification', 'Email tasdiqlash'), ('password_reset', 'Parolni tiklash')], max_length=50),
        ),
    ]
