# Generated by Django 5.1.4 on 2026-08-17 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'rbac_permission',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.SlugField(unique=True)),
                ('name', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False, help_text="Tizim roli — o'chirib bo'lmaydi (masalan super_admin)")),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission')),
            ],
            options={
                'db_table': 'rbac_role',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('course', 'Kurs'), ('organization', 'Tashkilot')], default='global', max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_role_assignment',
                'indexes': [models.Index(fields=['user', 'scope_type', 'scope_id'], name='rbac_role_a_user_id_78f470_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'scope_type', 'scope_id'), name='uniq_role_assignment')],
            },
        ),
    ]
