# Generated by Django 5.1.4 on 2026-08-17 16:44

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='certificate_templates/')),
                ('signature_image', models.FileField(blank=True, null=True, upload_to='certificate_templates/')),
                ('background_image', models.FileField(blank=True, null=True, upload_to='certificate_templates/')),
                ('text_template', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'certificates_template',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.certificates.models._generate_code, max_length=32, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollment.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'db_table': 'certificates_certificate',
                'indexes': [models.Index(fields=['code'], name='certificate_code_b5c6e8_idx')],
            },
        ),
    ]
