# Generated by Django 5.1.4 on 2026-08-17 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_choice_ids', models.JSONField(blank=True, default=list)),
                ('text_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(null=True)),
                ('points_awarded', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'assessments_answer',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Yuborilgan'), ('expired', 'Vaqti tugagan')], default='in_progress', max_length=20)),
                ('question_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'assessments_attempt',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'assessments_choice',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('single_choice', "Bitta to'g'ri javob"), ('multiple_choice', "Bir nechta to'g'ri javob"), ('true_false', "To'g'ri/noto'g'ri"), ('short_text', 'Qisqa matnli javob')], max_length=20)),
                ('text', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('correct_text_pattern', models.CharField(blank=True, max_length=255)),
                ('is_regex', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assessments_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('questions_per_attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_choices', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('pass_percent', models.PositiveSmallIntegerField(default=60)),
                ('retake_cooldown_hours', models.PositiveIntegerField(default=0)),
                ('result_display', models.CharField(choices=[('immediate', 'Darhol'), ('after_test', 'Testdan keyin'), ('never', 'Hech qachon')], default='after_test', max_length=20)),
            ],
            options={
                'db_table': 'assessments_quiz',
            },
        ),
    ]
