# Generated by Django 5.1.4 on 2026-08-20 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('groups', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='groups.group')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.quiz')),
            ],
            options={
                'db_table': 'assessments_quiz_assignment',
                'indexes': [models.Index(fields=['group'], name='assessments_group_i_e640d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'group'), name='uniq_quiz_assignment_per_group')],
            },
        ),
    ]
