# Generated by Django 5.1.4 on 2026-08-17 16:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='courses/files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courses_file_asset',
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='bunny', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('manifest_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('uploading', 'Yuklanmoqda'), ('processing', 'Transkodlanmoqda'), ('ready', 'Tayyor'), ('failed', 'Xatolik')], default='uploading', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('subtitles', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('total_watched_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'courses_video_asset',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('outcomes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending_moderation', 'Moderatsiyada'), ('published', 'Nashr etilgan'), ('rejected', 'Rad etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='courses/covers/')),
                ('issues_certificate', models.BooleanField(default=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('title_plain', models.CharField(blank=True, max_length=255)),
                ('description_plain', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_courses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.category')),
            ],
            options={
                'db_table': 'courses_course',
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_course_version',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.courseversion'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'db_table': 'courses_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('video', 'Video dars'), ('text', 'Matnli dars'), ('file', 'Fayl / material'), ('quiz', 'Test / kviz'), ('homework', 'Uy vazifasi')], max_length=20)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('text_content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('unlock_rule', models.JSONField(blank=True, default=dict)),
                ('file_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='courses.fileasset')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
                ('video_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='courses.videoasset')),
            ],
            options={
                'db_table': 'courses_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='trailer_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.videoasset'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'version_no'), name='uniq_course_version_no'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='courses_mod_course__20183c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='courses_les_module__4accd4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='courses_cou_search__e2a3ab_gin'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'category'], name='courses_cou_status_1d6ad1_idx'),
        ),
    ]
