# Generated by Django 5.1.4 on 2026-08-18 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileasset',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='file_asset',
        ),
        migrations.AddField(
            model_name='fileasset',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson'),
        ),
    ]
