# Generated by Django 5.1.4 on 2026-08-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_fileasset_options_remove_lesson_file_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
