# Generated by Django 5.1.4 on 2026-08-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_fileasset_description_fileasset_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='kind',
            field=models.CharField(choices=[('presentation', 'Taqdimot'), ('task', 'Vazifa')], default='presentation', max_length=20),
        ),
    ]
