"""Database — PostgreSQL bo'limi uchun mavzu testlari (10 savoldan) va yakuniy test (30 savol)."""

MODULE_TITLE = "Database — PostgreSQL"

QUESTIONS: dict[str, list[dict]] = {
    "(Database) Database va PostgreSQL kirish": [
        {"text": "Ma'lumotlar bazasini boshqarish tizimi (RDBMS) qanday ma'lumotlar tuzilmasidan foydalanadi?",
         "choices": ["Jadvallar (relations)", "Fayllar to'plami", "Rasmlar", "Faqat matn"], "correct": 0},
        {"text": "PostgreSQL MySQL'dan farqli o'laroq nimasi bilan ajralib turadi?",
         "choices": ["Kengaytirilgan tip tizimi va standartlarga to'liqroq mos kelishi", "Faqat bepul bo'lishi", "Faqat Windows'da ishlashi", "SQL ishlatmasligi"], "correct": 0},
        {"text": "PostgreSQL bilan grafik boshqarish uchun mashhur vosita qaysi?",
         "choices": ["pgAdmin", "VS Code", "Postman", "Figma"], "correct": 0},
        {"text": "PostgreSQL buyruq satri interfeysi qanday ataladi?",
         "choices": ["psql", "mysql", "bash", "sqlcmd"], "correct": 0},
        {"text": "Yangi ma'lumotlar bazasi yaratish uchun qaysi SQL buyrug'i ishlatiladi?",
         "choices": ["CREATE DATABASE", "NEW DATABASE", "MAKE DATABASE", "ADD DATABASE"], "correct": 0},
        {"text": "RDBMS nimani anglatadi?",
         "choices": ["Relational Database Management System", "Random Data Backup System", "Remote Database Manager Service", "Real Data Base Model"], "correct": 0},
        {"text": "PostgreSQL — bu qanday turdagi dastur?",
         "choices": ["Ochiq kodli ob'ektga yo'naltirilgan RDBMS", "Matn muharriri", "Operatsion tizim", "Brauzer"], "correct": 0},
        {"text": "psql orqali bazaga ulanish uchun odatda nima kerak bo'ladi?",
         "choices": ["Foydalanuvchi nomi va parol", "Faqat IP manzil", "Faqat port raqami", "Hech narsa kerak emas"], "correct": 0},
        {"text": "Ma'lumotlar bazasi (database) va jadval (table) o'rtasidagi munosabat qanday?",
         "choices": ["Database bir nechta jadvaldan iborat bo'lishi mumkin", "Jadval database'dan katta bo'ladi", "Ular bir xil narsa", "Database faqat bitta jadval saqlaydi"], "correct": 0},
        {"text": "PostgreSQL qaysi sohalarda keng qo'llaniladi?",
         "choices": ["Web ilovalar, analitika, GIS va boshqalar", "Faqat o'yin dasturlash", "Faqat mobil UI dizayn", "Faqat video montaj"], "correct": 0},
    ],
    "(Database) Jadval yaratish, Field turlari va Sequences": [
        {"text": "Jadval yaratish uchun qaysi SQL buyrug'i ishlatiladi?",
         "choices": ["CREATE TABLE", "MAKE TABLE", "NEW TABLE", "BUILD TABLE"], "correct": 0},
        {"text": "Jadvalda har bir qatorni noyob aniqlovchi ustun qanday ataladi?",
         "choices": ["Foreign Key", "Primary Key", "Index", "Constraint"], "correct": 1},
        {"text": "O'zgaruvchan uzunlikdagi matn saqlash uchun qaysi tip ishlatiladi?",
         "choices": ["varchar", "boolean", "date", "int"], "correct": 0},
        {"text": "Avtomatik ortib boruvchi butun son (auto-increment) uchun PostgreSQL'da qaysi tip ishlatiladi?",
         "choices": ["SERIAL", "TEXT", "BOOLEAN", "DATE"], "correct": 0},
        {"text": "JSON ma'lumotlarni samarali saqlash uchun PostgreSQL'da qaysi tip qulay?",
         "choices": ["jsonb", "varchar", "int", "boolean"], "correct": 0},
        {"text": "Katta hajmdagi butun sonlar uchun qaysi tip ishlatiladi?",
         "choices": ["bigint", "boolean", "text", "uuid"], "correct": 0},
        {"text": "SELECT natijasidan yangi jadval yaratish uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["CREATE TABLE AS", "ALTER TABLE", "DROP TABLE", "INSERT INTO"], "correct": 0},
        {"text": "SERIAL tipi orqasida qaysi mexanizm ishlaydi?",
         "choices": ["Sequence (avtomatik hisoblagich)", "Index", "Trigger", "View"], "correct": 0},
        {"text": "Sana va vaqtni birga saqlash uchun qaysi tip ishlatiladi?",
         "choices": ["timestamp", "varchar", "int", "boolean"], "correct": 0},
        {"text": "Noyob identifikator sifatida tasodifiy generatsiya qilinadigan tip qaysi?",
         "choices": ["uuid", "serial", "text", "boolean"], "correct": 0},
    ],
    "(Database) INSERT va UPSERT": [
        {"text": "Jadvalga yangi yozuv qo'shish uchun qaysi buyruq ishlatiladi?",
         "choices": ["INSERT INTO", "UPDATE", "SELECT", "DELETE"], "correct": 0},
        {"text": "Bir nechta yozuvni bitta so'rovda qo'shish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["VALUES", "WHERE", "GROUP BY", "ORDER BY"], "correct": 0},
        {"text": "INSERT so'rovi natijasida qo'shilgan qatorni qaytarish uchun qaysi ifoda ishlatiladi?",
         "choices": ["RETURNING", "OUTPUT", "SHOW", "GET"], "correct": 0},
        {"text": "UPSERT nimani anglatadi?",
         "choices": ["Update yoki Insert — mavjud bo'lsa yangilash, bo'lmasa qo'shish", "Faqat o'chirish", "Faqat o'qish", "Faqat saralash"], "correct": 0},
        {"text": "PostgreSQL'da UPSERT qanday sintaksis bilan amalga oshiriladi?",
         "choices": ["INSERT ... ON CONFLICT DO UPDATE", "INSERT ... REPLACE", "UPDATE ... IF EXISTS", "MERGE ... INTO"], "correct": 0},
        {"text": "Konflikt (masalan unique buzilishi) yuz berganda hech narsa qilmaslik uchun qaysi ifoda ishlatiladi?",
         "choices": ["DO NOTHING", "DO UPDATE", "DO DELETE", "DO SKIP"], "correct": 0},
        {"text": "INSERT so'rovida ustunlar tartibini ko'rsatmasa nima bo'ladi?",
         "choices": ["Jadval yaratilgandagi tartib bo'yicha qiymat kutiladi", "Xatolik chiqmasdan bo'sh qoladi", "Avtomatik saralanadi", "Hech narsa qo'shilmaydi"], "correct": 0},
        {"text": "ON CONFLICT sharti odatda qaysi ustunga asoslanadi?",
         "choices": ["Unique yoki Primary Key ustuniga", "Har qanday ustunga", "Faqat matn ustuniga", "Faqat sana ustuniga"], "correct": 0},
        {"text": "Ma'lumot to'plamini bazaga yuklashda UPSERT qachon foydali?",
         "choices": ["Takroriy import paytida dublikatlarni oldini olishda", "Faqat birinchi marta yuklashda", "Hech qachon", "Faqat DELETE uchun"], "correct": 0},
        {"text": "INSERT INTO buyrug'ida VALUES o'rniga nima ishlatilishi mumkin?",
         "choices": ["SELECT so'rovi natijasi", "DELETE buyrug'i", "DROP buyrug'i", "Hech narsa"], "correct": 0},
    ],
    "(Database) SELECT asoslari": [
        {"text": "Jadvaldagi barcha ustunlarni tanlash uchun qaysi belgi ishlatiladi?",
         "choices": ["*", "%", "#", "@"], "correct": 0},
        {"text": "Natijalarni shartga ko'ra filtrlash uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["WHERE", "ORDER BY", "GROUP BY", "HAVING"], "correct": 0},
        {"text": "\"Teng emas\" solishtirish operatori qaysi?",
         "choices": ["<>", "==", "=!", "!"], "correct": 0},
        {"text": "Ikki shartni birga qanoatlantirish uchun qaysi operator ishlatiladi?",
         "choices": ["AND", "OR", "NOT", "XOR"], "correct": 0},
        {"text": "Ustunga vaqtinchalik boshqa nom berish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["AS", "IN", "IS", "TO"], "correct": 0},
        {"text": "Natijalar sonini cheklash uchun qaysi ifoda ishlatiladi?",
         "choices": ["LIMIT", "MAX", "COUNT", "TOP"], "correct": 0},
        {"text": "Ma'lum sondagi natijalarni o'tkazib yuborish (sahifalash uchun) qaysi ifoda ishlatiladi?",
         "choices": ["OFFSET", "SKIP", "PAGE", "JUMP"], "correct": 0},
        {"text": "SELECT so'rovida faqat kerakli ustunlarni tanlash nima uchun tavsiya etiladi?",
         "choices": ["Samaradorlik va aniqlik uchun", "Har doim majburiy", "Xatolikni oldini olish uchun emas", "Hech qanday sabab yo'q"], "correct": 0},
        {"text": "WHERE sharti odatda so'rovning qaysi bosqichida qo'llaniladi?",
         "choices": ["Qatorlarni tanlashdan oldin filtrlashda", "Faqat guruhlashdan keyin", "Faqat saralashdan keyin", "Hech qachon"], "correct": 0},
        {"text": "\"NOT\" operatori nima vazifani bajaradi?",
         "choices": ["Shartni inkor qiladi (teskarisini oladi)", "Ikki shartni birlashtiradi", "Ustunni o'chiradi", "Jadvalni saralaydi"], "correct": 0},
    ],
    "(Database) UPDATE va DELETE": [
        {"text": "Mavjud yozuvni yangilash uchun qaysi buyruq ishlatiladi?",
         "choices": ["UPDATE", "INSERT", "SELECT", "CREATE"], "correct": 0},
        {"text": "UPDATE buyrug'ida yangi qiymat qaysi kalit so'z bilan beriladi?",
         "choices": ["SET", "VALUES", "WHERE", "INTO"], "correct": 0},
        {"text": "UPDATE buyrug'ida WHERE sharti bo'lmasa nima bo'ladi?",
         "choices": ["Jadvaldagi barcha qatorlar yangilanadi", "Hech narsa o'zgarmaydi", "Xatolik chiqadi", "Faqat birinchi qator yangilanadi"], "correct": 0},
        {"text": "Yozuvlarni o'chirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["DELETE FROM", "REMOVE", "DROP ROW", "CLEAR"], "correct": 0},
        {"text": "Jadvaldagi BARCHA qatorlarni tez o'chirib, strukturani saqlash uchun qaysi buyruq ishlatiladi?",
         "choices": ["TRUNCATE", "DELETE *", "DROP TABLE", "CLEAR TABLE"], "correct": 0},
        {"text": "TRUNCATE va DELETE FROM (WHERE'siz) o'rtasidagi asosiy farq nima?",
         "choices": ["TRUNCATE odatda tezroq va ID hisoblagichni ham tiklaydi", "Farqi yo'q", "DELETE jadvalni butunlay o'chiradi", "TRUNCATE faqat bitta qatorni o'chiradi"], "correct": 0},
        {"text": "Boshqa jadval asosida yangilash uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["UPDATE ... FROM", "UPDATE ... JOIN ONLY", "UPDATE ... WITH", "UPDATE ... USING ONLY"], "correct": 0},
        {"text": "DELETE buyrug'ida boshqa jadval bilan bog'lab o'chirish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["USING", "FROM ONLY", "JOIN", "SET"], "correct": 0},
        {"text": "O'chirilgan yoki yangilangan qatorlarni qaytarish uchun qaysi ifoda ishlatiladi?",
         "choices": ["RETURNING", "SHOW", "OUTPUT", "DISPLAY"], "correct": 0},
        {"text": "DROP TABLE va TRUNCATE TABLE o'rtasidagi farq nima?",
         "choices": ["DROP jadval strukturasini ham o'chiradi, TRUNCATE faqat ma'lumotni", "Farqi yo'q", "TRUNCATE jadvalni butunlay o'chiradi", "DROP faqat ma'lumotni o'chiradi"], "correct": 0},
    ],
    "(Database) Constraints va ALTER TABLE": [
        {"text": "Ustun qiymati bo'sh bo'lmasligini ta'minlovchi cheklov qaysi?",
         "choices": ["NOT NULL", "UNIQUE", "DEFAULT", "CHECK"], "correct": 0},
        {"text": "Ustundagi barcha qiymatlar noyob bo'lishini ta'minlovchi cheklov qaysi?",
         "choices": ["UNIQUE", "NOT NULL", "PRIMARY", "INDEX"], "correct": 0},
        {"text": "Qiymat kiritilmasa avtomatik qo'yiladigan standart qiymat qaysi kalit so'z bilan belgilanadi?",
         "choices": ["DEFAULT", "AUTO", "INIT", "SET"], "correct": 0},
        {"text": "Ustun qiymati ma'lum shartga mos kelishini talab qiluvchi cheklov qaysi?",
         "choices": ["CHECK", "UNIQUE", "NOT NULL", "DEFAULT"], "correct": 0},
        {"text": "Boshqa jadvaldagi qatorga bog'lanishni ta'minlovchi kalit qaysi?",
         "choices": ["FOREIGN KEY", "PRIMARY KEY", "UNIQUE KEY", "INDEX KEY"], "correct": 0},
        {"text": "Mavjud jadvalga yangi ustun qo'shish uchun qaysi buyruq ishlatiladi?",
         "choices": ["ALTER TABLE ... ADD COLUMN", "CREATE COLUMN", "INSERT COLUMN", "NEW COLUMN"], "correct": 0},
        {"text": "Ustun turini o'zgartirish uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["ALTER COLUMN ... TYPE ...", "CHANGE COLUMN TYPE", "MODIFY TYPE", "SET TYPE ONLY"], "correct": 0},
        {"text": "Jadval nomini o'zgartirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["ALTER TABLE ... RENAME TO", "RENAME TABLE ONLY", "CHANGE TABLE NAME", "UPDATE TABLE NAME"], "correct": 0},
        {"text": "Bog'liq yozuvlar o'chirilganda ular ham avtomatik o'chishi uchun qaysi qoida ishlatiladi?",
         "choices": ["ON DELETE CASCADE", "ON DELETE RESTRICT", "ON DELETE SET NULL", "ON DELETE NOTHING"], "correct": 0},
        {"text": "Jadvalni butunlay o'chirishda bog'liq obyektlar bo'lsa xatolik bermasligi uchun qaysi so'z qo'shiladi?",
         "choices": ["CASCADE", "RESTRICT", "DEFAULT", "ONLY"], "correct": 0},
    ],
    "(Database) Chuqur SELECT — saralash, qidirish, NULL": [
        {"text": "Natijalarni saralash uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["ORDER BY", "GROUP BY", "SORT BY", "ARRANGE BY"], "correct": 0},
        {"text": "Kamayish tartibida saralash uchun qaysi kalit so'z qo'shiladi?",
         "choices": ["DESC", "ASC", "DOWN", "REVERSE"], "correct": 0},
        {"text": "Faqat noyob qiymatlarni qaytarish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["DISTINCT", "UNIQUE", "ONLY", "SINGLE"], "correct": 0},
        {"text": "Katta-kichik harflarga sezgir bo'lmagan qidiruv uchun qaysi operator ishlatiladi?",
         "choices": ["ILIKE", "LIKE", "MATCH", "EQUAL"], "correct": 0},
        {"text": "Berilgan qiymatlar to'plamiga mos kelishini tekshirish uchun qaysi operator ishlatiladi?",
         "choices": ["IN", "BETWEEN", "LIKE", "IS"], "correct": 0},
        {"text": "Ikki qiymat oralig'ini tekshirish uchun qaysi operator ishlatiladi?",
         "choices": ["BETWEEN", "IN", "LIKE", "IS"], "correct": 0},
        {"text": "Ustun qiymati bo'sh (NULL) ekanligini tekshirish uchun qaysi ifoda ishlatiladi?",
         "choices": ["IS NULL", "= NULL", "== NULL", "NULL()"], "correct": 0},
        {"text": "Shartli qiymat qaytarish uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["CASE WHEN ... THEN ... END", "IF ... THEN ... ELSE", "SWITCH ... CASE", "WHEN ... DO"], "correct": 0},
        {"text": "NULL qiymatlarni saralashda oxiriga qo'yish uchun qaysi ifoda ishlatiladi?",
         "choices": ["NULLS LAST", "NULLS END", "NULL DOWN", "SORT NULL"], "correct": 0},
        {"text": "LIKE operatorida istalgan belgilar ketma-ketligini bildiruvchi wildcard qaysi?",
         "choices": ["%", "*", "_", "#"], "correct": 0},
    ],
    "(Database) Munosabatlar va JOIN turlari": [
        {"text": "Bir foydalanuvchining ko'p buyurtmasi bo'lishi qanday munosabat turiga misol?",
         "choices": ["One-to-Many", "One-to-One", "Many-to-Many", "Bog'liqlik yo'q"], "correct": 0},
        {"text": "Ikki jadval o'rtasida bog'lanishni ta'minlovchi kalit qaysi?",
         "choices": ["FOREIGN KEY", "PRIMARY KEY", "UNIQUE", "INDEX"], "correct": 0},
        {"text": "Faqat ikkala jadvalda ham mos keladigan yozuvlarni qaytaruvchi JOIN turi qaysi?",
         "choices": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN"], "correct": 0},
        {"text": "Chap jadvaldagi barcha yozuvlarni (mos kelmasa ham) qaytaruvchi JOIN turi qaysi?",
         "choices": ["LEFT JOIN", "INNER JOIN", "RIGHT JOIN", "CROSS JOIN"], "correct": 0},
        {"text": "Ikkala jadvaldagi barcha yozuvlarni (mos kelsa ham, kelmasa ham) qaytaruvchi JOIN turi qaysi?",
         "choices": ["FULL OUTER JOIN", "INNER JOIN", "LEFT JOIN", "SELF JOIN"], "correct": 0},
        {"text": "Ikki jadvalning barcha mumkin bo'lgan kombinatsiyasini qaytaruvchi JOIN turi qaysi?",
         "choices": ["CROSS JOIN", "INNER JOIN", "LEFT JOIN", "SELF JOIN"], "correct": 0},
        {"text": "Jadvalning o'zi bilan birlashtirilishi (masalan xodim-menejer) qanday ataladi?",
         "choices": ["SELF JOIN", "CROSS JOIN", "OUTER JOIN", "NATURAL JOIN"], "correct": 0},
        {"text": "Ma'lumotlar bazasi tuzilmasini vizual ko'rsatish uchun qaysi vosita tilga olingan?",
         "choices": ["dbdiagram.io", "Figma", "Postman", "GitHub"], "correct": 0},
        {"text": "Ko'p-ko'pga (Many-to-Many) munosabat odatda qanday amalga oshiriladi?",
         "choices": ["Oraliq (bog'lovchi) jadval orqali", "To'g'ridan-to'g'ri FOREIGN KEY bilan", "UNIQUE cheklov bilan", "Amalga oshirilmaydi"], "correct": 0},
        {"text": "Bir foydalanuvchining faqat bitta profili bo'lishi qanday munosabatga misol?",
         "choices": ["One-to-One", "One-to-Many", "Many-to-Many", "Bog'liqlik yo'q"], "correct": 0},
    ],
    "(Database) Aggregatsiya, GROUP BY va Set operatorlari": [
        {"text": "Qatorlar sonini hisoblovchi funksiya qaysi?",
         "choices": ["COUNT", "SUM", "AVG", "MAX"], "correct": 0},
        {"text": "Qiymatlar yig'indisini hisoblovchi funksiya qaysi?",
         "choices": ["SUM", "COUNT", "AVG", "MIN"], "correct": 0},
        {"text": "O'rtacha qiymatni hisoblovchi funksiya qaysi?",
         "choices": ["AVG", "SUM", "COUNT", "MAX"], "correct": 0},
        {"text": "Qatorlarni ma'lum ustun bo'yicha guruhlashtirish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["GROUP BY", "ORDER BY", "WHERE", "DISTINCT"], "correct": 0},
        {"text": "Guruhlangan natijalarni shart bilan filtrlash uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["HAVING", "WHERE", "AND", "FILTER"], "correct": 0},
        {"text": "HAVING va WHERE o'rtasidagi asosiy farq nima?",
         "choices": ["HAVING guruhlangan natijalarni, WHERE qatorlarni filtrlaydi", "Farqi yo'q", "WHERE faqat sonlar uchun", "HAVING faqat matn uchun"], "correct": 0},
        {"text": "Ikki so'rov natijasini birlashtirib, dublikatlarni olib tashlovchi operator qaysi?",
         "choices": ["UNION", "UNION ALL", "INTERSECT", "EXCEPT"], "correct": 0},
        {"text": "Ikki so'rov natijasidagi umumiy qatorlarni qaytaruvchi operator qaysi?",
         "choices": ["INTERSECT", "UNION", "EXCEPT", "JOIN"], "correct": 0},
        {"text": "Birinchi so'rovda bor, ikkinchisida yo'q qatorlarni qaytaruvchi operator qaysi?",
         "choices": ["EXCEPT", "INTERSECT", "UNION", "UNION ALL"], "correct": 0},
        {"text": "UNION va UNION ALL o'rtasidagi farq nima?",
         "choices": ["UNION dublikatlarni olib tashlaydi, UNION ALL saqlaydi", "Farqi yo'q", "UNION ALL tezroq har doim yomon", "UNION faqat sonlar uchun"], "correct": 0},
    ],
    "(Database) Subquery va CTE": [
        {"text": "Boshqa so'rov ichida joylashgan so'rov qanday ataladi?",
         "choices": ["Subquery (ichki so'rov)", "Trigger", "View", "Index"], "correct": 0},
        {"text": "Subquery natijasida hech bo'lmasa bitta qator mavjudligini tekshiruvchi operator qaysi?",
         "choices": ["EXISTS", "ANY", "ALL", "IN"], "correct": 0},
        {"text": "Subquery natijasidagi HAR BIR qiymat bilan solishtirish uchun qaysi operator ishlatiladi?",
         "choices": ["ALL", "ANY", "EXISTS", "IN"], "correct": 0},
        {"text": "Subquery natijasidagi QAYSIDIR bitta qiymat bilan solishtirish uchun qaysi operator ishlatiladi?",
         "choices": ["ANY", "ALL", "EXISTS", "NOT"], "correct": 0},
        {"text": "CTE nimani anglatadi?",
         "choices": ["Common Table Expression", "Complex Table Extension", "Central Table Engine", "Custom Type Expression"], "correct": 0},
        {"text": "CTE qaysi kalit so'z bilan e'lon qilinadi?",
         "choices": ["WITH", "AS TABLE", "DEFINE", "CREATE CTE"], "correct": 0},
        {"text": "CTE ishlatishning asosiy afzalligi nima?",
         "choices": ["Murakkab so'rovlarni o'qish oson qismlarga bo'lish", "Bazani tezlashtirish har doim", "Ma'lumotni saqlash", "Xotira tejash har doim"], "correct": 0},
        {"text": "O'zini o'ziga murojaat qiluvchi CTE turi qanday ataladi?",
         "choices": ["Recursive CTE", "Nested Subquery", "Self Join", "Materialized View"], "correct": 0},
        {"text": "Subquery odatda qaysi SQL qismlarida ishlatilishi mumkin?",
         "choices": ["SELECT, WHERE, FROM qismlarida", "Faqat SELECT'da", "Faqat WHERE'da", "Faqat FROM'da"], "correct": 0},
        {"text": "Murakkab hisobotlar tuzishda subquery/CTE ishlatishning sababi nima?",
         "choices": ["So'rovni soddalashtirish va qayta ishlatish", "Ma'lumotni o'chirish", "Jadval yaratish", "Foydalanuvchi qo'shish"], "correct": 0},
    ],
    "(Database) Transaksiyalar, Index va optimizatsiya": [
        {"text": "Tranzaksiyani boshlash uchun qaysi buyruq ishlatiladi?",
         "choices": ["BEGIN", "START", "OPEN", "INIT"], "correct": 0},
        {"text": "Tranzaksiya o'zgarishlarini yakuniy tasdiqlash uchun qaysi buyruq ishlatiladi?",
         "choices": ["COMMIT", "SAVE", "APPLY", "CONFIRM"], "correct": 0},
        {"text": "Tranzaksiya o'zgarishlarini bekor qilish uchun qaysi buyruq ishlatiladi?",
         "choices": ["ROLLBACK", "CANCEL", "UNDO", "DELETE"], "correct": 0},
        {"text": "ACID tamoyillarida \"A\" harfi nimani anglatadi?",
         "choices": ["Atomicity", "Availability", "Aggregation", "Authorization"], "correct": 0},
        {"text": "Tranzaksiya ichida qisman qaytish nuqtasini belgilash uchun qaysi buyruq ishlatiladi?",
         "choices": ["SAVEPOINT", "CHECKPOINT", "MARKPOINT", "RESTOREPOINT"], "correct": 0},
        {"text": "Qidiruvni tezlashtirish uchun jadval ustuniga qo'shiladigan struktura qanday ataladi?",
         "choices": ["Index", "Trigger", "View", "Constraint"], "correct": 0},
        {"text": "Eng ko'p ishlatiladigan standart index turi qaysi?",
         "choices": ["B-tree", "Hash faqat", "GIN faqat", "BRIN faqat"], "correct": 0},
        {"text": "Yangi index yaratish uchun qaysi buyruq ishlatiladi?",
         "choices": ["CREATE INDEX", "ADD INDEX", "NEW INDEX", "MAKE INDEX"], "correct": 0},
        {"text": "So'rov qanday bajarilayotganini tahlil qilish uchun qaysi buyruq ishlatiladi?",
         "choices": ["EXPLAIN ANALYZE", "DESCRIBE", "SHOW PLAN", "CHECK QUERY"], "correct": 0},
        {"text": "Ortiqcha index yaratishning kamchiligi nima bo'lishi mumkin?",
         "choices": ["Yozish (INSERT/UPDATE) tezligini pasaytirishi", "Har doim faqat foyda beradi", "Hech qanday ta'siri yo'q", "Bazani avtomatik o'chiradi"], "correct": 0},
    ],
    "(Database) Python + psycopg2 va yakuniy mini loyiha": [
        {"text": "Python'dan PostgreSQL'ga ulanish uchun mashhur kutubxona qaysi?",
         "choices": ["psycopg2", "requests", "flask", "numpy"], "correct": 0},
        {"text": "SQL so'rovini bajarish uchun psycopg2'da qaysi obyekt ishlatiladi?",
         "choices": ["cursor", "session", "engine", "client"], "correct": 0},
        {"text": "So'rovni bajarish uchun cursor'ning qaysi metodi ishlatiladi?",
         "choices": ["execute()", "run()", "call()", "send()"], "correct": 0},
        {"text": "Barcha natijalarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["fetchall()", "getall()", "readall()", "selectall()"], "correct": 0},
        {"text": "Faqat bitta natijani olish uchun qaysi metod ishlatiladi?",
         "choices": ["fetchone()", "getone()", "readone()", "selectone()"], "correct": 0},
        {"text": "SQL injection hujumidan himoyalanish uchun nima qilinadi?",
         "choices": ["Parametrlangan so'rovlar ishlatish", "Foydalanuvchi kiritgan matnni to'g'ridan-to'g'ri qo'shish", "Bazani o'chirish", "Cursor ishlatmaslik"], "correct": 0},
        {"text": "SQL so'rovda parametr o'rnini bildiruvchi belgi psycopg2'da odatda qaysi?",
         "choices": ["%s", "?", "$1 faqat", "@param"], "correct": 0},
        {"text": "Connection pooling nima uchun ishlatiladi?",
         "choices": ["Ulanishlarni qayta ishlatib samaradorlikni oshirish", "Ma'lumotni shifrlash", "Jadval yaratish", "Indeks qo'shish"], "correct": 0},
        {"text": "O'zgarishlarni bazaga saqlash uchun psycopg2'da nima chaqiriladi?",
         "choices": ["connection.commit()", "connection.save()", "cursor.apply()", "cursor.confirm()"], "correct": 0},
        {"text": "To'liq CRUD ilova nimani anglatadi?",
         "choices": ["Create, Read, Update, Delete amallarini qo'llab-quvvatlash", "Faqat o'qish imkoniyati", "Faqat yozish imkoniyati", "Faqat o'chirish imkoniyati"], "correct": 0},
    ],
}

FINAL = {
    "quiz_title": "Yakuniy test: Database — PostgreSQL",
    "time_limit_seconds": 2700,
    "question_count": 30,
    "questions": [
        {"text": "RDBMS ma'lumotlarni qanday tuzilmada saqlaydi?",
         "choices": ["Jadvallar", "Fayllar", "Rasmlar", "Videolar"], "correct": 0},
        {"text": "PostgreSQL bilan grafik ishlash uchun vosita?",
         "choices": ["pgAdmin", "Figma", "Postman", "VS Code"], "correct": 0},
        {"text": "Yangi baza yaratish buyrug'i?",
         "choices": ["CREATE DATABASE", "NEW DATABASE", "MAKE DB", "ADD DATABASE"], "correct": 0},
        {"text": "Jadval yaratish buyrug'i?",
         "choices": ["CREATE TABLE", "MAKE TABLE", "NEW TABLE", "BUILD TABLE"], "correct": 0},
        {"text": "Qatorni noyob aniqlovchi ustun?",
         "choices": ["Primary Key", "Foreign Key", "Index", "View"], "correct": 0},
        {"text": "Avtomatik ortib boruvchi tip?",
         "choices": ["SERIAL", "TEXT", "BOOLEAN", "DATE"], "correct": 0},
        {"text": "JSON saqlash uchun samarali tip?",
         "choices": ["jsonb", "varchar", "int", "uuid"], "correct": 0},
        {"text": "Yozuv qo'shish buyrug'i?",
         "choices": ["INSERT INTO", "ADD ROW", "NEW ROW", "PUT INTO"], "correct": 0},
        {"text": "UPSERT PostgreSQL'da qanday amalga oshiriladi?",
         "choices": ["INSERT ... ON CONFLICT DO UPDATE", "UPDATE ... IF EXISTS", "MERGE INTO", "INSERT ... REPLACE"], "correct": 0},
        {"text": "Natijani shartga ko'ra filtrlovchi kalit so'z?",
         "choices": ["WHERE", "ORDER BY", "GROUP BY", "LIMIT"], "correct": 0},
        {"text": "Natijalar sonini cheklovchi ifoda?",
         "choices": ["LIMIT", "COUNT", "TOP", "MAX"], "correct": 0},
        {"text": "Yozuvni yangilovchi buyruq?",
         "choices": ["UPDATE", "INSERT", "SELECT", "ALTER"], "correct": 0},
        {"text": "Barcha ma'lumotni tez o'chirib strukturani saqlovchi buyruq?",
         "choices": ["TRUNCATE", "DELETE *", "DROP TABLE", "CLEAR"], "correct": 0},
        {"text": "Ustun bo'sh bo'lmasligini talab qiluvchi cheklov?",
         "choices": ["NOT NULL", "UNIQUE", "DEFAULT", "CHECK"], "correct": 0},
        {"text": "Boshqa jadvalga bog'lovchi kalit?",
         "choices": ["FOREIGN KEY", "PRIMARY KEY", "UNIQUE", "INDEX"], "correct": 0},
        {"text": "Yangi ustun qo'shish buyrug'i?",
         "choices": ["ALTER TABLE ADD COLUMN", "NEW COLUMN", "INSERT COLUMN", "CREATE COLUMN"], "correct": 0},
        {"text": "Natijalarni saralovchi kalit so'z?",
         "choices": ["ORDER BY", "GROUP BY", "SORT", "ARRANGE"], "correct": 0},
        {"text": "Faqat noyob qiymatlarni qaytaruvchi kalit so'z?",
         "choices": ["DISTINCT", "UNIQUE", "ONLY", "SINGLE"], "correct": 0},
        {"text": "Katta-kichik harfga sezgir bo'lmagan qidiruv operatori?",
         "choices": ["ILIKE", "LIKE", "EQUAL", "MATCH"], "correct": 0},
        {"text": "NULL tekshirish ifodasi?",
         "choices": ["IS NULL", "= NULL", "== NULL", "NULL()"], "correct": 0},
        {"text": "Faqat ikkala jadvalda mos kelgan yozuvlarni qaytaruvchi JOIN?",
         "choices": ["INNER JOIN", "LEFT JOIN", "FULL JOIN", "CROSS JOIN"], "correct": 0},
        {"text": "Chap jadvaldagi barcha yozuvlarni qaytaruvchi JOIN?",
         "choices": ["LEFT JOIN", "INNER JOIN", "RIGHT JOIN", "CROSS JOIN"], "correct": 0},
        {"text": "Ikki jadvalning barcha kombinatsiyasini qaytaruvchi JOIN?",
         "choices": ["CROSS JOIN", "INNER JOIN", "SELF JOIN", "FULL JOIN"], "correct": 0},
        {"text": "Qatorlar sonini hisoblovchi funksiya?",
         "choices": ["COUNT", "SUM", "AVG", "MAX"], "correct": 0},
        {"text": "Guruhlashtirish uchun kalit so'z?",
         "choices": ["GROUP BY", "ORDER BY", "WHERE", "HAVING faqat"], "correct": 0},
        {"text": "Guruhlangan natijani filtrlovchi kalit so'z?",
         "choices": ["HAVING", "WHERE", "AND", "FILTER"], "correct": 0},
        {"text": "Ichki so'rov qanday ataladi?",
         "choices": ["Subquery", "Trigger", "View", "Index"], "correct": 0},
        {"text": "CTE qanday e'lon qilinadi?",
         "choices": ["WITH kaliti bilan", "DEFINE bilan", "AS TABLE bilan", "CREATE CTE bilan"], "correct": 0},
        {"text": "Tranzaksiyani boshlash buyrug'i?",
         "choices": ["BEGIN", "START", "OPEN", "INIT"], "correct": 0},
        {"text": "Qidiruvni tezlashtiruvchi struktura?",
         "choices": ["Index", "Trigger", "View", "Constraint"], "correct": 0},
    ],
}
