"""Deployment bo'limi uchun mavzu testlari (10 savoldan) va yakuniy test (30 savol)."""

MODULE_TITLE = "Deployment — Linux server"

QUESTIONS: dict[str, list[dict]] = {
    "(Deploy) Linux va VPS asoslari": [
        {"text": "Joriy papkadagi fayllarni ro'yxatlash uchun qaysi Linux buyrug'i ishlatiladi?",
         "choices": ["cd", "ls", "pwd", "mkdir"], "correct": 1},
        {"text": "Joriy ish papkasi yo'lini ko'rsatuvchi buyruq qaysi?",
         "choices": ["pwd", "ls", "cat", "mv"], "correct": 0},
        {"text": "Yangi papka yaratish uchun qaysi buyruq ishlatiladi?",
         "choices": ["rm", "mkdir", "cp", "nano"], "correct": 1},
        {"text": "Fayl ruxsatlarini (permissions) o'zgartirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["chmod", "chown", "sudo", "ls -l"], "correct": 0},
        {"text": "Fayl egasini (owner) o'zgartirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["chmod", "chown", "adduser", "passwd"], "correct": 1},
        {"text": "Superuser huquqi bilan buyruq bajarish uchun qaysi prefiks ishlatiladi?",
         "choices": ["root", "sudo", "admin", "su root"], "correct": 1},
        {"text": "Paketlarni yangilash uchun Ubuntu'da qaysi buyruq ishlatiladi?",
         "choices": ["apt update", "apt install", "apt remove", "apt list"], "correct": 0},
        {"text": "Serverga masofadan xavfsiz ulanish uchun qaysi protokol/buyruq ishlatiladi?",
         "choices": ["ftp", "ssh user@ip", "http", "ping"], "correct": 1},
        {"text": "Server xavfsizligini ta'minlash uchun portlarni boshqaruvchi vosita (firewall) Ubuntu'da odatda qaysi?",
         "choices": ["ufw", "nano", "grep", "top"], "correct": 0},
        {"text": "VPS (Virtual Private Server) sotib olish uchun mashhur provayderlardan biri qaysi?",
         "choices": ["GitHub", "DigitalOcean", "Figma", "Postman"], "correct": 1},
    ],
    "(Deploy) Server tayyorlash va loyihani ishga tushirish": [
        {"text": "Django loyihasini ishga tushirish uchun serverda birinchi navbatda nima o'rnatiladi?",
         "choices": ["Faqat Nginx", "Python, pip, venv, PostgreSQL, Nginx, Git", "Faqat Git", "Faqat PostgreSQL"], "correct": 1},
        {"text": "Production muhitida DEBUG sozlamasi qanday bo'lishi kerak?",
         "choices": ["DEBUG=True", "DEBUG=False", "DEBUG='yes'", "Muhim emas"], "correct": 1},
        {"text": "Statik fayllarni bitta papkaga yig'ish uchun qaysi Django buyrug'i ishlatiladi?",
         "choices": ["collectstatic", "migrate", "runserver", "makemigrations"], "correct": 0},
        {"text": "Production'da Django'ni Gunicorn bilan ishga tushirishning sababi nima?",
         "choices": ["runserver production uchun mos emas, Gunicorn ishonchli WSGI server", "Gunicorn tezroq kod yozadi", "Gunicorn bazani almashtiradi", "Sababi yo'q"], "correct": 0},
        {"text": "Nginx bu kontekstda qanday rol o'ynaydi?",
         "choices": ["Ma'lumotlar bazasi", "Reverse proxy / veb-server", "Dasturlash tili", "Versiya nazorati tizimi"], "correct": 1},
        {"text": "Loyihani doimiy ishlab turishi (server qayta ishga tushganda ham) uchun nima sozlanadi?",
         "choices": ["systemd service", "requirements.txt", "README.md", ".gitignore"], "correct": 0},
        {"text": "Loyihani GitHub'dan serverga olish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git clone", "git commit", "git push", "git branch"], "correct": 0},
        {"text": "Python kutubxonalarini requirements.txt orqali o'rnatish uchun buyruq?",
         "choices": ["pip install -r requirements.txt", "pip freeze", "pip list", "python manage.py install"], "correct": 0},
        {"text": "ALLOWED_HOSTS sozlamasi nima uchun kerak?",
         "choices": ["Bazaga ulanish uchun", "Django ilova qaysi domenlardan so'rov qabul qilishini cheklash uchun", "Statik fayllar uchun", "Email yuborish uchun"], "correct": 1},
        {"text": "Migratsiyalarni serverda qo'llash uchun qaysi buyruq ishlatiladi?",
         "choices": ["migrate", "collectstatic", "runserver", "shell"], "correct": 0},
    ],
    "(Deploy) Domain, SSL, Telegram Bot Webhook va monitoring": [
        {"text": "Domen nomini VPS IP manziliga bog'lash uchun qaysi DNS yozuvi ishlatiladi?",
         "choices": ["A record", "MX record", "TXT record", "CNAME faqat"], "correct": 0},
        {"text": "Bepul SSL sertifikat olish uchun mashhur xizmat qaysi?",
         "choices": ["Certbot / Let's Encrypt", "GitHub Pages", "Docker Hub", "npm"], "correct": 0},
        {"text": "HTTP o'rniga HTTPS ishlatishning asosiy sababi nima?",
         "choices": ["Tezroq yuklanish", "Ma'lumotlar shifrlanishi va xavfsizlik", "Domen arzonroq bo'lishi", "SEO'ga aloqasi yo'q"], "correct": 1},
        {"text": "Maxfiy sozlamalarni (parol, token) kodga yozmasdan boshqarish uchun nima ishlatiladi?",
         "choices": [".env fayl va python-decouple", "settings.py ichida ochiq yozish", "README.md", "Git commit message"], "correct": 0},
        {"text": "Telegram bot webhook'ni production'da o'rnatish uchun nima talab qilinadi?",
         "choices": ["Faqat localhost", "Real domen + HTTPS", "Faqat HTTP", "Ngrok doimiy"], "correct": 1},
        {"text": "Nginx konfiguratsiyasida qaysi qism domen nomini belgilaydi?",
         "choices": ["server_name", "listen", "root", "location"], "correct": 0},
        {"text": "Server loglarini kuzatish uchun Linux'da qaysi buyruq ishlatiladi?",
         "choices": ["journalctl", "git log", "pip list", "ls -l"], "correct": 0},
        {"text": "Nginx xatoliklari odatda qaysi log faylda ko'rinadi?",
         "choices": ["access.log", "error.log", "settings.py", "requirements.txt"], "correct": 1},
        {"text": "Server xavfsizligi uchun quyidagilardan qaysi biri TAVSIYA ETILMAYDI?",
         "choices": ["Firewall sozlash", "DEBUG=True holda qoldirish", "SSH key ishlatish", "Muntazam yangilanish (apt update)"], "correct": 1},
        {"text": "SSL sertifikat muddati tugashini oldini olish uchun nima qilinadi?",
         "choices": ["Avtomatik yangilanishni sozlash (Certbot renew)", "Domenni o'chirish", "HTTPS'ni butunlay o'chirish", "Hech narsa qilinmaydi"], "correct": 0},
    ],
}

FINAL = {
    "quiz_title": "Yakuniy test: Deployment — Linux server",
    "time_limit_seconds": 2700,
    "question_count": 30,
    "questions": [
        {"text": "Joriy papkadagi fayllarni ko'rish uchun buyruq?",
         "choices": ["cd", "ls", "pwd", "rm"], "correct": 1},
        {"text": "Joriy papka yo'lini ko'rsatuvchi buyruq?",
         "choices": ["pwd", "cat", "mv", "ls"], "correct": 0},
        {"text": "Yangi papka yaratuvchi buyruq?",
         "choices": ["rm", "mkdir", "nano", "cp"], "correct": 1},
        {"text": "Fayl ruxsatlarini o'zgartiruvchi buyruq?",
         "choices": ["chmod", "chown", "sudo", "adduser"], "correct": 0},
        {"text": "Fayl egasini o'zgartiruvchi buyruq?",
         "choices": ["chmod", "chown", "passwd", "ufw"], "correct": 1},
        {"text": "Superuser huquqi bilan ishga tushirish prefiksi?",
         "choices": ["root", "sudo", "admin", "top"], "correct": 1},
        {"text": "Paketlar ro'yxatini yangilash buyrug'i?",
         "choices": ["apt update", "apt remove", "apt list", "apt clean"], "correct": 0},
        {"text": "Serverga masofaviy xavfsiz ulanish protokoli?",
         "choices": ["ftp", "ssh", "http", "smtp"], "correct": 1},
        {"text": "Ubuntu'dagi firewall vositasi?",
         "choices": ["ufw", "grep", "nano", "top"], "correct": 0},
        {"text": "VPS provayderlaridan biri?",
         "choices": ["Figma", "DigitalOcean", "Postman", "Notion"], "correct": 1},
        {"text": "Django loyihasi uchun serverda nimalar o'rnatiladi?",
         "choices": ["Faqat brauzer", "Python, venv, PostgreSQL, Nginx, Git", "Faqat Word", "Faqat Excel"], "correct": 1},
        {"text": "Production'da DEBUG sozlamasi qanday bo'lishi kerak?",
         "choices": ["True", "False", "Ahamiyatsiz", "1"], "correct": 1},
        {"text": "Statik fayllarni yig'uvchi Django buyrug'i?",
         "choices": ["collectstatic", "migrate", "runserver", "shell"], "correct": 0},
        {"text": "Production'da Django ishga tushiriladigan WSGI server?",
         "choices": ["Gunicorn", "npm", "webpack", "React"], "correct": 0},
        {"text": "Nginx bu arxitekturada qanday vazifa bajaradi?",
         "choices": ["Baza boshqaruvi", "Reverse proxy", "Dasturlash tili", "Versiya nazorati"], "correct": 1},
        {"text": "Loyiha doimiy ishlashi uchun nima sozlanadi?",
         "choices": ["systemd service", ".gitignore", "README.md", "requirements.txt"], "correct": 0},
        {"text": "GitHub'dan loyihani serverga olish buyrug'i?",
         "choices": ["git clone", "git push", "git commit", "git branch"], "correct": 0},
        {"text": "requirements.txt orqali kutubxona o'rnatish buyrug'i?",
         "choices": ["pip install -r requirements.txt", "pip freeze", "pip list", "pip show"], "correct": 0},
        {"text": "ALLOWED_HOSTS nima uchun ishlatiladi?",
         "choices": ["Ruxsat etilgan domenlarni belgilash", "Bazaga ulanish", "Email yuborish", "Statik fayllar"], "correct": 0},
        {"text": "Migratsiyalarni qo'llash buyrug'i?",
         "choices": ["migrate", "collectstatic", "shell", "test"], "correct": 0},
        {"text": "Domenni VPS IP'ga bog'lovchi DNS yozuvi?",
         "choices": ["A record", "MX record", "TXT record", "NS record"], "correct": 0},
        {"text": "Bepul SSL sertifikat xizmati?",
         "choices": ["Let's Encrypt", "npm", "GitHub Pages", "Docker Hub"], "correct": 0},
        {"text": "HTTPS ishlatishning asosiy sababi?",
         "choices": ["Tezlik", "Shifrlangan, xavfsiz aloqa", "Arzonlik", "Rangi chiroyli"], "correct": 1},
        {"text": "Maxfiy sozlamalarni boshqarish uchun nima ishlatiladi?",
         "choices": [".env va python-decouple", "settings.py'ga ochiq yozish", "Git commit", "README"], "correct": 0},
        {"text": "Telegram bot webhook production'da qanday sharoit talab qiladi?",
         "choices": ["Faqat localhost", "Real domen + HTTPS", "Faqat HTTP", "Hech qanday shart yo'q"], "correct": 1},
        {"text": "Nginx konfiguratsiyasida domen nomi qaysi direktivada beriladi?",
         "choices": ["server_name", "listen", "root", "index"], "correct": 0},
        {"text": "Server loglarini ko'rish uchun buyruq?",
         "choices": ["journalctl", "pip list", "git log", "ls"], "correct": 0},
        {"text": "Nginx xatoliklari qaysi faylda saqlanadi?",
         "choices": ["access.log", "error.log", "settings.py", ".env"], "correct": 1},
        {"text": "Xavfsizlik nuqtai nazaridan TAVSIYA ETILMAYDIGAN amal?",
         "choices": ["Firewall yoqish", "DEBUG=True qoldirish", "SSH key ishlatish", "Muntazam yangilash"], "correct": 1},
        {"text": "SSL sertifikat muddati tugashini oldini olish uchun nima qilinadi?",
         "choices": ["Avtomatik yangilanish sozlash", "Domenni o'chirish", "HTTPS o'chirish", "Hech narsa"], "correct": 0},
    ],
}
