"""Django/DRF/Telegram Bot bo'limi uchun mavzu testlari (10 savoldan) va yakuniy test (50 savol)."""

MODULE_TITLE = "Django, HTML, Jinja, REST Framework va Telegram Bot"

QUESTIONS: dict[str, list[dict]] = {
    "(Django) Django bilan tanishuv va o'rnatish": [
        {"text": "Django asosan qanday dasturiy vosita hisoblanadi?",
         "choices": ["Web framework", "Operatsion tizim", "Ma'lumotlar bazasi", "Brauzer"], "correct": 0},
        {"text": "Django qaysi arxitektura naqshiga asoslangan?",
         "choices": ["MVT (Model-View-Template)", "MVC faqat klassik", "MVVM", "Ikkitalik model"], "correct": 0},
        {"text": "Django'ni o'rnatish uchun qaysi buyruq ishlatiladi?",
         "choices": ["pip install django", "npm install django", "apt django install", "django setup"], "correct": 0},
        {"text": "Lokal serverni ishga tushirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["python manage.py runserver", "python manage.py start", "django run", "python runserver.py"], "correct": 0},
        {"text": "Django loyihasining bosh sozlamalar fayli qaysi?",
         "choices": ["settings.py", "config.py", "django.cfg", "main.py"], "correct": 0},
        {"text": "Loyihaning URL yo'nalishlari qaysi faylda belgilanadi?",
         "choices": ["urls.py", "routes.py", "paths.py", "views.py"], "correct": 0},
        {"text": "WSGI ilova kirish nuqtasi qaysi fayl?",
         "choices": ["wsgi.py", "asgi.py", "settings.py", "manage.py"], "correct": 0},
        {"text": "Framework va kutubxona o'rtasidagi asosiy farq nima?",
         "choices": ["Framework loyiha oqimini boshqaradi, kutubxona esa dasturchi tomonidan chaqiriladi", "Farqi yo'q", "Kutubxona har doim kattaroq", "Framework faqat frontend uchun"], "correct": 0},
        {"text": "Virtual muhit (venv) Django loyihasida nima uchun tavsiya etiladi?",
         "choices": ["Loyiha kutubxonalarini izolyatsiya qilish uchun", "Internetga ulanish uchun", "Faylni siqish uchun", "Bazani tozalash uchun"], "correct": 0},
        {"text": "Django loyihasini boshqarish uchun asosiy buyruq fayli qaysi?",
         "choices": ["manage.py", "django.py", "run.py", "app.py"], "correct": 0},
    ],
    "(Django) Sozlamalar va App yaratish": [
        {"text": "O'rnatilgan ilovalar ro'yxati settings.py'da qaysi o'zgaruvchida saqlanadi?",
         "choices": ["INSTALLED_APPS", "APPS_LIST", "DJANGO_APPS", "APP_REGISTRY"], "correct": 0},
        {"text": "Baza sozlamalari settings.py'da qaysi o'zgaruvchida saqlanadi?",
         "choices": ["DATABASES", "DB_CONFIG", "DATABASE_URL", "SQL_SETTINGS"], "correct": 0},
        {"text": "Production'da xatolik ma'lumotlarini yashirish uchun qaysi sozlama False qilinadi?",
         "choices": ["DEBUG", "SECRET_KEY", "TIME_ZONE", "LANGUAGE_CODE"], "correct": 0},
        {"text": "Yangi ilova (app) yaratish uchun qaysi buyruq ishlatiladi?",
         "choices": ["python manage.py startapp", "python manage.py newapp", "django-admin createapp", "python manage.py init"], "correct": 0},
        {"text": "Yaratilgan app ishlashi uchun qayerga qo'shilishi kerak?",
         "choices": ["INSTALLED_APPS ro'yxatiga", "urls.py'ga faqat", "wsgi.py'ga", "manage.py'ga"], "correct": 0},
        {"text": "Migratsiyalarni bazaga qo'llash uchun qaysi buyruq ishlatiladi?",
         "choices": ["python manage.py migrate", "python manage.py apply", "python manage.py update_db", "python manage.py sync"], "correct": 0},
        {"text": "Model o'zgarishlari asosida yangi migratsiya fayli yaratish uchun qaysi buyruq ishlatiladi?",
         "choices": ["python manage.py makemigrations", "python manage.py migrate", "python manage.py generate", "python manage.py build"], "correct": 0},
        {"text": "Admin panelga kirish uchun superuser yaratuvchi buyruq qaysi?",
         "choices": ["python manage.py createsuperuser", "python manage.py createadmin", "python manage.py adduser --admin", "python manage.py superuser"], "correct": 0},
        {"text": "App ichidagi ma'lumotlar bazasi modellari odatda qaysi faylda yoziladi?",
         "choices": ["models.py", "database.py", "schema.py", "tables.py"], "correct": 0},
        {"text": "TIME_ZONE sozlamasi nimani belgilaydi?",
         "choices": ["Loyihaning vaqt zonasini", "Bazaning nomini", "Tilni", "Statik fayllar yo'lini"], "correct": 0},
    ],
    "(Django) URL va View": [
        {"text": "URL manzillarini View'larga bog'lash uchun qaysi funksiya ishlatiladi?",
         "choices": ["path()", "route()", "link()", "map()"], "correct": 0},
        {"text": "Regulyar ifoda asosida URL yo'nalishi belgilash uchun qaysi funksiya ishlatiladi?",
         "choices": ["re_path()", "regex_path()", "match_path()", "pattern_path()"], "correct": 0},
        {"text": "App darajasidagi urls.py'ni loyiha urls.py'ga ulash uchun qaysi funksiya ishlatiladi?",
         "choices": ["include()", "connect()", "link_app()", "attach()"], "correct": 0},
        {"text": "Oddiy funksiya sifatida yozilgan view qanday ataladi?",
         "choices": ["FBV (Function-Based View)", "CBV (Class-Based View)", "TemplateView", "GenericView"], "correct": 0},
        {"text": "Foydalanuvchiga oddiy matnli javob qaytarish uchun qaysi obyekt ishlatiladi?",
         "choices": ["HttpResponse", "JsonResponse only", "Response DRF only", "TemplateResponse only"], "correct": 0},
        {"text": "URL'dan butun son parametrini olish uchun qaysi konverter ishlatiladi?",
         "choices": ["<int:id>", "<num:id>", "<integer:id>", "<digit:id>"], "correct": 0},
        {"text": "URL'ga nom berish uchun path() funksiyasida qaysi parametr ishlatiladi?",
         "choices": ["name=", "id=", "label=", "tag="], "correct": 0},
        {"text": "URL'dan matnli qiymat (bo'sh joysiz) olish uchun qaysi konverter ishlatiladi?",
         "choices": ["<slug:name>", "<text:name>", "<word:name>", "<char:name>"], "correct": 0},
        {"text": "Har bir view funksiyasi minimal qanday parametr qabul qiladi?",
         "choices": ["request", "response", "context", "template"], "correct": 0},
        {"text": "URL routing'ning asosiy vazifasi nima?",
         "choices": ["Kelgan so'rovni to'g'ri view'ga yo'naltirish", "Ma'lumotlar bazasini yaratish", "Statik fayllarni siqish", "Emailga xabar yuborish"], "correct": 0},
    ],
    "(Django) Models — 1-qism (yaratish)": [
        {"text": "Model klassi odatda qaysi bazaviy klassdan meros oladi?",
         "choices": ["models.Model", "models.Base", "django.Model", "BaseModel faqat"], "correct": 0},
        {"text": "Matnli, cheklangan uzunlikdagi maydon uchun qaysi field turi ishlatiladi?",
         "choices": ["CharField", "TextField", "IntegerField", "BooleanField"], "correct": 0},
        {"text": "Uzunligi cheklanmagan matn uchun qaysi field turi ishlatiladi?",
         "choices": ["TextField", "CharField", "SlugField", "URLField"], "correct": 0},
        {"text": "CharField uchun uzunlik cheklovi qaysi parametr bilan beriladi?",
         "choices": ["max_length", "length", "size", "limit"], "correct": 0},
        {"text": "Maydon bazada bo'sh (NULL) bo'lishi mumkinligini bildiruvchi parametr qaysi?",
         "choices": ["null=True", "blank=True faqat", "empty=True", "optional=True"], "correct": 0},
        {"text": "Maydon forma darajasida bo'sh qoldirilishi mumkinligini bildiruvchi parametr qaysi?",
         "choices": ["blank=True", "null=True faqat", "empty=True", "optional=True"], "correct": 0},
        {"text": "Maydon uchun standart qiymat berish parametri qaysi?",
         "choices": ["default", "initial", "value", "start"], "correct": 0},
        {"text": "Model obyektini o'qishga qulay matn shaklida qaytaruvchi metod qaysi?",
         "choices": ["__str__", "__repr__ faqat", "__display__", "__text__"], "correct": 0},
        {"text": "Model ichidagi Meta klassi nima uchun ishlatiladi?",
         "choices": ["ordering, verbose_name kabi model darajasidagi sozlamalar uchun", "Maydon yaratish uchun", "URL yo'nalishi uchun", "Xatolik ushlash uchun"], "correct": 0},
        {"text": "Model o'zgarishidan keyin bazaga qo'llash uchun ketma-ket qaysi ikki buyruq bajariladi?",
         "choices": ["makemigrations va migrate", "migrate va makemigrations", "collectstatic va migrate", "runserver va migrate"], "correct": 0},
    ],
    "(Django) Models — 2-qism (munosabatlar)": [
        {"text": "\"Ko'p-birga\" (Many-to-One) munosabat uchun qaysi field turi ishlatiladi?",
         "choices": ["ForeignKey", "OneToOneField", "ManyToManyField", "CharField"], "correct": 0},
        {"text": "\"Bir-birga\" (One-to-One) munosabat uchun qaysi field turi ishlatiladi?",
         "choices": ["OneToOneField", "ForeignKey", "ManyToManyField", "IntegerField"], "correct": 0},
        {"text": "\"Ko'p-ko'pga\" (Many-to-Many) munosabat uchun qaysi field turi ishlatiladi?",
         "choices": ["ManyToManyField", "ForeignKey", "OneToOneField", "TextField"], "correct": 0},
        {"text": "ForeignKey'da bog'liq obyekt o'chirilganda nima bo'lishini belgilovchi parametr qaysi?",
         "choices": ["on_delete", "on_remove", "cascade", "delete_rule"], "correct": 0},
        {"text": "on_delete=models.CASCADE nimani anglatadi?",
         "choices": ["Bog'liq obyekt o'chirilganda shu yozuv ham o'chadi", "Hech narsa o'chmaydi", "Xatolik chiqadi", "Faqat ogohlantirish beriladi"], "correct": 0},
        {"text": "Teskari (reverse) tomondan bog'liq obyektlarga murojaat qilish nomini o'zgartirish uchun qaysi parametr ishlatiladi?",
         "choices": ["related_name", "reverse_name", "back_name", "link_name"], "correct": 0},
        {"text": "author.book_set.all() kabi murojaat qanday ataladi?",
         "choices": ["Reverse lookup (teskari qidiruv)", "Forward lookup", "Direct query", "Static lookup"], "correct": 0},
        {"text": "Migratsiyalar munosabatlarni bazada qanday tatbiq etadi?",
         "choices": ["Jadval ustunlari va cheklovlar (masalan FOREIGN KEY) orqali", "Faqat Python darajasida, bazaga ta'sir qilmaydi", "Faqat admin panelda", "Hech qanday ta'siri yo'q"], "correct": 0},
        {"text": "Admin panelda bog'liq modelni asosiy model sahifasida ko'rsatish uchun nima ishlatiladi?",
         "choices": ["Inline (TabularInline/StackedInline)", "ForeignKey faqat", "related_name faqat", "Meta class faqat"], "correct": 0},
        {"text": "Bir kitobning faqat bitta muallifi bo'lishi qaysi munosabatga misol?",
         "choices": ["ForeignKey (Many-to-One)", "ManyToManyField", "Hech qaysisiga", "OneToOneField har doim"], "correct": 0},
    ],
    "(Django) Django ORM": [
        {"text": "Jadvaldagi barcha yozuvlarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["all()", "get()", "select()", "list()"], "correct": 0},
        {"text": "Shartga mos yozuvlarni filtrlash uchun qaysi metod ishlatiladi?",
         "choices": ["filter()", "where()", "select()", "match()"], "correct": 0},
        {"text": "Faqat bitta, aniq yozuvni olish uchun qaysi metod ishlatiladi?",
         "choices": ["get()", "filter()", "first()", "find()"], "correct": 0},
        {"text": "Shartga mos KELMAGAN yozuvlarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["exclude()", "filter_not()", "reject()", "without()"], "correct": 0},
        {"text": "Natijalarni saralash uchun qaysi metod ishlatiladi?",
         "choices": ["order_by()", "sort()", "arrange()", "sequence()"], "correct": 0},
        {"text": "Yangi obyekt yaratib, uni bazaga saqlash uchun qaysi qulay metod ishlatiladi?",
         "choices": ["create()", "new()", "add()", "insert()"], "correct": 0},
        {"text": "Mavjud obyektni bazaga saqlash uchun qaysi metod ishlatiladi?",
         "choices": ["save()", "commit()", "update_db()", "store()"], "correct": 0},
        {"text": "QuerySet'da yozuvlar mavjudligini tekshirish uchun qaysi metod ishlatiladi?",
         "choices": ["exists()", "has()", "contains()", "check()"], "correct": 0},
        {"text": "Django shell'ga kirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["python manage.py shell", "python manage.py console", "python manage.py repl", "django shell"], "correct": 0},
        {"text": "QuerySet'dagi yozuvlar sonini olish uchun qaysi metod ishlatiladi?",
         "choices": ["count()", "len() faqat", "size()", "total()"], "correct": 0},
    ],
    "(Django) Templates va render() (HTML asoslari bilan)": [
        {"text": "Django shablon fayllari odatda qaysi papkada joylashadi?",
         "choices": ["templates/", "views/", "static/", "models/"], "correct": 0},
        {"text": "View'dan shablonga kontekst bilan javob qaytarish uchun qaysi funksiya ishlatiladi?",
         "choices": ["render()", "response()", "template()", "return_html()"], "correct": 0},
        {"text": "HTML hujjatning turi (versiya) qaysi teg bilan e'lon qilinadi?",
         "choices": ["<!DOCTYPE html>", "<html-type>", "<version>", "<meta type>"], "correct": 0},
        {"text": "Sahifaning ko'rinadigan asosiy tarkibi qaysi teg ichida joylashadi?",
         "choices": ["<body>", "<head>", "<meta>", "<title>"], "correct": 0},
        {"text": "Havola (link) yaratish uchun qaysi HTML tegi ishlatiladi?",
         "choices": ["<a>", "<link>", "<href>", "<url>"], "correct": 0},
        {"text": "Shablonda kontekst o'zgaruvchisini chiqarish uchun qaysi belgilar ishlatiladi?",
         "choices": ["{{ }}", "{% %}", "{# #}", "[[ ]]"], "correct": 0},
        {"text": "render() funksiyasiga odatda nechta asosiy argument beriladi?",
         "choices": ["request, template nomi va (ixtiyoriy) context", "Faqat template nomi", "Faqat request", "Faqat context"], "correct": 0},
        {"text": "Rasm joylashtirish uchun qaysi HTML tegi ishlatiladi?",
         "choices": ["<img>", "<pic>", "<image>", "<src>"], "correct": 0},
        {"text": "Ro'yxat elementlarini tartibsiz ko'rsatish uchun qaysi teg ishlatiladi?",
         "choices": ["<ul>", "<ol>", "<li> faqat", "<list>"], "correct": 0},
        {"text": "Kontekst — bu nima?",
         "choices": ["View'dan shablonga uzatiladigan ma'lumotlar lug'ati", "CSS fayli", "URL nomi", "Baza jadvali"], "correct": 0},
    ],
    "(Django) DTL — sintaksis va filterlar": [
        {"text": "DTL nimani anglatadi?",
         "choices": ["Django Template Language", "Data Type Library", "Django Test Layer", "Dynamic Text Loader"], "correct": 0},
        {"text": "Shablon tegi (masalan {% if %}) qaysi qavslar bilan yoziladi?",
         "choices": ["{% %}", "{{ }}", "{# #}", "<% %>"], "correct": 0},
        {"text": "Shablon izohi qaysi qavslar bilan yoziladi?",
         "choices": ["{# #}", "{% %}", "{{ }}", "<!-- -->"], "correct": 0},
        {"text": "Matnni bosh harfga o'girish uchun qaysi filter ishlatiladi?",
         "choices": ["upper", "capitalize faqat", "title faqat", "big"], "correct": 0},
        {"text": "Qiymat bo'sh bo'lsa standart qiymat ko'rsatish uchun qaysi filter ishlatiladi?",
         "choices": ["default", "empty", "fallback", "or"], "correct": 0},
        {"text": "Ro'yxat yoki string uzunligini olish uchun qaysi filter ishlatiladi?",
         "choices": ["length", "len", "size", "count"], "correct": 0},
        {"text": "Matnni belgilangan uzunlikdan qisqartirish uchun qaysi filter ishlatiladi?",
         "choices": ["truncatechars", "shorten", "cut", "limit"], "correct": 0},
        {"text": "Sana formatlash uchun qaysi filter ishlatiladi?",
         "choices": ["date", "format_date", "datetime", "strftime"], "correct": 0},
        {"text": "Bir nechta filterni birlashtirish uchun qanday belgi ishlatiladi?",
         "choices": ["| (pipe)", ", (vergul)", "+ (qo'shish)", "& (va)"], "correct": 0},
        {"text": "Ro'yxat elementlarini bitta matnga birlashtiruvchi filter qaysi?",
         "choices": ["join", "merge", "concat", "combine"], "correct": 0},
    ],
    "(Django) DTL — shartlar, sikllar, inheritance": [
        {"text": "Shablonda shartli blok qanday boshlanadi?",
         "choices": ["{% if %}", "{{ if }}", "{# if #}", "<if>"], "correct": 0},
        {"text": "Shablonda sikl qanday tashkil qilinadi?",
         "choices": ["{% for %} ... {% endfor %}", "{% while %}", "{{ for }}", "{# loop #}"], "correct": 0},
        {"text": "for sikli ichida joriy iteratsiya haqida ma'lumot beruvchi maxsus o'zgaruvchi qaysi?",
         "choices": ["forloop", "loopindex", "current", "iter"], "correct": 0},
        {"text": "Shablon merosxo'rligi (inheritance) uchun qaysi teg ishlatiladi?",
         "choices": ["{% extends %}", "{% inherit %}", "{% include_base %}", "{% parent %}"], "correct": 0},
        {"text": "Ota shablonda bola shablon to'ldiradigan qism qaysi teg bilan belgilanadi?",
         "choices": ["{% block %}", "{% section %}", "{% area %}", "{% slot %}"], "correct": 0},
        {"text": "Boshqa shablon faylini joriy shablon ichiga qo'shish uchun qaysi teg ishlatiladi?",
         "choices": ["{% include %}", "{% import %}", "{% embed %}", "{% insert %}"], "correct": 0},
        {"text": "URL nomiga qarab havola yaratish uchun qaysi teg ishlatiladi?",
         "choices": ["{% url %}", "{% link %}", "{% href %}", "{% path %}"], "correct": 0},
        {"text": "{% extends %} qatori shablonning qaysi qismida bo'lishi shart?",
         "choices": ["Faylning eng boshida", "Faylning oxirida", "Har qanday joyda", "Faqat body ichida"], "correct": 0},
        {"text": "forloop.counter nimani ko'rsatadi?",
         "choices": ["Joriy iteratsiya raqamini (1 dan boshlab)", "Umumiy elementlar sonini", "Oxirgi elementni", "Doim 0 ni"], "correct": 0},
        {"text": "Shablon merosxo'rligining asosiy afzalligi nima?",
         "choices": ["Umumiy tuzilmani (header, footer) takrorlamaslik", "Sahifani tezlashtirish", "Xavfsizlikni oshirish", "Bazani optimallashtirish"], "correct": 0},
    ],
    "(Django) Jinja template tili": [
        {"text": "Jinja Django'da qachon ishlatilishi mumkin?",
         "choices": ["DTL o'rniga muqobil shablon dvigateli sifatida", "Faqat CSS uchun", "Faqat JavaScript uchun", "Hech qachon ishlatilmaydi"], "correct": 0},
        {"text": "Jinja'ni Django loyihasiga ulash uchun qayerda sozlash kerak?",
         "choices": ["settings.py'dagi TEMPLATES", "urls.py", "models.py", "wsgi.py"], "correct": 0},
        {"text": "Jinja va DTL sintaksisi umumiy jihatdan qanday?",
         "choices": ["Juda o'xshash ({{ }}, {% %})", "Butunlay boshqacha", "Jinja HTML ishlatmaydi", "DTL Python kodini to'g'ridan-to'g'ri ishlatadi"], "correct": 0},
        {"text": "Jinja'da qayta ishlatiladigan shablon funksiyasi qanday ataladi?",
         "choices": ["Macro ({% macro %})", "Function", "Block only", "Include only"], "correct": 0},
        {"text": "Jinja DTL'ga nisbatan qaysi jihati bilan ko'proq imkoniyat beradi?",
         "choices": ["Kengaytirilgan Python-ga yaqin ifodalar va filterlar", "Faqat rasm ko'rsatish", "Faqat CSS animatsiya", "Faqat JSON formatlash"], "correct": 0},
        {"text": "Django'da bir loyihada ham DTL, ham Jinja ishlatish mumkinmi?",
         "choices": ["Ha, turli backend sifatida sozlash orqali", "Yo'q, faqat bittasi", "Faqat yangi loyihalarda", "Hech qachon"], "correct": 0},
        {"text": "Qachon DTL, qachon Jinja ishlatish tavsiya etiladi?",
         "choices": ["Loyiha ehtiyoji va murakkablik darajasiga qarab", "Har doim faqat Jinja", "Har doim faqat DTL", "Farqi yo'q, tasodifiy tanlanadi"], "correct": 0},
        {"text": "Jinja shablon fayllarining kengaytmasi odatda qanday?",
         "choices": [".html (DTL bilan bir xil)", ".jinja majburiy", ".j2 majburiy", ".jn"], "correct": 0},
        {"text": "Jinja'da izoh qanday yoziladi?",
         "choices": ["{# izoh #}", "// izoh", "<!-- izoh -->", "/* izoh */"], "correct": 0},
        {"text": "Macro Jinja'da nimaga o'xshaydi?",
         "choices": ["Parametrli funksiyaga", "CSS klassiga", "URL yo'liga", "Bazaviy jadvalga"], "correct": 0},
    ],
    "(Django) CSS asoslari": [
        {"text": "CSS asosan nima uchun ishlatiladi?",
         "choices": ["Veb-sahifa ko'rinishini (stil) belgilash uchun", "Ma'lumotlar bazasini boshqarish uchun", "Server mantiqini yozish uchun", "URL yo'nalishini belgilash uchun"], "correct": 0},
        {"text": "CSS'ni HTML'ga alohida fayl sifatida ulash usuli qanday ataladi?",
         "choices": ["External CSS", "Internal CSS", "Inline CSS", "Embedded CSS"], "correct": 0},
        {"text": "Klass selektori qaysi belgi bilan boshlanadi?",
         "choices": [".", "#", "@", "&"], "correct": 0},
        {"text": "ID selektori qaysi belgi bilan boshlanadi?",
         "choices": ["#", ".", "@", "%"], "correct": 0},
        {"text": "Box model tarkibiga quyidagilardan qaysi biri KIRMAYDI?",
         "choices": ["Animation", "Margin", "Padding", "Border"], "correct": 0},
        {"text": "Elementning tashqi bo'shlig'i qaysi xususiyat bilan boshqariladi?",
         "choices": ["margin", "padding", "border", "outline"], "correct": 0},
        {"text": "Elementning ichki bo'shlig'i qaysi xususiyat bilan boshqariladi?",
         "choices": ["padding", "margin", "gap", "spacing"], "correct": 0},
        {"text": "Elementni bir qatorda, lekin o'lcham berilishi mumkin qilib ko'rsatuvchi display turi qaysi?",
         "choices": ["inline-block", "block", "inline", "none"], "correct": 0},
        {"text": "Elementni yangi qatorda, to'liq kenglikda ko'rsatuvchi display turi qaysi?",
         "choices": ["block", "inline", "inline-block", "flex faqat"], "correct": 0},
        {"text": "CSS'da matn rangini belgilash uchun qaysi xususiyat ishlatiladi?",
         "choices": ["color", "text-color", "font-color", "background"], "correct": 0},
    ],
    "(Django) Bootstrap va Static fayllar": [
        {"text": "Bootstrap'ni tez ulash uchun qaysi usul ishlatiladi?",
         "choices": ["CDN orqali <link> qo'shish", "Faqat pip install", "Faqat npm install", "Bootstrap kerak emas"], "correct": 0},
        {"text": "Bootstrap grid tizimida sahifa qismlari qaysi klass ichiga joylashtiriladi?",
         "choices": ["container", "wrapper", "box", "frame"], "correct": 0},
        {"text": "Bootstrap grid tizimida qator (row) ichida ustunlar qaysi klasslar bilan belgilanadi?",
         "choices": ["col-md-*, col-lg-* kabi", "grid-*", "box-*", "layout-*"], "correct": 0},
        {"text": "Sahifa yuqorisidagi navigatsiya paneli uchun Bootstrap komponenti qaysi?",
         "choices": ["navbar", "topbar", "menu-bar", "header-bar"], "correct": 0},
        {"text": "Statik fayllar (CSS, JS, rasm) uchun bazaviy URL manzili qaysi sozlamada beriladi?",
         "choices": ["STATIC_URL", "MEDIA_URL", "BASE_URL", "ASSETS_URL"], "correct": 0},
        {"text": "Statik fayllar qidiriladigan qo'shimcha papkalar qaysi sozlamada ko'rsatiladi?",
         "choices": ["STATICFILES_DIRS", "STATIC_ROOT", "MEDIA_ROOT", "TEMPLATES_DIRS"], "correct": 0},
        {"text": "Shablonda statik fayllardan foydalanish uchun avval nima qilinadi?",
         "choices": ["{% load static %} yoziladi", "Hech narsa, avtomatik ishlaydi", "Faqat settings.py o'zgartiriladi", "Faqat urls.py o'zgartiriladi"], "correct": 0},
        {"text": "Shablonda statik faylga havola berish uchun qaysi teg ishlatiladi?",
         "choices": ["{% static 'path' %}", "{{ static.path }}", "{# static path #}", "<static path>"], "correct": 0},
        {"text": "Bootstrap'da modal oyna (dialog) uchun komponent nomi qaysi?",
         "choices": ["modal", "popup", "dialog-box", "alert-box"], "correct": 0},
        {"text": "Bootstrap ishlatishning asosiy afzalligi nima?",
         "choices": ["Tayyor, responsive UI komponentlarini tez qo'llash", "Bazani tezlashtirish", "Server xavfsizligini oshirish", "URL yo'nalishini avtomatlashtirish"], "correct": 0},
    ],
    "(Django) Django Admin chuqur": [
        {"text": "Modelni admin panelda ro'yxatdan o'tkazish uchun qaysi funksiya ishlatiladi?",
         "choices": ["admin.site.register()", "admin.add_model()", "admin.model_register()", "register_model()"], "correct": 0},
        {"text": "Admin ro'yxat sahifasida ko'rsatiladigan ustunlarni belgilovchi atribut qaysi?",
         "choices": ["list_display", "list_columns", "display_fields", "show_fields"], "correct": 0},
        {"text": "Admin panelda filtrlash paneli uchun qaysi atribut ishlatiladi?",
         "choices": ["list_filter", "filter_by", "search_filter", "filters"], "correct": 0},
        {"text": "Admin panelda qidiruv maydonini yoqish uchun qaysi atribut ishlatiladi?",
         "choices": ["search_fields", "search_by", "find_fields", "query_fields"], "correct": 0},
        {"text": "Ro'yxat sahifasida to'g'ridan-to'g'ri tahrirlash mumkin bo'lgan maydonlar qaysi atribut bilan belgilanadi?",
         "choices": ["list_editable", "editable_fields", "quick_edit", "inline_edit"], "correct": 0},
        {"text": "Bir sahifada nechta yozuv ko'rsatilishini belgilovchi atribut qaysi?",
         "choices": ["list_per_page", "page_size", "items_per_page", "pagination_count"], "correct": 0},
        {"text": "Faqat o'qish uchun (tahrirlanmaydigan) maydonlarni belgilovchi atribut qaysi?",
         "choices": ["readonly_fields", "view_only_fields", "locked_fields", "static_fields"], "correct": 0},
        {"text": "Bog'liq modelni asosiy model formasida jadval ko'rinishida ko'rsatish uchun qaysi klass ishlatiladi?",
         "choices": ["TabularInline", "StackedInline faqat", "ListInline", "GridInline"], "correct": 0},
        {"text": "Admin panelda tanlangan yozuvlar ustida maxsus amal bajarish uchun nima yoziladi?",
         "choices": ["Custom admin action", "Custom view faqat", "Custom serializer", "Custom middleware"], "correct": 0},
        {"text": "ModelAdmin klassi nima uchun ishlatiladi?",
         "choices": ["Modelning admin panelda qanday ko'rinishini sozlash uchun", "Modelni yaratish uchun", "Migratsiya yaratish uchun", "URL yo'naltirish uchun"], "correct": 0},
    ],
    "(Django) Forms — 1-qism (Form class)": [
        {"text": "Django Form klassi qaysi bazaviy klassdan meros oladi?",
         "choices": ["forms.Form", "forms.Base", "django.Form", "models.Form"], "correct": 0},
        {"text": "Ma'lumot yuborishning ikkita asosiy HTTP metodi qaysilar?",
         "choices": ["GET va POST", "PUT va DELETE", "PATCH va HEAD", "OPTIONS va TRACE"], "correct": 0},
        {"text": "Shablonda formani avtomatik <p> teglar bilan chiqarish uchun qaysi ifoda ishlatiladi?",
         "choices": ["{{ form.as_p }}", "{{ form.render }}", "{{ form.html }}", "{{ form.output }}"], "correct": 0},
        {"text": "Formadagi ma'lumotlar to'g'riligini tekshirish uchun qaysi metod chaqiriladi?",
         "choices": ["is_valid()", "check()", "validate()", "verify()"], "correct": 0},
        {"text": "Tekshirilgan (validatsiyadan o'tgan) ma'lumotlar qaysi atributda saqlanadi?",
         "choices": ["cleaned_data", "valid_data", "form_data", "checked_data"], "correct": 0},
        {"text": "CSRF hujumidan himoyalanish uchun formada nima ishlatiladi?",
         "choices": ["{% csrf_token %}", "{% security_token %}", "{% auth_token %}", "{% form_token %}"], "correct": 0},
        {"text": "CSRF nimani anglatadi?",
         "choices": ["Cross-Site Request Forgery", "Client Side Request Filter", "Cross Server Response Format", "Cached Session Request Flow"], "correct": 0},
        {"text": "Formaning muvaffaqiyatsiz validatsiyasi natijasida nima yuz beradi?",
         "choices": ["Xatoliklar form.errors orqali qaytariladi", "Dastur to'xtaydi", "Avtomatik bazaga saqlanadi", "Hech narsa yuz bermaydi"], "correct": 0},
        {"text": "GET va POST so'rovlari o'rtasidagi asosiy farq nima?",
         "choices": ["GET ma'lumotni URL orqali, POST — so'rov tanasida yuboradi", "Farqi yo'q", "GET faqat rasm uchun", "POST faqat o'qish uchun"], "correct": 0},
        {"text": "Forma maydoni turi (masalan CharField) nimani belgilaydi?",
         "choices": ["Kiritish turi va validatsiya qoidalarini", "Faqat ranги", "Faqat shriftni", "Faqat joylashuvni"], "correct": 0},
    ],
    "(Django) Forms — 2-qism (ModelForm)": [
        {"text": "ModelForm nima uchun ishlatiladi?",
         "choices": ["Model asosida avtomatik forma yaratish uchun", "Faqat static forma uchun", "Faqat admin panel uchun", "URL yaratish uchun"], "correct": 0},
        {"text": "ModelForm'da qaysi model va maydonlar ishlatilishini belgilovchi ichki klass qaysi?",
         "choices": ["Meta", "Config", "Settings", "Options"], "correct": 0},
        {"text": "ModelForm orqali yangi obyekt yaratish uchun forma tekshirilgandan so'ng qaysi metod chaqiriladi?",
         "choices": ["form.save()", "form.create()", "form.commit()", "form.write()"], "correct": 0},
        {"text": "Bitta maydon uchun maxsus validatsiya yozish uchun qaysi metod nomlanishi ishlatiladi?",
         "choices": ["clean_<field_nomi>()", "validate_<field_nomi>()", "check_<field_nomi>()", "verify_<field_nomi>()"], "correct": 0},
        {"text": "Butun forma darajasidagi validatsiya uchun qaysi metod override qilinadi?",
         "choices": ["clean()", "validate()", "check_all()", "verify_form()"], "correct": 0},
        {"text": "Forma maydoniga qo'shimcha HTML atributlar (masalan CSS klass) qo'shish uchun nima ishlatiladi?",
         "choices": ["widget attrs={}", "meta attrs={}", "field attrs={}", "form attrs={}"], "correct": 0},
        {"text": "Ko'p qatorli matn kiritish maydoni uchun qaysi widget ishlatiladi?",
         "choices": ["forms.Textarea", "forms.TextInput", "forms.CharInput", "forms.LongInput"], "correct": 0},
        {"text": "ModelForm'da Meta.fields = '__all__' nimani anglatadi?",
         "choices": ["Modelning barcha maydonlari formaga kiritiladi", "Hech qanday maydon kiritilmaydi", "Faqat bitta maydon", "Xatolik beradi"], "correct": 0},
        {"text": "ModelForm CRUD'ning qaysi ikki amalida asosiy foydalanadi?",
         "choices": ["Create va Update", "Faqat Delete", "Faqat Read", "Faqat List"], "correct": 0},
        {"text": "Forma widget'lariga Bootstrap klasslari qo'shish nima uchun qilinadi?",
         "choices": ["Formani vizual jihatdan chiroyli ko'rsatish uchun", "Validatsiyani o'chirish uchun", "Xotira tejash uchun", "Xavfsizlikni oshirish uchun"], "correct": 0},
    ],
    "(Django) Class-Based Views — 1-qism": [
        {"text": "FBV va CBV o'rtasidagi asosiy farq nima?",
         "choices": ["FBV — oddiy funksiya, CBV — klass sifatida yoziladi", "Farqi yo'q", "FBV faqat admin uchun", "CBV faqat API uchun"], "correct": 0},
        {"text": "Barcha Class-Based View'larning bazaviy klassi qaysi?",
         "choices": ["View", "Model", "Form", "Template"], "correct": 0},
        {"text": "Statik shablonni ko'rsatuvchi eng oddiy CBV qaysi?",
         "choices": ["TemplateView", "ListView", "DetailView", "FormView"], "correct": 0},
        {"text": "Boshqa URL'ga yo'naltirish uchun qaysi CBV ishlatiladi?",
         "choices": ["RedirectView", "TemplateView", "ListView", "DetailView"], "correct": 0},
        {"text": "Obyektlar ro'yxatini ko'rsatish uchun qaysi CBV ishlatiladi?",
         "choices": ["ListView", "DetailView", "CreateView", "TemplateView"], "correct": 0},
        {"text": "Bitta obyekt tafsilotlarini ko'rsatish uchun qaysi CBV ishlatiladi?",
         "choices": ["DetailView", "ListView", "CreateView", "UpdateView"], "correct": 0},
        {"text": "CBV'ni URL'ga ulash uchun qanday sintaksis ishlatiladi?",
         "choices": ["MyView.as_view()", "MyView()", "MyView.render()", "MyView.call()"], "correct": 0},
        {"text": "Shablonga qo'shimcha kontekst ma'lumot berish uchun qaysi metod override qilinadi?",
         "choices": ["get_context_data()", "get_queryset() faqat", "add_context()", "context()"], "correct": 0},
        {"text": "ListView uchun qaysi obyektlar ro'yxati qaytarilishini belgilash uchun qaysi metod override qilinadi?",
         "choices": ["get_queryset()", "get_context_data() faqat", "get_list()", "queryset()"], "correct": 0},
        {"text": "CBV ishlatishning asosiy afzalligi nima?",
         "choices": ["Kodni qayta ishlatish (meros orqali) va tuzilganlik", "Har doim tezroq ishlashi", "Faqat kichik loyihalar uchun mos", "Faqat admin uchun ishlatiladi"], "correct": 0},
    ],
    "(Django) Class-Based Views — 2-qism (CRUD)": [
        {"text": "Yangi obyekt yaratish uchun qaysi CBV ishlatiladi?",
         "choices": ["CreateView", "UpdateView", "DeleteView", "ListView"], "correct": 0},
        {"text": "Mavjud obyektni yangilash uchun qaysi CBV ishlatiladi?",
         "choices": ["UpdateView", "CreateView", "DeleteView", "DetailView"], "correct": 0},
        {"text": "Obyektni o'chirish uchun qaysi CBV ishlatiladi?",
         "choices": ["DeleteView", "CreateView", "UpdateView", "ListView"], "correct": 0},
        {"text": "Forma bilan ishlash uchun umumiy CBV qaysi?",
         "choices": ["FormView", "TemplateView", "ListView", "RedirectView"], "correct": 0},
        {"text": "Muvaffaqiyatli amaldan keyin yo'naltiriladigan URL qaysi atribut bilan belgilanadi?",
         "choices": ["success_url", "redirect_url", "next_url", "done_url"], "correct": 0},
        {"text": "success_url'ni dinamik hisoblash kerak bo'lsa qaysi metod override qilinadi?",
         "choices": ["get_success_url()", "get_redirect()", "compute_url()", "set_url()"], "correct": 0},
        {"text": "Faqat tizimga kirgan foydalanuvchilar view'ga kirishini ta'minlovchi mixin qaysi?",
         "choices": ["LoginRequiredMixin", "PermissionRequiredMixin", "UserMixin", "AuthMixin"], "correct": 0},
        {"text": "Foydalanuvchida ma'lum ruxsat borligini talab qiluvchi mixin qaysi?",
         "choices": ["PermissionRequiredMixin", "LoginRequiredMixin", "StaffRequiredMixin", "GroupRequiredMixin"], "correct": 0},
        {"text": "CRUD nimani anglatadi?",
         "choices": ["Create, Read, Update, Delete", "Copy, Read, Update, Drop", "Create, Remove, Update, Delete", "Check, Read, Use, Delete"], "correct": 0},
        {"text": "Mini CRUD ilova (masalan kitoblar boshqaruvi) uchun odatda nechta asosiy CBV kerak bo'ladi?",
         "choices": ["To'rttasi (List, Detail, Create/Update, Delete)", "Faqat bitta", "Faqat ikkitasi", "Kamida o'ntasi"], "correct": 0},
    ],
    "(Django) Authentication (kirish/chiqish)": [
        {"text": "Django'ning o'rnatilgan autentifikatsiya tizimi qaysi ilova orqali ishlaydi?",
         "choices": ["django.contrib.auth", "django.contrib.sessions faqat", "django.contrib.admin faqat", "django.contrib.auth_system"], "correct": 0},
        {"text": "Kirish (login) sahifasi uchun tayyor CBV qaysi?",
         "choices": ["LoginView", "AuthView", "SignInView", "AccessView"], "correct": 0},
        {"text": "Chiqish (logout) uchun tayyor CBV qaysi?",
         "choices": ["LogoutView", "SignOutView", "ExitView", "EndSessionView"], "correct": 0},
        {"text": "Kirish sahifasi URL manzilini belgilovchi sozlama qaysi?",
         "choices": ["LOGIN_URL", "AUTH_URL", "SIGNIN_URL", "ACCESS_URL"], "correct": 0},
        {"text": "Muvaffaqiyatli kirishdan keyin yo'naltiriladigan sahifani belgilovchi sozlama qaysi?",
         "choices": ["LOGIN_REDIRECT_URL", "LOGIN_SUCCESS_URL", "AFTER_LOGIN_URL", "HOME_URL"], "correct": 0},
        {"text": "Chiqishdan keyin yo'naltiriladigan sahifani belgilovchi sozlama qaysi?",
         "choices": ["LOGOUT_REDIRECT_URL", "LOGOUT_URL", "AFTER_LOGOUT_URL", "EXIT_URL"], "correct": 0},
        {"text": "Django parollarni bazada qanday saqlaydi?",
         "choices": ["Hashlangan (shifrlangan) holda", "Ochiq matn (plain text) holda", "Umuman saqlamaydi", "Faqat administratorga ko'rinadigan holda"], "correct": 0},
        {"text": "Foydalanuvchi tizimga kirganligini tekshirish uchun request obyektida qaysi atribut ishlatiladi?",
         "choices": ["request.user.is_authenticated", "request.is_logged_in", "request.auth", "request.session.user"], "correct": 0},
        {"text": "django.contrib.auth qaysi standart modelni taqdim etadi?",
         "choices": ["User modeli", "Profile modeli", "Account modeli", "Session modeli"], "correct": 0},
        {"text": "Login formalarini chiroyli ko'rsatish uchun odatda nima ishlatiladi?",
         "choices": ["Bootstrap", "Faqat oddiy matn", "Excel", "PDF"], "correct": 0},
    ],
    "(Django) Ro'yxatdan o'tish va Authorization": [
        {"text": "Foydalanuvchi ro'yxatdan o'tishi uchun Django'ning tayyor formasi qaysi?",
         "choices": ["UserCreationForm", "UserRegisterForm", "SignupForm", "AccountForm"], "correct": 0},
        {"text": "Faqat tizimga kirgan foydalanuvchi view'ga kira olishi uchun qaysi dekorator ishlatiladi?",
         "choices": ["@login_required", "@auth_required", "@user_required", "@access_required"], "correct": 0},
        {"text": "CBV uchun login talab qilishda qaysi mixin ishlatiladi?",
         "choices": ["LoginRequiredMixin", "AuthMixin", "UserRequiredMixin", "SessionMixin"], "correct": 0},
        {"text": "Foydalanuvchi guruhlari (Groups) nima uchun ishlatiladi?",
         "choices": ["Bir nechta foydalanuvchiga birgalikda ruxsatlar berish uchun", "Faqat statistika uchun", "Faqat email yuborish uchun", "Faqat parolni saqlash uchun"], "correct": 0},
        {"text": "Ma'lum ruxsat (permission) talab qilishda qaysi dekorator ishlatiladi?",
         "choices": ["@permission_required", "@auth_required", "@access_required", "@group_required"], "correct": 0},
        {"text": "Permissions va Groups qaysi panel orqali ham boshqarilishi mumkin?",
         "choices": ["Admin panel", "Faqat kod orqali", "Faqat shell orqali", "Faqat migratsiya orqali"], "correct": 0},
        {"text": "Parolni tiklash (password reset) funksiyasi odatda nima orqali amalga oshiriladi?",
         "choices": ["Email orqali maxsus havola yuborish", "SMS majburiy", "Faqat administrator orqali", "Umuman mumkin emas"], "correct": 0},
        {"text": "Custom registration form yaratishning sababi nima bo'lishi mumkin?",
         "choices": ["Qo'shimcha maydonlar (masalan telefon) qo'shish uchun", "Faqat dizayn uchun", "Xavfsizlikni pasaytirish uchun", "Hech qanday sabab"], "correct": 0},
        {"text": "Authorization va Authentication o'rtasidagi farq nima?",
         "choices": ["Authentication — kim ekanligini, Authorization — nima qila olishini aniqlaydi", "Ular bir xil", "Authorization faqat parolga tegishli", "Authentication faqat ruxsatga tegishli"], "correct": 0},
        {"text": "UserCreationForm asosan qaysi ma'lumotlarni so'raydi?",
         "choices": ["Username va parol (tasdiqlash bilan)", "Faqat email", "Faqat telefon raqami", "Faqat to'liq ism"], "correct": 0},
    ],
    "(Django) Custom User Model": [
        {"text": "Django'ning standart User modelining keng tarqalgan kamchiligi nima?",
         "choices": ["Qo'shimcha maydon qo'shish qiyinroq va keyinroq almashtirish murakkab", "Umuman ishlamaydi", "Faqat superuser yarata olmaydi", "Parolni saqlay olmaydi"], "correct": 0},
        {"text": "Custom User Model yaratishda ko'proq moslashuvchanlik beruvchi bazaviy klass qaysi?",
         "choices": ["AbstractBaseUser", "AbstractUser faqat", "User", "BaseModel"], "correct": 0},
        {"text": "Mavjud User strukturasini deyarli saqlab, kengaytirish uchun qaysi bazaviy klass qulayroq?",
         "choices": ["AbstractUser", "AbstractBaseUser faqat", "Model", "BaseUser"], "correct": 0},
        {"text": "Username o'rniga email bilan login qilish uchun nima sozlanishi kerak?",
         "choices": ["USERNAME_FIELD = 'email'", "LOGIN_FIELD = 'email'", "AUTH_FIELD = 'email'", "EMAIL_LOGIN = True"], "correct": 0},
        {"text": "Loyihada qaysi User modeli ishlatilishini belgilovchi sozlama qaysi?",
         "choices": ["AUTH_USER_MODEL", "USER_MODEL", "CUSTOM_USER", "DEFAULT_USER_MODEL"], "correct": 0},
        {"text": "Custom User Model qachon loyihaga qo'shilishi tavsiya etiladi?",
         "choices": ["Loyiha boshida, birinchi migratsiyadan oldin", "Loyiha oxirida", "Hech qachon", "Faqat production'da"], "correct": 0},
        {"text": "Foydalanuvchi rasmi uchun qo'shimcha maydon qanday nomlanishi mumkin?",
         "choices": ["avatar", "faqat rasm nomi bo'lishi shart emas, istalgan nom", "photo majburiy", "img majburiy"], "correct": 0},
        {"text": "Profile model yondashuvi nimani anglatadi?",
         "choices": ["User modelini o'zgartirmasdan, unga OneToOne bog'langan qo'shimcha model yaratish", "User modelini butunlay o'chirish", "Faqat admin panelda ma'lumot saqlash", "Hech narsa"], "correct": 0},
        {"text": "AbstractBaseUser ishlatilganda dasturchi qo'shimcha nimani o'zi yozishi kerak bo'ladi?",
         "choices": ["UserManager klassini", "Faqat migratsiyalarni", "Faqat admin.py'ni", "Hech narsani"], "correct": 0},
        {"text": "Custom User Model bilan ishlashda AUTH_USER_MODEL nimaga ishora qiladi?",
         "choices": ["'app_nomi.ModelNomi' formatidagi satrga", "Faqat model klassiga to'g'ridan-to'g'ri", "URL manziliga", "Fayl yo'liga"], "correct": 0},
    ],
    "(Django) Media fayllar (rasm/file upload)": [
        {"text": "Foydalanuvchi yuklagan fayllar odatda qaysi papkaga saqlanadi?",
         "choices": ["MEDIA_ROOT belgilagan papkaga", "STATIC_ROOT papkasiga", "templates papkasiga", "manage.py yoniga"], "correct": 0},
        {"text": "Media fayllarga URL orqali kirish uchun qaysi sozlama ishlatiladi?",
         "choices": ["MEDIA_URL", "STATIC_URL", "FILE_URL", "UPLOAD_URL"], "correct": 0},
        {"text": "Rasm yuklash uchun model maydoni qaysi turdan foydalanadi?",
         "choices": ["ImageField", "FileField faqat umumiy", "CharField", "URLField"], "correct": 0},
        {"text": "Rasm bilan ishlash uchun (masalan validatsiya) qaysi kutubxona kerak bo'ladi?",
         "choices": ["Pillow", "NumPy", "Requests", "BeautifulSoup"], "correct": 0},
        {"text": "Fayl yuklovchi HTML formada qaysi atribut bo'lishi shart?",
         "choices": ["enctype=\"multipart/form-data\"", "method=\"file\"", "type=\"upload\"", "accept-file=\"true\""], "correct": 0},
        {"text": "Umumiy fayl (rasm bo'lmasligi mumkin) yuklash uchun qaysi maydon turi ishlatiladi?",
         "choices": ["FileField", "ImageField faqat", "BinaryField", "BlobField"], "correct": 0},
        {"text": "Yuklangan rasm hajmini cheklash nima uchun muhim?",
         "choices": ["Server resurslarini va xavfsizlikni himoya qilish uchun", "Faqat dizayn uchun", "Hech qanday sababsiz", "Faqat SEO uchun"], "correct": 0},
        {"text": "Shablonda yuklangan rasmni ko'rsatish uchun nima ishlatiladi?",
         "choices": ["{{ obj.rasm.url }}", "{{ obj.rasm.path }}", "{{ obj.rasm.name }} faqat", "{{ obj.rasm }} to'g'ridan-to'g'ri har doim yetarli"], "correct": 0},
        {"text": "MEDIA_ROOT va MEDIA_URL o'rtasidagi farq nima?",
         "choices": ["ROOT — serverdagi jismoniy yo'l, URL — brauzerdan foydalaniladigan manzil", "Farqi yo'q", "URL — jismoniy yo'l", "ROOT — faqat rasm uchun"], "correct": 0},
        {"text": "Production'da media fayllarni odatda kim xizmat qiladi?",
         "choices": ["Nginx yoki bulutli saqlash xizmati (Django emas)", "Har doim Django runserver", "Faqat brauzer", "Hech kim"], "correct": 0},
    ],
    "(Django) Pagination, Search va Filter": [
        {"text": "Natijalarni sahifalarga bo'lish uchun qaysi klass ishlatiladi?",
         "choices": ["Paginator", "PageSplitter", "ListDivider", "ChunkMaker"], "correct": 0},
        {"text": "CBV'da sahifa hajmini belgilovchi atribut qaysi?",
         "choices": ["paginate_by", "page_size", "items_per_page", "per_page"], "correct": 0},
        {"text": "Bootstrap bilan sahifalash tugmalarini chiroyli ko'rsatish uchun nima ishlatiladi?",
         "choices": ["Bootstrap pagination komponenti", "Faqat oddiy matn", "JavaScript majburiy", "CSS animatsiya majburiy"], "correct": 0},
        {"text": "Qidiruv funksiyasini murakkab OR/AND shartlar bilan yozish uchun qaysi obyekt ishlatiladi?",
         "choices": ["Q obyektlari", "F obyektlari", "Search obyekti", "Filter obyekti"], "correct": 0},
        {"text": "URL orqali kelgan GET parametrlariga qanday murojaat qilinadi?",
         "choices": ["request.GET", "request.params", "request.query", "request.args"], "correct": 0},
        {"text": "Foydalanuvchi qidiruv so'zi kiritgan formaning odatiy metodi qaysi?",
         "choices": ["GET", "POST majburiy", "PUT", "DELETE"], "correct": 0},
        {"text": "Sahifalashda joriy sahifa raqami odatda qanday parametr orqali uzatiladi?",
         "choices": ["?page=2 kabi query parametr", "URL yo'lida majburiy", "Faqat cookie orqali", "Faqat session orqali"], "correct": 0},
        {"text": "Filtrlash va saralashni birga qo'llashda odatiy yondashuv qanday?",
         "choices": ["QuerySet'ga filter() va order_by() ketma-ket qo'llanadi", "Faqat Python darajasida qo'lda saralash", "Bazadan barcha ma'lumotni olib, Excel'da saralash", "Mumkin emas"], "correct": 0},
        {"text": "Paginator klassi asosan nima bilan ishlaydi?",
         "choices": ["QuerySet yoki list bilan", "Faqat string bilan", "Faqat dictionary bilan", "Faqat fayl bilan"], "correct": 0},
        {"text": "Katta ma'lumotlar ro'yxatini bittada ko'rsatish o'rniga sahifalashning asosiy sababi nima?",
         "choices": ["Ishlash tezligi va foydalanuvchi tajribasini yaxshilash", "Faqat dizayn uchun", "Ma'lumotni yashirish uchun", "Hech qanday sabab yo'q"], "correct": 0},
    ],
    "(Django) Django ORM chuqur": [
        {"text": "Murakkab OR shartlarini yozish uchun qaysi obyekt ishlatiladi?",
         "choices": ["Q obyektlari", "F obyektlari", "Filter obyekti", "Case obyekti"], "correct": 0},
        {"text": "Baza darajasida ustunlar orasida hisoblash (masalan bir ustunni boshqasiga solishtirish) uchun qaysi obyekt ishlatiladi?",
         "choices": ["F obyektlari", "Q obyektlari", "Value obyektlari", "Expr obyektlari"], "correct": 0},
        {"text": "N+1 muammosini oldini olish uchun ForeignKey munosabatlarida qaysi metod ishlatiladi?",
         "choices": ["select_related()", "prefetch_only()", "join()", "eager()"], "correct": 0},
        {"text": "ManyToMany yoki teskari ForeignKey munosabatlarda samaradorlikni oshirish uchun qaysi metod ishlatiladi?",
         "choices": ["prefetch_related()", "select_related() faqat", "join()", "cache()"], "correct": 0},
        {"text": "Guruhlangan ma'lumotlar ustida statistik hisoblash (masalan Count, Sum) uchun qaysi metod ishlatiladi?",
         "choices": ["annotate()", "aggregate() faqat butun queryset uchun", "group()", "calc()"], "correct": 0},
        {"text": "Butun QuerySet bo'yicha bitta umumiy statistik natija olish uchun qaysi metod ishlatiladi?",
         "choices": ["aggregate()", "annotate() faqat", "group()", "summary()"], "correct": 0},
        {"text": "Faqat kerakli ustunlarni dictionary ko'rinishida olish uchun qaysi metod ishlatiladi?",
         "choices": ["values()", "only_fields()", "select()", "get_fields()"], "correct": 0},
        {"text": "Faqat kerakli ustunlarni tuple ko'rinishida olish uchun qaysi metod ishlatiladi?",
         "choices": ["values_list()", "values() faqat", "tuple_fields()", "as_tuple()"], "correct": 0},
        {"text": "Django ORM orqali to'g'ridan-to'g'ri SQL yozish imkoniyati bormi?",
         "choices": ["Ha, Raw SQL so'rovlar orqali", "Yo'q, umuman mumkin emas", "Faqat admin panel orqali", "Faqat migratsiyalarda"], "correct": 0},
        {"text": "N+1 muammosi nima uchun yomon?",
         "choices": ["Har bir bog'liq obyekt uchun alohida so'rov yuborilib, samaradorlikni pasaytiradi", "Xavfsizlikni buzadi", "Faqat kod chiroyliligiga ta'sir qiladi", "Hech qanday ta'siri yo'q"], "correct": 0},
    ],
    "(Django) Email, Cache, Sessions va xavfsizlik": [
        {"text": "Django orqali email yuborish uchun qaysi funksiya ishlatiladi?",
         "choices": ["send_mail()", "mail_send()", "email_send()", "post_mail()"], "correct": 0},
        {"text": "Sessiya ma'lumotlariga murojaat qilish uchun qaysi obyekt ishlatiladi?",
         "choices": ["request.session", "request.cookies faqat", "request.cache", "request.data"], "correct": 0},
        {"text": "Cookie va Session o'rtasidagi asosiy farq nima?",
         "choices": ["Session ma'lumoti server tomonida, cookie odatda mijoz tomonida saqlanadi", "Farqi yo'q", "Cookie har doim xavfsizroq", "Session faqat login uchun"], "correct": 0},
        {"text": "Sahifani keshlash (cache) uchun qaysi dekorator ishlatiladi?",
         "choices": ["@cache_page", "@cache_view", "@cached", "@store_page"], "correct": 0},
        {"text": "SQL injection hujumidan himoyalanish uchun Django ORM nima qiladi?",
         "choices": ["So'rovlarni avtomatik parametrlaydi (escape qiladi)", "Hech narsa qilmaydi", "Faqat admin panelda himoya qiladi", "Faqat POST so'rovlarda"], "correct": 0},
        {"text": "XSS hujumi nimani anglatadi?",
         "choices": ["Cross-Site Scripting", "External System Security", "Extended Session Storage", "XML Site Structure"], "correct": 0},
        {"text": "Maxfiy sozlamalarni (parol, token) kodga yozmaslik uchun nima ishlatiladi?",
         "choices": [".env fayl", "settings.py'ga ochiq yozish", "README fayl", "Git commit"], "correct": 0},
        {"text": "Production'da ALLOWED_HOSTS bo'sh qoldirilsa (DEBUG=False bilan) nima bo'ladi?",
         "choices": ["Server so'rovlarni rad etadi", "Hech narsa, hammasi ishlaydi", "Avtomatik barcha domenlarga ruxsat beriladi", "Faqat ogohlantirish chiqadi"], "correct": 0},
        {"text": "Memory cache nima uchun ishlatiladi?",
         "choices": ["Tez-tez so'raladigan ma'lumotni xotirada saqlab, tezlashtirish uchun", "Fayl saqlash uchun", "Email yuborish uchun", "URL yaratish uchun"], "correct": 0},
        {"text": "DEBUG=False bo'lganda xato yuz bersa foydalanuvchiga nima ko'rsatiladi?",
         "choices": ["Umumiy xatolik sahifasi (texnik tafsilotlarsiz)", "To'liq Python traceback", "Baza paroli", "Server manzili"], "correct": 0},
    ],
    "(Django) REST API va DRF kirish": [
        {"text": "REST API'da ma'lumot olish uchun qaysi HTTP metodi ishlatiladi?",
         "choices": ["GET", "POST", "DELETE", "PUT"], "correct": 0},
        {"text": "REST API'da yangi ma'lumot yaratish uchun qaysi HTTP metodi ishlatiladi?",
         "choices": ["POST", "GET", "DELETE", "HEAD"], "correct": 0},
        {"text": "REST API'da ma'lumotni to'liq yangilash uchun qaysi HTTP metodi ishlatiladi?",
         "choices": ["PUT", "GET", "POST faqat", "HEAD"], "correct": 0},
        {"text": "Muvaffaqiyatli so'rov uchun odatiy status kodi qaysi?",
         "choices": ["200", "404", "500", "301"], "correct": 0},
        {"text": "Yangi resurs yaratilganda odatiy status kodi qaysi?",
         "choices": ["201", "200", "204", "202"], "correct": 0},
        {"text": "Resurs topilmaganda qaysi status kodi qaytariladi?",
         "choices": ["404", "400", "401", "500"], "correct": 0},
        {"text": "Ruxsat berilmagan (autentifikatsiya kerak) holatda qaysi status kodi qaytariladi?",
         "choices": ["401", "403", "404", "400"], "correct": 0},
        {"text": "DRF nimani anglatadi?",
         "choices": ["Django REST Framework", "Django Response Format", "Direct Request Filter", "Data Rest Function"], "correct": 0},
        {"text": "DRF'ni ulash uchun INSTALLED_APPS'ga qaysi nom qo'shiladi?",
         "choices": ["'rest_framework'", "'drf'", "'django_rest'", "'api_framework'"], "correct": 0},
        {"text": "API'larni brauzerda interaktiv ko'rish imkoniyati DRF'da qanday ataladi?",
         "choices": ["Browsable API", "Interactive API", "Live API", "Visual API"], "correct": 0},
    ],
    "(Django) Serializers — 1-qism": [
        {"text": "Serializer asosan nima uchun ishlatiladi?",
         "choices": ["Model/ma'lumotni JSON kabi formatga aylantirish va aksincha", "Faqat parolni shifrlash uchun", "URL yaratish uchun", "Baza yaratish uchun"], "correct": 0},
        {"text": "Python obyektini JSON'ga aylantirish jarayoni qanday ataladi?",
         "choices": ["Serialization", "Deserialization", "Validation", "Migration"], "correct": 0},
        {"text": "JSON'dan Python obyektiga qaytarish jarayoni qanday ataladi?",
         "choices": ["Deserialization", "Serialization", "Rendering", "Parsing only"], "correct": 0},
        {"text": "Model asosida avtomatik serializer yaratish uchun qaysi klass ishlatiladi?",
         "choices": ["ModelSerializer", "AutoSerializer", "BaseSerializer faqat", "QuickSerializer"], "correct": 0},
        {"text": "ModelSerializer'da qaysi maydonlar ishlatilishini belgilovchi ichki klass qaysi?",
         "choices": ["Meta", "Config", "Options", "Fields"], "correct": 0},
        {"text": "Faqat o'qish uchun (javobda ko'rinadigan, lekin yozib bo'lmaydigan) maydonlar qaysi atribut bilan belgilanadi?",
         "choices": ["read_only_fields", "output_fields", "view_fields", "display_only"], "correct": 0},
        {"text": "Faqat yozish uchun (masalan parol) maydonlar qaysi atribut bilan belgilanadi?",
         "choices": ["write_only_fields", "input_fields", "hidden_fields", "secret_fields"], "correct": 0},
        {"text": "Serializer'ni Django shell'da sinash uchun odatda nima qilinadi?",
         "choices": ["Serializer obyektini yaratib .data ni tekshirish", "Faqat brauzerda ochish", "Faqat admin panelda ko'rish", "Faqat testda tekshirish shart"], "correct": 0},
        {"text": "exclude atributi Meta klassida nima qiladi?",
         "choices": ["Ko'rsatilgan maydonlarni serializerdan chiqarib tashlaydi", "Faqat ko'rsatilgan maydonlarni qoldiradi", "Hech narsa qilmaydi", "Barcha maydonlarni o'chiradi"], "correct": 0},
        {"text": "Serializer klassi odatda qaysi modulga yoziladi?",
         "choices": ["serializers.py", "views.py", "models.py", "forms.py"], "correct": 0},
    ],
    "(Django) Serializers — 2-qism (validatsiya va nested)": [
        {"text": "Bitta maydon uchun maxsus validatsiya yozish uchun qaysi metod nomlanishi ishlatiladi?",
         "choices": ["validate_<field_nomi>()", "clean_<field_nomi>()", "check_<field_nomi>()", "verify_<field_nomi>()"], "correct": 0},
        {"text": "Butun serializer darajasidagi validatsiya uchun qaysi metod override qilinadi?",
         "choices": ["validate()", "clean()", "check_all()", "verify()"], "correct": 0},
        {"text": "Validatsiya xatosini chiqarish uchun qaysi klass ishlatiladi?",
         "choices": ["serializers.ValidationError", "serializers.Error", "ValueError faqat", "FormError"], "correct": 0},
        {"text": "Yangi obyekt yaratish logikasi qaysi metodda yoziladi?",
         "choices": ["create()", "save() faqat to'g'ridan-to'g'ri", "new()", "insert()"], "correct": 0},
        {"text": "Mavjud obyektni yangilash logikasi qaysi metodda yoziladi?",
         "choices": ["update()", "modify()", "change()", "edit()"], "correct": 0},
        {"text": "Bog'liq modelni ham serialize qiluvchi serializer ichida boshqa serializer ishlatilishi qanday ataladi?",
         "choices": ["Nested serializer", "Chained serializer", "Linked serializer", "Sub serializer only"], "correct": 0},
        {"text": "Modelda yo'q, lekin serializer chiqishida qo'shimcha hisoblab qo'shiladigan maydon qaysi field turi bilan yaratiladi?",
         "choices": ["SerializerMethodField", "ComputedField", "ExtraField", "CustomField"], "correct": 0},
        {"text": "SerializerMethodField qiymati qanday hisoblanadi?",
         "choices": ["get_<field_nomi>() metodi orqali", "Avtomatik modeldan", "Faqat sozlamalardan", "Har doim None bo'ladi"], "correct": 0},
        {"text": "source= parametri serializer maydonida nima uchun ishlatiladi?",
         "choices": ["Maydonni boshqa model atributiga bog'lash uchun", "Faqat nomini o'zgartirish uchun", "Validatsiyani o'chirish uchun", "Xavfsizlik uchun"], "correct": 0},
        {"text": "create() va update() metodlarini override qilishning sababi nima?",
         "choices": ["Standart saqlash mantig'ini o'zgartirish/kengaytirish uchun", "Faqat tezlik uchun", "Xavfsizlikni pasaytirish uchun", "Hech qanday sabab"], "correct": 0},
    ],
    "(Django) APIView va Generic Views": [
        {"text": "Funksiya uslubida API view yozish uchun qaysi dekorator ishlatiladi?",
         "choices": ["@api_view", "@rest_view", "@drf_view", "@endpoint"], "correct": 0},
        {"text": "DRF'da so'rov ma'lumotlari qaysi obyekt orqali olinadi?",
         "choices": ["Request (DRF'ning kengaytirilgan obyekti)", "HttpRequest faqat", "Query obyekti", "Params obyekti"], "correct": 0},
        {"text": "DRF'da javob qaytarish uchun qaysi klass ishlatiladi?",
         "choices": ["Response", "HttpResponse faqat", "JsonResponse faqat", "ApiResponse"], "correct": 0},
        {"text": "Class-Based uslubda API yozish uchun bazaviy klass qaysi?",
         "choices": ["APIView", "View faqat oddiy Django", "ModelView", "RestView"], "correct": 0},
        {"text": "Faqat ro'yxat qaytaruvchi generic view qaysi?",
         "choices": ["ListAPIView", "RetrieveAPIView", "CreateAPIView", "UpdateAPIView"], "correct": 0},
        {"text": "Bitta obyektni qaytaruvchi generic view qaysi?",
         "choices": ["RetrieveAPIView", "ListAPIView", "CreateAPIView", "DestroyAPIView"], "correct": 0},
        {"text": "Ro'yxat va yaratishni birlashtiruvchi generic view qaysi?",
         "choices": ["ListCreateAPIView", "RetrieveUpdateAPIView", "CreateAPIView faqat", "ListAPIView faqat"], "correct": 0},
        {"text": "Bitta obyektni ko'rish, yangilash va o'chirishni birlashtiruvchi generic view qaysi?",
         "choices": ["RetrieveUpdateDestroyAPIView", "ListCreateAPIView", "CreateAPIView", "UpdateAPIView faqat"], "correct": 0},
        {"text": "DRF'dagi Mixin'lar nima uchun ishlatiladi?",
         "choices": ["Generic view'lar ichida takroriy CRUD logikasini qayta ishlatish uchun", "Faqat autentifikatsiya uchun", "Faqat sahifalash uchun", "Faqat filtr uchun"], "correct": 0},
        {"text": "@api_view dekoratorida qaysi HTTP metodlar ruxsat etilishi ko'rsatiladi?",
         "choices": ["@api_view(['GET', 'POST']) kabi ro'yxat orqali", "Har doim barcha metodlar avtomatik", "Faqat GET avtomatik", "Ko'rsatish shart emas"], "correct": 0},
    ],
    "(Django) ViewSet va Routers + GitHub jamoa ishi": [
        {"text": "CRUD amallarini bitta klassda birlashtiruvchi DRF tuzilmasi qaysi?",
         "choices": ["ModelViewSet", "APIView", "GenericView", "MixinView"], "correct": 0},
        {"text": "Faqat o'qish (list/retrieve) uchun ViewSet qaysi?",
         "choices": ["ReadOnlyModelViewSet", "ModelViewSet", "ListViewSet", "GetViewSet"], "correct": 0},
        {"text": "ViewSet uchun URL'larni avtomatik generatsiya qiluvchi vosita qaysi?",
         "choices": ["Router (DefaultRouter, SimpleRouter)", "Path builder", "URL factory", "AutoMapper"], "correct": 0},
        {"text": "ViewSet'ga standart CRUD'dan tashqari maxsus endpoint qo'shish uchun qaysi dekorator ishlatiladi?",
         "choices": ["@action", "@custom_route", "@extra_endpoint", "@special"], "correct": 0},
        {"text": "DefaultRouter SimpleRouter'dan qanday farq qiladi?",
         "choices": ["DefaultRouter qo'shimcha API root view ham yaratadi", "Farqi yo'q", "SimpleRouter tezroq har doim", "DefaultRouter faqat GET qo'llab-quvvatlaydi"], "correct": 0},
        {"text": "ViewSet, APIView va Generic Views orasida eng yuqori darajadagi abstraksiya qaysi?",
         "choices": ["ViewSet", "APIView", "Generic View", "Barchasi bir xil darajada"], "correct": 0},
        {"text": "Yangi funksiya ustida ishlash uchun Git'da odatda nima yaratiladi?",
         "choices": ["Yangi branch (tarmoq)", "Yangi repository har doim", "Yangi fayl tizimi", "Yangi server"], "correct": 0},
        {"text": "Branch'lar orasida joriy branch'ni almashtirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git checkout yoki git switch", "git change", "git move", "git select"], "correct": 0},
        {"text": "Ikki branch'ni birlashtirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git merge", "git join", "git combine", "git link"], "correct": 0},
        {"text": "GitHub'da kod o'zgarishlarini ko'rib chiqish va taklif qilish jarayoni qanday ataladi?",
         "choices": ["Pull Request va kod review", "Direct push only", "Force commit", "Silent merge"], "correct": 0},
    ],
    "(Django) Authentication (DRF)": [
        {"text": "DRF'da brauzer sessiyasiga asoslangan autentifikatsiya turi qaysi?",
         "choices": ["SessionAuthentication", "TokenAuthentication", "BasicAuthentication", "JWTAuthentication"], "correct": 0},
        {"text": "Foydalanuvchi nomi va parolni har so'rovda yuborishga asoslangan oddiy autentifikatsiya turi qaysi?",
         "choices": ["BasicAuthentication", "SessionAuthentication", "TokenAuthentication", "OAuth"], "correct": 0},
        {"text": "DRF'ning o'rnatilgan token asosidagi autentifikatsiyasi qanday ataladi?",
         "choices": ["TokenAuthentication", "SessionAuthentication", "BasicAuthentication", "CookieAuthentication"], "correct": 0},
        {"text": "JWT nimani anglatadi?",
         "choices": ["JSON Web Token", "Java Web Toolkit", "Just Web Trigger", "JSON Write Type"], "correct": 0},
        {"text": "Django'da JWT ishlatish uchun mashhur kutubxona qaysi?",
         "choices": ["djangorestframework-simplejwt", "django-token", "drf-auth", "pyjwt-django"], "correct": 0},
        {"text": "JWT tizimida access token muddati tugaganda odatda nima ishlatiladi?",
         "choices": ["Refresh token orqali yangi access token olish", "Foydalanuvchi qayta ro'yxatdan o'tishi", "Hech narsa qilinmaydi", "Baza qayta ishga tushiriladi"], "correct": 0},
        {"text": "Token'ni bekor qilish (logout) uchun mexanizm qanday ataladi?",
         "choices": ["Token blacklist", "Token delete only", "Token reset", "Token clear"], "correct": 0},
        {"text": "API'ni qo'lda sinash uchun mashhur vositalar qaysilar?",
         "choices": ["Postman yoki Thunder Client", "Faqat brauzer manzil satri", "Faqat curl majburiy", "Excel"], "correct": 0},
        {"text": "So'rovda token qaysi HTTP header orqali yuboriladi?",
         "choices": ["Authorization", "Content-Type", "Accept", "X-Token faqat"], "correct": 0},
        {"text": "SessionAuthentication va TokenAuthentication qachon mos ravishda ishlatiladi?",
         "choices": ["Session — brauzer ilovalarida, Token — mobil/tashqi klientlarda", "Ular bir xil holatda ishlatiladi", "Session faqat mobil uchun", "Token faqat brauzer uchun"], "correct": 0},
    ],
    "(Django) Permissions": [
        {"text": "Har kimga ruxsat beruvchi DRF permission klassi qaysi?",
         "choices": ["AllowAny", "IsAuthenticated", "IsAdminUser", "DenyAll"], "correct": 0},
        {"text": "Faqat tizimga kirgan foydalanuvchilarga ruxsat beruvchi klass qaysi?",
         "choices": ["IsAuthenticated", "AllowAny", "IsAdminUser", "IsStaff"], "correct": 0},
        {"text": "Faqat admin (staff) foydalanuvchilarga ruxsat beruvchi klass qaysi?",
         "choices": ["IsAdminUser", "IsAuthenticated", "AllowAny", "IsSuperuser"], "correct": 0},
        {"text": "O'qish uchun hammaga, yozish uchun faqat autentifikatsiyalanganlarga ruxsat beruvchi klass qaysi?",
         "choices": ["IsAuthenticatedOrReadOnly", "IsAuthenticated", "AllowAny", "ReadOnlyPermission"], "correct": 0},
        {"text": "Django modelidagi ruxsatlarga asoslangan DRF permission klassi qaysi?",
         "choices": ["DjangoModelPermissions", "ModelPermission", "AutoPermission", "BasePermission faqat"], "correct": 0},
        {"text": "Obyekt darajasidagi ruxsatlar (masalan faqat egasi tahrirlay olishi) qanday ataladi?",
         "choices": ["Object-level permissions", "Global permissions", "Static permissions", "Field-level permissions"], "correct": 0},
        {"text": "Maxsus permission klassi yozishda umumiy so'rov ruxsatini tekshiruvchi metod qaysi?",
         "choices": ["has_permission()", "check_permission()", "validate_permission()", "verify_access()"], "correct": 0},
        {"text": "Maxsus permission klassida bitta obyektga nisbatan ruxsatni tekshiruvchi metod qaysi?",
         "choices": ["has_object_permission()", "has_permission() faqat", "check_object()", "verify_object()"], "correct": 0},
        {"text": "Custom Permission klassi qaysi bazaviy klassdan meros oladi?",
         "choices": ["permissions.BasePermission", "permissions.Base", "AccessControl", "AuthBase"], "correct": 0},
        {"text": "permission_classes atributi qayerda belgilanadi?",
         "choices": ["View yoki ViewSet klassida", "Faqat settings.py'da", "Faqat model.py'da", "Faqat urls.py'da"], "correct": 0},
    ],
    "(Django) Filtering, Search, Ordering, Pagination": [
        {"text": "Matn bo'yicha qidiruvni yoqish uchun qaysi filter backend ishlatiladi?",
         "choices": ["SearchFilter", "OrderingFilter", "DjangoFilterBackend", "QueryFilter"], "correct": 0},
        {"text": "Natijalarni saralashga imkon beruvchi filter backend qaysi?",
         "choices": ["OrderingFilter", "SearchFilter", "DjangoFilterBackend", "SortFilter"], "correct": 0},
        {"text": "Aniq maydon qiymatlariga ko'ra filtrlash uchun keng qo'llaniladigan kutubxona qaysi?",
         "choices": ["django-filter (DjangoFilterBackend)", "django-search", "django-query", "django-order"], "correct": 0},
        {"text": "Sahifa raqamiga asoslangan pagination turi qaysi?",
         "choices": ["PageNumberPagination", "LimitOffsetPagination", "CursorPagination", "SimplePagination"], "correct": 0},
        {"text": "Limit va offset parametrlariga asoslangan pagination turi qaysi?",
         "choices": ["LimitOffsetPagination", "PageNumberPagination", "CursorPagination", "OffsetOnly"], "correct": 0},
        {"text": "Qidiruv qilinadigan maydonlar ViewSet'da qaysi atribut orqali belgilanadi?",
         "choices": ["search_fields", "filter_fields", "search_by", "query_fields"], "correct": 0},
        {"text": "django-filter'da qaysi maydonlar bo'yicha filtrlash mumkinligini belgilovchi atribut qaysi?",
         "choices": ["filterset_fields", "filter_fields_list", "search_fields", "query_fields"], "correct": 0},
        {"text": "View yoki ViewSet'da qaysi filter backend'lar ishlatilishini belgilovchi atribut qaysi?",
         "choices": ["filter_backends", "backends", "filters_list", "active_filters"], "correct": 0},
        {"text": "Pagination sinfini butun loyiha uchun standart qilib belgilash qayerda amalga oshiriladi?",
         "choices": ["settings.py REST_FRAMEWORK sozlamasida", "Har bir view'da alohida majburiy", "urls.py'da", "models.py'da"], "correct": 0},
        {"text": "Custom pagination klassi yaratishning sababi nima bo'lishi mumkin?",
         "choices": ["Sahifa hajmi yoki javob formatini o'ziga xos qilish", "Faqat tezlik uchun", "Xavfsizlik uchun majburiy", "Hech qanday sabab"], "correct": 0},
    ],
    "(Django) Throttling, CORS va Swagger + GitHub konflikt": [
        {"text": "So'rovlar sonini cheklash mexanizmi qanday ataladi?",
         "choices": ["Throttling (Rate limiting)", "Pagination", "Filtering", "Caching"], "correct": 0},
        {"text": "Anonim foydalanuvchilar uchun so'rov chastotasini cheklovchi klass qaysi?",
         "choices": ["AnonRateThrottle", "UserRateThrottle", "ScopedRateThrottle", "GlobalThrottle"], "correct": 0},
        {"text": "Tizimga kirgan foydalanuvchilar uchun so'rov chastotasini cheklovchi klass qaysi?",
         "choices": ["UserRateThrottle", "AnonRateThrottle", "PublicThrottle", "OpenThrottle"], "correct": 0},
        {"text": "Boshqa domendan API'ga so'rov yuborishga ruxsat berish uchun qaysi kutubxona ishlatiladi?",
         "choices": ["django-cors-headers", "django-cross-origin", "django-api-access", "django-remote"], "correct": 0},
        {"text": "CORS nimani anglatadi?",
         "choices": ["Cross-Origin Resource Sharing", "Central Origin Request System", "Cross Object Request Service", "Client Origin Response Sharing"], "correct": 0},
        {"text": "API hujjatlarini avtomatik generatsiya qiluvchi mashhur DRF kutubxonasi qaysi?",
         "choices": ["drf-spectacular", "drf-docs-auto", "django-swagger-gen", "api-doc-builder"], "correct": 0},
        {"text": "API versiyalashning maqsadi nima?",
         "choices": ["Eski klientlarni buzmasdan API'ni rivojlantirish", "Faqat dizayn uchun", "Xavfsizlikni pasaytirish", "Bazani optimallashtirish"], "correct": 0},
        {"text": "Git'da ikki branch bir xil qatorni turlicha o'zgartirsa nima yuz beradi?",
         "choices": ["Merge conflict (birlashtirish nizosi)", "Avtomatik hal bo'ladi har doim", "Fayl o'chadi", "Hech narsa"], "correct": 0},
        {"text": "Merge conflict'ni hal qilish uchun umumiy yondashuv qanday?",
         "choices": ["Nizoli qismlarni qo'lda ko'rib chiqib, to'g'ri versiyani tanlash", "Fayl butunlay o'chiriladi", "Avtomatik hal bo'lishini kutish", "Repository o'chiriladi"], "correct": 0},
        {"text": "git rebase asosiy vazifasi nima?",
         "choices": ["Commit tarixini boshqa branch ustiga qayta joylashtirish", "Faylni o'chirish", "Yangi repository yaratish", "Branch'ni o'chirish"], "correct": 0},
    ],
    "(Django) Telegram Bot — 1-qism (Aiogram asoslari)": [
        {"text": "Telegram bot yaratish uchun avval kim bilan gaplashish kerak?",
         "choices": ["BotFather", "Telegram Support", "Admin", "API Gateway"], "correct": 0},
        {"text": "BotFather'dan olinadigan maxfiy kalit qanday ataladi?",
         "choices": ["Bot token", "API key faqat umumiy", "Secret code", "Access ID"], "correct": 0},
        {"text": "Python'da Telegram bot yaratish uchun mashhur kutubxona qaysi?",
         "choices": ["Aiogram", "Flask-Telegram", "Django-Bot", "PyTelegram-Core"], "correct": 0},
        {"text": "Aiogram'ni o'rnatish uchun qaysi buyruq ishlatiladi?",
         "choices": ["pip install aiogram", "npm install aiogram", "django-admin aiogram", "apt install aiogram"], "correct": 0},
        {"text": "Bot bilan suhbatni boshlash uchun odatiy buyruq qaysi?",
         "choices": ["/start", "/begin", "/init", "/run"], "correct": 0},
        {"text": "Foydalanuvchi buyrug'iga javob beruvchi funksiya qanday ataladi?",
         "choices": ["Handler", "Listener only", "Responder only", "Trigger only"], "correct": 0},
        {"text": "Aiogram asosan qaysi dasturlash uslubida ishlaydi?",
         "choices": ["Async/await (asinxron)", "Faqat sinxron", "Faqat multithreading", "Faqat multiprocessing"], "correct": 0},
        {"text": "Bot server tomonidan doimiy so'rov yuborib yangilanishlarni tekshiradigan rejim qanday ataladi?",
         "choices": ["Polling", "Webhook", "Streaming", "Pushing"], "correct": 0},
        {"text": "Xabar ostida tugmalar ko'rsatish uchun qaysi tugma turi ishlatiladi?",
         "choices": ["Inline tugmalar", "Reply tugmalar faqat", "Hidden tugmalar", "Static tugmalar"], "correct": 0},
        {"text": "Klaviatura o'rnini egallovchi tugmalar qanday ataladi?",
         "choices": ["Reply tugmalar", "Inline tugmalar faqat", "Popup tugmalar", "Menu tugmalar"], "correct": 0},
    ],
    "(Django) Telegram Bot — 2-qism (Django + ngrok + Webhook)": [
        {"text": "Polling va Webhook o'rtasidagi asosiy farq nima?",
         "choices": ["Polling doimiy so'raydi, Webhook Telegram'dan xabar keladi", "Farqi yo'q", "Webhook faqat test uchun", "Polling faqat production uchun"], "correct": 0},
        {"text": "Production muhitda odatda qaysi usul tavsiya etiladi?",
         "choices": ["Webhook", "Polling", "Ikkalasi ham teng darajada", "Hech biri"], "correct": 0},
        {"text": "Django loyihasida bot uchun so'rovlarni qabul qiladigan qism nima bo'ladi?",
         "choices": ["Maxsus view (POST endpoint)", "Faqat admin panel", "Faqat model", "Faqat migratsiya"], "correct": 0},
        {"text": "Lokal serverni vaqtincha internetga ochish uchun qaysi vosita ishlatiladi?",
         "choices": ["ngrok", "Docker", "nginx faqat", "gunicorn faqat"], "correct": 0},
        {"text": "ngrok orqali lokal 8000-portni ochish uchun qaysi buyruq ishlatiladi?",
         "choices": ["ngrok http 8000", "ngrok open 8000", "ngrok start 8000", "ngrok expose 8000"], "correct": 0},
        {"text": "Telegram webhook faqat qanday manzillar bilan ishlaydi?",
         "choices": ["HTTPS manzillar bilan", "HTTP manzillar bilan ham", "FTP manzillar bilan", "Faqat lokal IP bilan"], "correct": 0},
        {"text": "Webhook manzilini Telegram'ga o'rnatish uchun qaysi metod chaqiriladi?",
         "choices": ["setWebhook", "registerWebhook", "connectWebhook", "initWebhook"], "correct": 0},
        {"text": "Maxfiy bot token va sozlamalarni saqlash uchun odatda nima ishlatiladi?",
         "choices": [".env fayl", "settings.py ichida ochiq", "README fayl", "urls.py"], "correct": 0},
        {"text": "Aiogram'ni Django ilova (app) sifatida integratsiya qilishning maqsadi nima?",
         "choices": ["Bot va veb-ilova kodini birgalikda tartibli boshqarish", "Faqat tezlik uchun", "Xavfsizlikni pasaytirish uchun", "Hech qanday sabab"], "correct": 0},
        {"text": "ngrok test muhitida ishlatilishining sababi nima?",
         "choices": ["Lokal serverga vaqtinchalik HTTPS manzil berish", "Bazani tezlashtirish", "Statik fayllarni siqish", "Emailga xabar yuborish"], "correct": 0},
    ],
    "(Django) Telegram Bot — 3-qism (Django ORM bilan to'liq bot)": [
        {"text": "Bot orqali Django modeliga ma'lumot qo'shish uchun nima ishlatiladi?",
         "choices": ["Django ORM (Model.objects.create() kabi)", "Faqat SQL yozish", "Faqat admin panel", "Bu imkonsiz"], "correct": 0},
        {"text": "Sinxron Django ORM'ni asinxron (aiogram) kontekstda ishlatish uchun qaysi vosita ishlatiladi?",
         "choices": ["sync_to_async", "async_to_sync faqat", "await_orm", "orm_async"], "correct": 0},
        {"text": "Bot bilan ko'p bosqichli suhbat (masalan ro'yxatdan o'tish) qanday mexanizm bilan boshqariladi?",
         "choices": ["FSM (Finite State Machine)", "Simple if/else faqat", "Faqat webhook", "Faqat handler"], "correct": 0},
        {"text": "FSM nimani anglatadi?",
         "choices": ["Finite State Machine (chekli holatlar mashinasi)", "Fast State Manager", "Full Session Mode", "Function State Method"], "correct": 0},
        {"text": "Foydalanuvchi bot orqali kiritgan ma'lumotlar odatda qayerga saqlanadi?",
         "choices": ["Django modeliga bog'langan bazaga", "Faqat vaqtinchalik xotiraga", "Faqat log fayliga", "Hech qayerga saqlanmaydi"], "correct": 0},
        {"text": "Admin panel orqali bot ma'lumotlarini boshqarish imkoniyati qanday ta'minlanadi?",
         "choices": ["Bot modellari admin.site.register() orqali ro'yxatdan o'tkaziladi", "Alohida bot admin paneli yoziladi", "Bu imkonsiz", "Faqat CLI orqali"], "correct": 0},
        {"text": "FSM holatlari odatda qaysi klass yordamida e'lon qilinadi (Aiogram'da)?",
         "choices": ["StatesGroup", "StateMachine", "FlowManager", "StepController"], "correct": 0},
        {"text": "Loyihani yakunlab GitHub'ga yuklashda nima qo'shish tavsiya etiladi?",
         "choices": ["README hujjati", "Faqat kod, hech qanday hujjatsiz", "Faqat rasm", "Faqat video"], "correct": 0},
        {"text": "sync_to_async ishlatilmasa, asinxron botda Django ORM chaqirilganda nima yuz berishi mumkin?",
         "choices": ["Event loop bloklanishi yoki xatolik yuzaga kelishi", "Hech qanday muammo", "Avtomatik tezlashadi", "Bot tezroq ishlaydi"], "correct": 0},
        {"text": "To'liq funksional bot loyihasida odatda nechta asosiy qism birlashtiriladi?",
         "choices": ["Bot handler'lari, Django ORM va FSM holatlari", "Faqat bitta funksiya", "Faqat frontend", "Faqat baza"], "correct": 0},
    ],
}

FINAL = {
    "quiz_title": "Yakuniy test: Django, HTML, Jinja, REST Framework va Telegram Bot",
    "time_limit_seconds": 4500,
    "question_count": 50,
    "questions": [
        {"text": "Django qaysi arxitektura naqshiga asoslangan?", "choices": ["MVT", "MVVM", "Klassik MVC", "Ikkitalik model"], "correct": 0},
        {"text": "Lokal serverni ishga tushirish buyrug'i?", "choices": ["python manage.py runserver", "python manage.py start", "django run", "python runserver.py"], "correct": 0},
        {"text": "O'rnatilgan ilovalar ro'yxati qaysi sozlamada?", "choices": ["INSTALLED_APPS", "APPS_LIST", "DJANGO_APPS", "APP_REGISTRY"], "correct": 0},
        {"text": "Yangi app yaratish buyrug'i?", "choices": ["startapp", "newapp", "createapp", "initapp"], "correct": 0},
        {"text": "Migratsiyalarni bazaga qo'llash buyrug'i?", "choices": ["migrate", "makemigrations", "apply", "sync"], "correct": 0},
        {"text": "URL'ni View'ga bog'lash funksiyasi?", "choices": ["path()", "route()", "link()", "map()"], "correct": 0},
        {"text": "App urls.py'ni loyihaga ulash funksiyasi?", "choices": ["include()", "connect()", "link_app()", "attach()"], "correct": 0},
        {"text": "Model bazaviy klassi?", "choices": ["models.Model", "models.Base", "django.Model", "BaseModel"], "correct": 0},
        {"text": "Cheklangan uzunlikdagi matn maydoni?", "choices": ["CharField", "TextField", "IntegerField", "BooleanField"], "correct": 0},
        {"text": "Ko'p-birga munosabat uchun field?", "choices": ["ForeignKey", "OneToOneField", "ManyToManyField", "CharField"], "correct": 0},
        {"text": "Bog'liq obyekt o'chirilganda shu yozuv ham o'chishi uchun parametr?", "choices": ["on_delete=CASCADE", "on_delete=PROTECT", "on_delete=SET_NULL", "on_delete=DO_NOTHING"], "correct": 0},
        {"text": "Barcha yozuvlarni olish metodi?", "choices": ["all()", "get()", "select()", "list()"], "correct": 0},
        {"text": "Shartga mos yozuvlarni olish metodi?", "choices": ["filter()", "where()", "select()", "match()"], "correct": 0},
        {"text": "Shablon fayllari odatda qaysi papkada?", "choices": ["templates/", "views/", "static/", "models/"], "correct": 0},
        {"text": "View'dan shablonga javob qaytarish funksiyasi?", "choices": ["render()", "response()", "template()", "return_html()"], "correct": 0},
        {"text": "DTL nimani anglatadi?", "choices": ["Django Template Language", "Data Type Library", "Django Test Layer", "Dynamic Text Loader"], "correct": 0},
        {"text": "Shablonda o'zgaruvchi chiqarish belgisi?", "choices": ["{{ }}", "{% %}", "{# #}", "[[ ]]"], "correct": 0},
        {"text": "Shablon merosxo'rligi uchun teg?", "choices": ["{% extends %}", "{% inherit %}", "{% include_base %}", "{% parent %}"], "correct": 0},
        {"text": "Boshqa shablonni qo'shish uchun teg?", "choices": ["{% include %}", "{% import %}", "{% embed %}", "{% insert %}"], "correct": 0},
        {"text": "Jinja Django'da qanday ishlatiladi?", "choices": ["DTL o'rniga muqobil dvigatel sifatida", "CSS uchun", "JS uchun", "Hech qachon"], "correct": 0},
        {"text": "Klass selektori qaysi belgi bilan?", "choices": [".", "#", "@", "&"], "correct": 0},
        {"text": "Statik fayllar uchun bazaviy URL sozlamasi?", "choices": ["STATIC_URL", "MEDIA_URL", "BASE_URL", "ASSETS_URL"], "correct": 0},
        {"text": "Statik fayldan foydalanish uchun avval nima qilinadi?", "choices": ["{% load static %}", "Hech narsa", "settings o'zgartiriladi", "urls o'zgartiriladi"], "correct": 0},
        {"text": "Modelni admin panelda ro'yxatdan o'tkazish funksiyasi?", "choices": ["admin.site.register()", "admin.add_model()", "admin.model_register()", "register_model()"], "correct": 0},
        {"text": "Admin ro'yxatida ko'rsatiladigan ustunlar atributi?", "choices": ["list_display", "list_columns", "display_fields", "show_fields"], "correct": 0},
        {"text": "Django Form bazaviy klassi?", "choices": ["forms.Form", "forms.Base", "django.Form", "models.Form"], "correct": 0},
        {"text": "CSRF himoyasi uchun forma tegi?", "choices": ["{% csrf_token %}", "{% security_token %}", "{% auth_token %}", "{% form_token %}"], "correct": 0},
        {"text": "Model asosida avtomatik forma yaratuvchi klass?", "choices": ["ModelForm", "AutoForm", "QuickForm", "DataForm"], "correct": 0},
        {"text": "Bazaviy Class-Based View klassi?", "choices": ["View", "Model", "Form", "Template"], "correct": 0},
        {"text": "Ro'yxat ko'rsatuvchi CBV?", "choices": ["ListView", "DetailView", "CreateView", "TemplateView"], "correct": 0},
        {"text": "Yangi obyekt yaratuvchi CBV?", "choices": ["CreateView", "UpdateView", "DeleteView", "ListView"], "correct": 0},
        {"text": "Faqat kirgan foydalanuvchi uchun mixin?", "choices": ["LoginRequiredMixin", "PermissionRequiredMixin", "UserMixin", "AuthMixin"], "correct": 0},
        {"text": "Django autentifikatsiya ilovasi?", "choices": ["django.contrib.auth", "django.contrib.sessions", "django.contrib.admin", "django.auth_system"], "correct": 0},
        {"text": "Ro'yxatdan o'tish uchun tayyor forma?", "choices": ["UserCreationForm", "UserRegisterForm", "SignupForm", "AccountForm"], "correct": 0},
        {"text": "Custom User Model uchun moslashuvchan bazaviy klass?", "choices": ["AbstractBaseUser", "AbstractUser", "User", "BaseModel"], "correct": 0},
        {"text": "Media fayllar uchun URL sozlamasi?", "choices": ["MEDIA_URL", "STATIC_URL", "FILE_URL", "UPLOAD_URL"], "correct": 0},
        {"text": "Rasm yuklash uchun model maydoni?", "choices": ["ImageField", "FileField", "CharField", "URLField"], "correct": 0},
        {"text": "Natijalarni sahifalash klassi?", "choices": ["Paginator", "PageSplitter", "ListDivider", "ChunkMaker"], "correct": 0},
        {"text": "Murakkab OR/AND so'rov uchun obyekt?", "choices": ["Q obyektlari", "F obyektlari", "Search obyekti", "Filter obyekti"], "correct": 0},
        {"text": "N+1 muammosini oldini oluvchi metod (ForeignKey uchun)?", "choices": ["select_related()", "prefetch_only()", "join()", "eager()"], "correct": 0},
        {"text": "Email yuborish funksiyasi?", "choices": ["send_mail()", "mail_send()", "email_send()", "post_mail()"], "correct": 0},
        {"text": "REST API'da ma'lumot olish HTTP metodi?", "choices": ["GET", "POST", "DELETE", "PUT"], "correct": 0},
        {"text": "Yangi resurs yaratilganda status kodi?", "choices": ["201", "200", "204", "202"], "correct": 0},
        {"text": "DRF nimani anglatadi?", "choices": ["Django REST Framework", "Django Response Format", "Direct Request Filter", "Data Rest Function"], "correct": 0},
        {"text": "Model asosida serializer yaratuvchi klass?", "choices": ["ModelSerializer", "AutoSerializer", "BaseSerializer", "QuickSerializer"], "correct": 0},
        {"text": "CRUD'ni bitta klassda birlashtiruvchi DRF tuzilmasi?", "choices": ["ModelViewSet", "APIView", "GenericView", "MixinView"], "correct": 0},
        {"text": "ViewSet uchun URL avtomatlashtiruvchi vosita?", "choices": ["Router", "Path builder", "URL factory", "AutoMapper"], "correct": 0},
        {"text": "DRF'da faqat autentifikatsiyalanganlarga ruxsat beruvchi klass?", "choices": ["IsAuthenticated", "AllowAny", "IsAdminUser", "DenyAll"], "correct": 0},
        {"text": "Telegram bot yaratish uchun avval kim bilan gaplashiladi?", "choices": ["BotFather", "Telegram Support", "Admin", "API Gateway"], "correct": 0},
        {"text": "Bot server tomonidan doimiy so'rov yuborish rejimi?", "choices": ["Polling", "Webhook", "Streaming", "Pushing"], "correct": 0},
    ],
}
