"""Python dasturlash tili bo'limi uchun mavzu testlari (10 savoldan) va yakuniy test (50 savol)."""

MODULE_TITLE = "Python dasturlash tili va algoritmlari"

QUESTIONS: dict[str, list[dict]] = {
    "(Python) Python bilan tanishuv": [
        {"text": "Python interpretatsiya qilinadigan (interpreted) til sifatida qanday ishlaydi?",
         "choices": ["Kodni satrma-satr bajaradi", "Faqat compile qiladi, bajarmaydi", "Faqat brauzerda ishlaydi", "Faqat mashina kodiga o'giradi va saqlaydi"], "correct": 0},
        {"text": "Ekranga matn chiqarish uchun qaysi funksiya ishlatiladi?",
         "choices": ["print()", "echo()", "output()", "write()"], "correct": 0},
        {"text": "Foydalanuvchidan klaviaturadan ma'lumot olish uchun qaysi funksiya ishlatiladi?",
         "choices": ["input()", "read()", "get()", "scan()"], "correct": 0},
        {"text": "Python kod yozish uslubi standarti qanday ataladi?",
         "choices": ["PEP8", "HTML5", "ES6", "JSON Schema"], "correct": 0},
        {"text": "Python uchun mashhur IDE'lardan biri qaysi?",
         "choices": ["PyCharm", "Photoshop", "AutoCAD", "Premiere"], "correct": 0},
        {"text": "\"Compiled\" va \"interpreted\" tillar orasidagi asosiy farq nima?",
         "choices": ["Compiled til avval mashina kodiga o'giradi, interpreted esa bajarish paytida o'qiydi", "Farqi yo'q", "Interpreted til tezroq har doim", "Compiled til brauzerda ishlaydi"], "correct": 0},
        {"text": "Python qaysi turdagi dasturlash tili?",
         "choices": ["Yuqori darajali, umumiy maqsadli til", "Faqat markup til", "Faqat query til", "Faqat stil tili"], "correct": 0},
        {"text": "Birinchi Python dasturi odatda nimani chop etadi?",
         "choices": ["\"Hello, World!\"", "Faqat sonlar", "Bo'sh natija", "Xatolik"], "correct": 0},
        {"text": "Python qaysi sohalarda keng qo'llaniladi?",
         "choices": ["Web, ma'lumotlar tahlili, sun'iy intellekt va boshqalar", "Faqat o'yin dizayni", "Faqat video montaj", "Faqat 3D modellashtirish"], "correct": 0},
        {"text": "Virtual muhit (venv) nima uchun ishlatiladi?",
         "choices": ["Loyiha uchun alohida, izolyatsiyalangan kutubxona muhiti yaratish", "Kodni tezlashtirish", "Internetga ulanish", "Fayllarni siqish"], "correct": 0},
    ],
    "(Python) Sintaksis, o'zgaruvchilar va kommentariyalar": [
        {"text": "O'zgaruvchi nomini e'lon qilishda Python'da qaysi kalit so'z talab qilinadi?",
         "choices": ["Hech qanday, to'g'ridan-to'g'ri nom = qiymat", "var", "let", "dim"], "correct": 0},
        {"text": "O'zgarmas qiymatlar (constants) odatda qanday nomlanadi?",
         "choices": ["UPPER_CASE", "lowerCase", "camelCase", "PascalCase"], "correct": 0},
        {"text": "Bir qatorli izoh (comment) qaysi belgi bilan boshlanadi?",
         "choices": ["#", "//", "--", "/*"], "correct": 0},
        {"text": "Funksiya yoki modul hujjatlash uchun ishlatiladigan ko'p qatorli matn qanday ataladi?",
         "choices": ["Docstring", "Comment block", "Header", "Tag"], "correct": 0},
        {"text": "Matnni butun songa aylantirish uchun qaysi funksiya ishlatiladi?",
         "choices": ["int()", "str()", "float()", "bool()"], "correct": 0},
        {"text": "Qiymatni matnga (string) aylantirish uchun qaysi funksiya ishlatiladi?",
         "choices": ["str()", "int()", "list()", "dict()"], "correct": 0},
        {"text": "O'zgaruvchining tipini aniqlash uchun qaysi funksiya ishlatiladi?",
         "choices": ["type()", "kind()", "class()", "typeof()"], "correct": 0},
        {"text": "Obyekt ma'lum klassga tegishli ekanligini tekshirish uchun qaysi funksiya ishlatiladi?",
         "choices": ["isinstance()", "type_of()", "class_check()", "is_type()"], "correct": 0},
        {"text": "Python'da o'zgaruvchi nomi nima bilan boshlanishi MUMKIN EMAS?",
         "choices": ["Raqam bilan", "Harf bilan", "Pastki chiziq (_) bilan", "Kichik harf bilan"], "correct": 0},
        {"text": "Python o'zgaruvchi tipini qachon aniqlaydi?",
         "choices": ["Dinamik ravishda, ishga tushirish (runtime) paytida", "Faqat compile paytida", "Hech qachon aniqlamaydi", "Faqat dastur boshida bir marta"], "correct": 0},
    ],
    "(Python) Stringlar va formatlash": [
        {"text": "String'dagi belgilarga indeks orqali murojaat qilishda birinchi belgi indeksi nechaga teng?",
         "choices": ["0", "1", "-1", "None"], "correct": 0},
        {"text": "String'ning bir qismini olish uchun qaysi texnika ishlatiladi?",
         "choices": ["Slicing ([start:stop:step])", "Splitting only", "Joining only", "Mapping"], "correct": 0},
        {"text": "String ichiga o'zgaruvchi qiymatini qulay kiritish uchun zamonaviy usul qaysi?",
         "choices": ["F-strings", "Concatenation only", "Only %s", "join() only"], "correct": 0},
        {"text": "String'ni bosh harflardan kichik harfga o'tkazuvchi metod qaysi?",
         "choices": ["lower()", "upper()", "strip()", "title()"], "correct": 0},
        {"text": "String boshidagi va oxiridagi bo'sh joylarni olib tashlovchi metod qaysi?",
         "choices": ["strip()", "trim_all()", "clean()", "cut()"], "correct": 0},
        {"text": "String'ni ma'lum belgi bo'yicha bo'laklarga ajratuvchi metod qaysi?",
         "choices": ["split()", "join()", "slice()", "divide()"], "correct": 0},
        {"text": "Ro'yxat elementlarini bitta string'ga birlashtirish uchun qaysi metod ishlatiladi?",
         "choices": ["join()", "split()", "merge()", "concat()"], "correct": 0},
        {"text": "String ichida ma'lum qism-satrni izlash uchun qaysi metod ishlatiladi?",
         "choices": ["find()", "search()", "index_of()", "locate()"], "correct": 0},
        {"text": "Escape belgilaridan qochish uchun ishlatiladigan raw string qanday belgilanadi?",
         "choices": ['r"..."', 'e"..."', 'raw"..."', '\\"..."'], "correct": 0},
        {"text": "String'da qism-matnni boshqasiga almashtirish uchun qaysi metod ishlatiladi?",
         "choices": ["replace()", "swap()", "change()", "update()"], "correct": 0},
    ],
    "(Python) Sonlar va operatorlar": [
        {"text": "Python'da butun son tipi qanday ataladi?",
         "choices": ["int", "float", "complex", "number"], "correct": 0},
        {"text": "Bo'linmadan qolgan qoldiqni hisoblovchi operator qaysi?",
         "choices": ["%", "//", "**", "/"], "correct": 0},
        {"text": "Butun qismli bo'lish (floor division) operatori qaysi?",
         "choices": ["//", "/", "%", "**"], "correct": 0},
        {"text": "Darajaga ko'tarish operatori qaysi?",
         "choices": ["**", "^", "%%", "^^"], "correct": 0},
        {"text": "\"Teng\" ekanligini tekshiruvchi solishtirish operatori qaysi?",
         "choices": ["==", "=", "===", "eq"], "correct": 0},
        {"text": "Mantiqiy VA (AND) operatori Python'da qanday yoziladi?",
         "choices": ["and", "&&", "AND", "&"], "correct": 0},
        {"text": "Bo'sh string, 0, None qiymatlari mantiqiy kontekstda qanday baholanadi?",
         "choices": ["Falsy", "Har doim Truthy", "Xatolik beradi", "Aniqlanmaydi"], "correct": 0},
        {"text": "Mantiqiy inkor (NOT) operatori qaysi?",
         "choices": ["not", "!", "NOT()", "~"], "correct": 0},
        {"text": "complex son tipi nimani ifodalaydi?",
         "choices": ["Kompleks (haqiqiy + mavhum qism) sonlarni", "Faqat manfiy sonlarni", "Faqat katta sonlarni", "Matnli sonlarni"], "correct": 0},
        {"text": "5 == 5.0 ifodasi Python'da nima natija beradi?",
         "choices": ["True", "False", "Xatolik", "None"], "correct": 0},
    ],
    "(Python) Shartli operatorlar va Control Flow": [
        {"text": "Asosiy shart operatorlari qaysi uchtasi?",
         "choices": ["if, elif, else", "if, then, end", "case, switch, default", "when, then, otherwise"], "correct": 0},
        {"text": "Shart ichida yana bir shart bo'lishi qanday ataladi?",
         "choices": ["Nested if (ichma-ich shart)", "Double if", "Loop if", "Chained if"], "correct": 0},
        {"text": "Qisqa shartli ifoda (bitta qatorda) qanday ataladi?",
         "choices": ["Ternary operator (a if cond else b)", "Lambda", "Generator", "Decorator"], "correct": 0},
        {"text": "match-case konstruksiyasi Python'ning qaysi versiyasidan boshlab qo'shilgan?",
         "choices": ["3.10", "2.7", "3.0", "3.5"], "correct": 0},
        {"text": "elif nimani anglatadi?",
         "choices": ["else if — qo'shimcha shart tekshirish", "Faqat else", "Faqat if", "Loop turi"], "correct": 0},
        {"text": "if shartida bo'sh ro'yxat ([]) qanday baholanadi?",
         "choices": ["Falsy (False sifatida)", "Truthy (True sifatida)", "Xatolik beradi", "None"], "correct": 0},
        {"text": "match-case konstruksiyasi qaysi tilning switch-case'iga o'xshaydi?",
         "choices": ["Ko'plab boshqa tillardagi switch-case'ga", "Faqat HTML'ga", "Faqat SQL'ga", "Hech qaysiga"], "correct": 0},
        {"text": "Ternary operatorning umumiy sintaksisi qanday?",
         "choices": ["natija_agar_true if shart else natija_agar_false", "if shart then natija else natija2 end", "shart ? natija1 : natija2", "case shart: natija"], "correct": 0},
        {"text": "Bir nechta elif zanjiri qachon foydali?",
         "choices": ["Bir nechta o'zaro istisno shartlarni tekshirishda", "Faqat bitta shart bo'lganda", "Hech qachon", "Faqat sikllar ichida"], "correct": 0},
        {"text": "if bloki ichidagi kod qanday ajratiladi?",
         "choices": ["Chekinish (indentation) bilan", "Qavslar bilan {}", "Nuqtali vergul bilan", "Teglar bilan"], "correct": 0},
    ],
    "(Python) while sikli": [
        {"text": "while sikli qachon ishlashni to'xtatadi?",
         "choices": ["Shart False bo'lganda", "Har doim 10 marta ishlaydi", "Hech qachon to'xtamaydi", "Faqat break bilan"], "correct": 0},
        {"text": "Sikldan to'liq chiqish uchun qaysi operator ishlatiladi?",
         "choices": ["break", "continue", "pass", "stop"], "correct": 0},
        {"text": "Joriy iteratsiyani o'tkazib, keyingisiga o'tish uchun qaysi operator ishlatiladi?",
         "choices": ["continue", "break", "pass", "skip"], "correct": 0},
        {"text": "Hech narsa bajarmaydigan, faqat joy egallovchi operator qaysi?",
         "choices": ["pass", "break", "continue", "None"], "correct": 0},
        {"text": "Shart hech qachon False bo'lmasa nima yuz beradi?",
         "choices": ["Cheksiz sikl (infinite loop)", "Dastur avtomatik to'xtaydi", "Xatolik chiqadi darhol", "Sikl ishlamaydi"], "correct": 0},
        {"text": "while-else konstruksiyasida else qismi qachon bajariladi?",
         "choices": ["Sikl break qilinmasdan normal tugaganda", "Har doim", "Faqat break bo'lganda", "Hech qachon"], "correct": 0},
        {"text": "while sikli qaysi holatda for sikliga qaraganda qulayroq?",
         "choices": ["Iteratsiyalar soni oldindan noma'lum bo'lganda", "Ro'yxat ustida yurishda", "Hech qachon", "Faqat matnda"], "correct": 0},
        {"text": "Cheksiz sikldan foydalanuvchi kiritgan buyruq orqali chiqish uchun odatda nima qilinadi?",
         "choices": ["Shart ichida break qo'shish", "Hech narsa qilmaslik", "Faqat continue ishlatish", "Sikl ichida yangi sikl yaratish"], "correct": 0},
        {"text": "while True: konstruksiyasi nimani anglatadi?",
         "choices": ["Shart doim rost bo'lgani uchun cheksiz sikl", "Faqat bir marta ishlaydigan sikl", "Sikl umuman ishlamaydi", "Xatolik"], "correct": 0},
        {"text": "while sikli tanasi qanday ajratiladi?",
         "choices": ["Chekinish (indentation)", "Qavslar {}", "begin/end so'zlari", "Teglar"], "correct": 0},
    ],
    "(Python) for sikli va range()": [
        {"text": "range(5) funksiyasi qanday sonlar ketma-ketligini beradi?",
         "choices": ["0, 1, 2, 3, 4", "1, 2, 3, 4, 5", "0, 1, 2, 3, 4, 5", "5, 4, 3, 2, 1"], "correct": 0},
        {"text": "range() funksiyasida uchinchi argument nimani bildiradi?",
         "choices": ["Qadam (step)", "Boshlanish nuqtasi", "Tugash nuqtasi", "Umumiy son"], "correct": 0},
        {"text": "Ustidan iteratsiya qilish mumkin bo'lgan obyektlar (list, string, range) umumiy nom bilan qanday ataladi?",
         "choices": ["Iterables", "Constants", "Functions", "Modules"], "correct": 0},
        {"text": "for sikli ichida yana bir for sikli bo'lishi qanday ataladi?",
         "choices": ["Nested loop (ichma-ich sikl)", "Double for", "Chain loop", "Recursive loop"], "correct": 0},
        {"text": "for x in [1,2,3]: konstruksiyasida x nimani anglatadi?",
         "choices": ["Ro'yxatning har bir elementi navbat bilan", "Ro'yxat uzunligi", "Ro'yxat indeksi doim 0", "Doimiy o'zgarmas qiymat"], "correct": 0},
        {"text": "range(2, 10, 2) natijasida qaysi sonlar hosil bo'ladi?",
         "choices": ["2, 4, 6, 8", "2, 3, 4, ..., 9", "2, 10", "0, 2, 4, 6, 8"], "correct": 0},
        {"text": "for sikli va range() birgalikda ko'pincha qanday maqsadda ishlatiladi?",
         "choices": ["Ma'lum marta takrorlash yoki indeks bo'yicha yurish", "Faqat matn chiqarish uchun", "Faqat fayl ochish uchun", "Faqat xatolik ushlash uchun"], "correct": 0},
        {"text": "Naqsh (masalan uchburchak) chizishda odatda qaysi sikl turi ishlatiladi?",
         "choices": ["Ichma-ich for sikllari", "Faqat if operatori", "Faqat while sikli", "Faqat print()"], "correct": 0},
        {"text": "for sikli list, tuple, string, dict kabi obyektlar bilan ishlay oladimi?",
         "choices": ["Ha, ular iterable bo'lgani uchun", "Yo'q, faqat list bilan", "Yo'q, faqat string bilan", "Faqat dict bilan"], "correct": 0},
        {"text": "range() funksiyasi natijada qanday obyekt qaytaradi?",
         "choices": ["range obyekti (lazy ketma-ketlik)", "To'liq list", "String", "Dictionary"], "correct": 0},
    ],
    "(Python) Ro'yxatlar (List) — 1-qism": [
        {"text": "Ro'yxatga oxiriga bitta element qo'shish uchun qaysi metod ishlatiladi?",
         "choices": ["append()", "add()", "insert_end()", "push()"], "correct": 0},
        {"text": "Ro'yxatning ma'lum indeksiga element qo'shish uchun qaysi metod ishlatiladi?",
         "choices": ["insert()", "append()", "add_at()", "put()"], "correct": 0},
        {"text": "Bir ro'yxatni boshqa ro'yxat elementlari bilan kengaytirish uchun qaysi metod ishlatiladi?",
         "choices": ["extend()", "append()", "merge()", "add_all()"], "correct": 0},
        {"text": "Ro'yxatdan ma'lum qiymatni (birinchi uchraganini) o'chirish uchun qaysi metod ishlatiladi?",
         "choices": ["remove()", "delete()", "pop_value()", "discard()"], "correct": 0},
        {"text": "Ro'yxatdan indeks bo'yicha element olib tashlab, uni qaytaruvchi metod qaysi?",
         "choices": ["pop()", "remove()", "delete()", "cut()"], "correct": 0},
        {"text": "Ro'yxat uzunligini olish uchun qaysi funksiya ishlatiladi?",
         "choices": ["len()", "size()", "count_all()", "length()"], "correct": 0},
        {"text": "Ro'yxatdagi eng katta qiymatni topish uchun qaysi funksiya ishlatiladi?",
         "choices": ["max()", "top()", "biggest()", "highest()"], "correct": 0},
        {"text": "Ro'yxatdagi barcha sonlar yig'indisini olish uchun qaysi funksiya ishlatiladi?",
         "choices": ["sum()", "total()", "add_all()", "plus()"], "correct": 0},
        {"text": "del kalit so'zi ro'yxat elementiga nisbatan nima qiladi?",
         "choices": ["Ko'rsatilgan indeksdagi elementni o'chiradi", "Ro'yxatni nusxalaydi", "Yangi ro'yxat yaratadi", "Ro'yxatni saralaydi"], "correct": 0},
        {"text": "Ro'yxat elementini indeks orqali o'zgartirish mumkinmi?",
         "choices": ["Ha, list mutable (o'zgaruvchan)", "Yo'q, list immutable", "Faqat birinchi elementni", "Faqat oxirgi elementni"], "correct": 0},
    ],
    "(Python) Ro'yxatlar (List) — 2-qism": [
        {"text": "Ro'yxatni o'zining ichida (joyida) saralovchi metod qaysi?",
         "choices": ["sort()", "sorted()", "order()", "arrange()"], "correct": 0},
        {"text": "Yangi saralangan ro'yxat qaytaruvchi (original o'zgarmaydigan) funksiya qaysi?",
         "choices": ["sorted()", "sort()", "order_by()", "arrange()"], "correct": 0},
        {"text": "Ro'yxat elementlari tartibini teskarisiga o'giruvchi metod qaysi?",
         "choices": ["reverse()", "invert()", "flip()", "backward()"], "correct": 0},
        {"text": "Ro'yxatni qisqa va o'qilishi oson usulda yaratish texnikasi qanday ataladi?",
         "choices": ["List comprehension", "List builder", "List factory", "List generator only"], "correct": 0},
        {"text": "Har bir elementga funksiya qo'llab, yangi iterator qaytaruvchi funksiya qaysi?",
         "choices": ["map()", "filter()", "reduce()", "apply()"], "correct": 0},
        {"text": "Shartga mos elementlarni tanlab olish uchun qaysi funksiya ishlatiladi?",
         "choices": ["filter()", "map()", "select()", "choose()"], "correct": 0},
        {"text": "Barcha elementlarni bitta qiymatga qisqartiruvchi funksiya qaysi?",
         "choices": ["reduce()", "map()", "filter()", "sum_all()"], "correct": 0},
        {"text": "reduce() funksiyasi qaysi modulda joylashgan?",
         "choices": ["functools", "itertools", "collections", "builtins faqat"], "correct": 0},
        {"text": "Ro'yxatdagi ma'lum qiymatning indeksini topish uchun qaysi metod ishlatiladi?",
         "choices": ["index()", "find()", "search()", "locate()"], "correct": 0},
        {"text": "Shartli list comprehension odatiy sintaksisi qaysi?",
         "choices": ["[x for x in list if shart]", "[x if shart for x in list]", "for x in list: if shart: x", "list(x for shart in x)"], "correct": 0},
    ],
    "(Python) Tuple va unpacking": [
        {"text": "Tuple'ning asosiy xususiyati nima?",
         "choices": ["Immutable (o'zgarmas)", "Mutable (o'zgaruvchan)", "Faqat sonlar saqlaydi", "Tartibsiz"], "correct": 0},
        {"text": "Tuple qanday qavslar bilan yaratiladi (odatda)?",
         "choices": ["( )", "[ ]", "{ }", "< >"], "correct": 0},
        {"text": "a, b = (1, 2) ifodasi qanday ataladi?",
         "choices": ["Tuple unpacking", "Tuple packing only", "List comprehension", "Dictionary merge"], "correct": 0},
        {"text": "a, *rest = [1,2,3,4] ifodasida rest nimaga teng bo'ladi?",
         "choices": ["[2, 3, 4]", "[1]", "[1, 2, 3, 4]", "4"], "correct": 0},
        {"text": "Tuple ichida ma'lum qiymat necha marta uchrashini sanovchi metod qaysi?",
         "choices": ["count()", "find()", "sum()", "len()"], "correct": 0},
        {"text": "Tuple ichida qiymat indeksini topuvchi metod qaysi?",
         "choices": ["index()", "find()", "search()", "locate()"], "correct": 0},
        {"text": "Tuple va List o'rtasidagi asosiy farq nima?",
         "choices": ["Tuple o'zgarmas, List o'zgaruvchan", "Farqi yo'q", "Tuple faqat sonlar uchun", "List har doim tezroq"], "correct": 0},
        {"text": "Tezlik va xotira jihatidan qachon Tuple List'dan afzal?",
         "choices": ["Ma'lumot o'zgarmasligi kerak bo'lganda", "Har doim ro'yxat o'rniga", "Hech qachon", "Faqat matn saqlashda"], "correct": 0},
        {"text": "Bitta elementli tuple qanday yaratiladi?",
         "choices": ["(5,) — vergul bilan", "(5) — vergulsiz", "[5]", "{5}"], "correct": 0},
        {"text": "Tuple'lar dictionary'da kalit (key) sifatida ishlatilishi mumkinmi?",
         "choices": ["Ha, chunki immutable", "Yo'q, hech qachon", "Faqat bo'sh tuple", "Faqat bitta elementli"], "correct": 0},
    ],
    "(Python) Set (To'plamlar)": [
        {"text": "Set'ning asosiy xususiyati nima?",
         "choices": ["Faqat noyob (unique) elementlar saqlaydi", "Tartiblangan va dublikat saqlaydi", "Indeks orqali murojaat qilinadi", "O'zgarmas (immutable)"], "correct": 0},
        {"text": "Set'ga element qo'shish uchun qaysi metod ishlatiladi?",
         "choices": ["add()", "append()", "insert()", "push()"], "correct": 0},
        {"text": "Set'dan elementni xatosiz (mavjud bo'lmasa ham) olib tashlash uchun qaysi metod ishlatiladi?",
         "choices": ["discard()", "remove()", "pop_safe()", "delete()"], "correct": 0},
        {"text": "Ikki set'ning birlashmasini olish uchun qaysi amal/metod ishlatiladi?",
         "choices": ["union()", "intersection()", "difference()", "symmetric()"], "correct": 0},
        {"text": "Ikki set'ga umumiy elementlarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["intersection()", "union()", "difference()", "update()"], "correct": 0},
        {"text": "Bitta set'da bor, ikkinchisida yo'q elementlarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["difference()", "union()", "intersection()", "add()"], "correct": 0},
        {"text": "Faqat ikkala set'da bitta-bittadan uchraydigan (umumiy bo'lmagan) elementlarni olish uchun qaysi metod ishlatiladi?",
         "choices": ["symmetric_difference()", "union()", "intersection()", "difference()"], "correct": 0},
        {"text": "Ikki set'ning kesishmasi bo'sh bo'lsa, ular qanday ataladi?",
         "choices": ["Disjoint sets", "Subset", "Superset", "Union sets"], "correct": 0},
        {"text": "O'zgarmas (immutable) set turi qanday ataladi?",
         "choices": ["frozenset", "constset", "fixedset", "readonlyset"], "correct": 0},
        {"text": "Set comprehension qanday belgilar bilan yoziladi?",
         "choices": ["{x for x in ...}", "[x for x in ...]", "(x for x in ...)", "<x for x in ...>"], "correct": 0},
    ],
    "(Python) Dictionary (Lug'atlar)": [
        {"text": "Dictionary asosan qanday tuzilma?",
         "choices": ["Kalit-qiymat (key-value) juftlari", "Tartiblangan sonlar ketma-ketligi", "Noyob elementlar to'plami", "O'zgarmas ketma-ketlik"], "correct": 0},
        {"text": "Dictionary'ga kalit orqali qiymat olishda kalit mavjud bo'lmasa xatolik bermaydigan metod qaysi?",
         "choices": ["get()", "fetch()", "find()", "retrieve()"], "correct": 0},
        {"text": "Dictionary'dagi barcha kalitlarni qaytaruvchi metod qaysi?",
         "choices": ["keys()", "values()", "items()", "all()"], "correct": 0},
        {"text": "Dictionary'dagi barcha (kalit, qiymat) juftliklarini qaytaruvchi metod qaysi?",
         "choices": ["items()", "keys()", "values()", "pairs()"], "correct": 0},
        {"text": "Dictionary'ni boshqa dictionary bilan yangilash/birlashtirish uchun qaysi metod ishlatiladi?",
         "choices": ["update()", "merge()", "add()", "combine()"], "correct": 0},
        {"text": "Dictionary'dan kalitni o'chirib, qiymatini qaytaruvchi metod qaysi?",
         "choices": ["pop()", "remove()", "delete()", "discard()"], "correct": 0},
        {"text": "Kalit mavjud bo'lmasa uni standart qiymat bilan qo'shuvchi metod qaysi?",
         "choices": ["setdefault()", "get_or_set()", "default()", "init_key()"], "correct": 0},
        {"text": "Dictionary ichida yana dictionary bo'lishi qanday ataladi?",
         "choices": ["Nested dictionary (ichma-ich)", "Double dict", "Chained dict", "Multi dict"], "correct": 0},
        {"text": "Dictionary comprehension qanday belgilar bilan yoziladi?",
         "choices": ["{k: v for k, v in ...}", "[k: v for ...]", "(k: v for ...)", "<k: v for ...>"], "correct": 0},
        {"text": "Dictionary'da kalitlar qanday bo'lishi shart?",
         "choices": ["Noyob (unique) va o'zgarmas (immutable) tip", "Faqat sonlar", "Faqat matnlar", "Har doim tartiblangan"], "correct": 0},
    ],
    "(Python) Funksiyalar — 1-qism": [
        {"text": "Funksiya e'lon qilish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["def", "function", "func", "define"], "correct": 0},
        {"text": "Funksiyadan qiymat qaytarish uchun qaysi operator ishlatiladi?",
         "choices": ["return", "give", "output", "yield only"], "correct": 0},
        {"text": "Funksiya chaqirilganda tartib bo'yicha uzatiladigan argumentlar qanday ataladi?",
         "choices": ["Positional arguments", "Keyword arguments", "Default arguments", "Global arguments"], "correct": 0},
        {"text": "Funksiya chaqirilganda nom orqali uzatiladigan argumentlar qanday ataladi?",
         "choices": ["Keyword arguments", "Positional arguments", "Free arguments", "Static arguments"], "correct": 0},
        {"text": "Parametrga oldindan qiymat berish uchun qanday sintaksis ishlatiladi?",
         "choices": ["def f(x=10):", "def f(x default 10):", "def f(x): default=10", "def f(x, 10):"], "correct": 0},
        {"text": "Funksiya vazifasini tushuntiruvchi hujjat matni qanday ataladi?",
         "choices": ["Docstring", "Comment", "Header", "Tag"], "correct": 0},
        {"text": "return operatori ishlamagan funksiya nima qaytaradi?",
         "choices": ["None", "0", "Bo'sh string", "Xatolik"], "correct": 0},
        {"text": "Funksiya nechta qiymat qaytarishi mumkin?",
         "choices": ["Bir nechta (tuple sifatida)", "Faqat bitta har doim", "Hech qanday", "Faqat 2 tagacha"], "correct": 0},
        {"text": "Funksiyaga standart qiymatli parametrni qayerga qo'yish kerak?",
         "choices": ["Positional parametrlardan keyin", "Har doim birinchi", "Muhim emas", "Faqat oxirgi bo'lmasligi kerak"], "correct": 0},
        {"text": "def get_sum(a, b): return a + b — bu funksiya nima qiladi?",
         "choices": ["Ikki sonni qo'shib qaytaradi", "Ikki sonni ko'paytiradi", "Ekranga chiqaradi, qaytarmaydi", "Xatolik beradi"], "correct": 0},
    ],
    "(Python) Funksiyalar — 2-qism": [
        {"text": "Noma'lum sondagi positional argumentlarni qabul qilish uchun qaysi sintaksis ishlatiladi?",
         "choices": ["*args", "**kwargs", "&args", "...args"], "correct": 0},
        {"text": "Noma'lum sondagi keyword argumentlarni qabul qilish uchun qaysi sintaksis ishlatiladi?",
         "choices": ["**kwargs", "*args", "&kwargs", "...kwargs"], "correct": 0},
        {"text": "Funksiya ichida e'lon qilingan o'zgaruvchi qaysi doiraga (scope) tegishli?",
         "choices": ["Local scope", "Global scope", "Universal scope", "Class scope"], "correct": 0},
        {"text": "Funksiya ichidan global o'zgaruvchini o'zgartirish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["global", "public", "extern", "outer"], "correct": 0},
        {"text": "Bitta qatorli, nomsiz funksiya qanday ataladi?",
         "choices": ["Lambda funksiya", "Mini funksiya", "Anon function only", "Micro function"], "correct": 0},
        {"text": "Lambda funksiya qanday sintaksis bilan yoziladi?",
         "choices": ["lambda x: x + 1", "def lambda(x): x+1", "func(x) => x+1", "lambda(x) { x+1 }"], "correct": 0},
        {"text": "*args funksiya ichida qanday tipda qabul qilinadi?",
         "choices": ["Tuple", "List", "Dictionary", "Set"], "correct": 0},
        {"text": "**kwargs funksiya ichida qanday tipda qabul qilinadi?",
         "choices": ["Dictionary", "Tuple", "List", "Set"], "correct": 0},
        {"text": "Lambda funksiyalar ko'pincha qaysi funksiyalar bilan birga ishlatiladi?",
         "choices": ["map(), filter(), sorted()", "print(), input()", "open(), close()", "import, export"], "correct": 0},
        {"text": "Global va local scope'da bir xil nomli o'zgaruvchi bo'lsa, funksiya ichida qaysi qiymat ustunlik qiladi?",
         "choices": ["Local qiymat", "Global qiymat", "Ikkalasi ham xatolik beradi", "Tasodifiy tanlanadi"], "correct": 0},
    ],
    "(Python) Exception handling": [
        {"text": "Xatolikni ushlab qolish uchun qaysi blok ishlatiladi?",
         "choices": ["try/except", "if/else", "for/while", "def/return"], "correct": 0},
        {"text": "Xatolik bo'lmasa ham har doim bajariladigan blok qaysi?",
         "choices": ["finally", "else", "except", "raise"], "correct": 0},
        {"text": "try blokida xatolik bo'lmasa bajariladigan (ixtiyoriy) blok qaysi?",
         "choices": ["else", "finally", "except", "pass"], "correct": 0},
        {"text": "Noto'g'ri tipdagi qiymat bilan amal bajarilganda odatda qaysi xatolik yuzaga keladi?",
         "choices": ["TypeError", "ValueError", "KeyError", "IndexError"], "correct": 0},
        {"text": "Nolga bo'lishda qaysi xatolik yuzaga keladi?",
         "choices": ["ZeroDivisionError", "ValueError", "TypeError", "OverflowError"], "correct": 0},
        {"text": "Ro'yxatda mavjud bo'lmagan indeksga murojaat qilganda qaysi xatolik yuzaga keladi?",
         "choices": ["IndexError", "KeyError", "TypeError", "NameError"], "correct": 0},
        {"text": "Dictionary'da mavjud bo'lmagan kalitga murojaat qilganda qaysi xatolik yuzaga keladi?",
         "choices": ["KeyError", "IndexError", "ValueError", "AttributeError"], "correct": 0},
        {"text": "Dasturchi o'zi xatolik chiqarish uchun qaysi kalit so'zni ishlatadi?",
         "choices": ["raise", "throw", "error", "except"], "correct": 0},
        {"text": "Bir try blokida bir nechta except bloki bo'lishi mumkinmi?",
         "choices": ["Ha, turli xatolik turlari uchun", "Yo'q, faqat bitta except", "Yo'q, hech qachon", "Faqat 2 tagacha"], "correct": 0},
        {"text": "int(\"abc\") bajarilganda qaysi xatolik yuzaga keladi?",
         "choices": ["ValueError", "TypeError", "KeyError", "IndexError"], "correct": 0},
    ],
    "(Python) Modullar va paketlar": [
        {"text": "Boshqa faylda yozilgan kodni joriy faylga qo'shish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["import", "include", "require", "use"], "correct": 0},
        {"text": "Modulning faqat ma'lum qismini import qilish uchun qaysi sintaksis ishlatiladi?",
         "choices": ["from module import name", "import module.name", "include module(name)", "use module::name"], "correct": 0},
        {"text": "Import qilingan modulga qisqa taxallus berish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["as", "alias", "rename", "like"], "correct": 0},
        {"text": "Fayl to'g'ridan-to'g'ri ishga tushirilganda __name__ o'zgaruvchisi qanday qiymatga teng bo'ladi?",
         "choices": ["\"__main__\"", "Fayl nomi", "None", "\"module\""], "correct": 0},
        {"text": "Python import qilishda modullarni qaysi ro'yxat bo'yicha izlaydi?",
         "choices": ["sys.path", "sys.modules only", "os.environ", "PATH faqat"], "correct": 0},
        {"text": "Papkani Python paketi sifatida belgilash uchun (eski uslubda) qanday fayl kerak?",
         "choices": ["__init__.py", "package.json", "setup.cfg", "main.py"], "correct": 0},
        {"text": "Virtual muhit (venv) yaratish uchun qaysi buyruq ishlatiladi?",
         "choices": ["python -m venv venv", "pip install venv", "venv create", "python venv new"], "correct": 0},
        {"text": "Modul va paket o'rtasidagi farq nima?",
         "choices": ["Paket — modullar to'plamini o'z ichiga olgan papka", "Farqi yo'q", "Modul har doim kattaroq", "Paket faqat bitta fayl"], "correct": 0},
        {"text": "\"from module import *\" nima qiladi?",
         "choices": ["Moduldagi barcha ochiq nomlarni import qiladi", "Hech narsa import qilmaydi", "Faqat bitta funksiyani import qiladi", "Xatolik beradi"], "correct": 0},
        {"text": "O'z modulingizni yaratish uchun nima kifoya?",
         "choices": [".py kengaytmali fayl yozish", "Faqat maxsus litsenziya", "PyPI'ga yuklash shart", "Faqat class yozish"], "correct": 0},
    ],
    "(Python) Fayllar bilan ishlash": [
        {"text": "Faylni ochish uchun qaysi funksiya ishlatiladi?",
         "choices": ["open()", "read()", "file()", "load()"], "correct": 0},
        {"text": "Faylni faqat o'qish uchun ochish rejimi qaysi?",
         "choices": ["r", "w", "a", "x"], "correct": 0},
        {"text": "Faylni yozish uchun (mavjud tarkibni o'chirib) ochish rejimi qaysi?",
         "choices": ["w", "r", "a", "x"], "correct": 0},
        {"text": "Faylga mavjud tarkib oxiriga qo'shib yozish rejimi qaysi?",
         "choices": ["a", "w", "r", "x"], "correct": 0},
        {"text": "Faylni avtomatik yopishni ta'minlovchi konstruksiya qaysi?",
         "choices": ["with open(...) as f:", "auto_close()", "file.safe()", "try open()"], "correct": 0},
        {"text": "Faylning bitta qatorini o'qish uchun qaysi metod ishlatiladi?",
         "choices": ["readline()", "read()", "readlines()", "getline()"], "correct": 0},
        {"text": "Faylning barcha qatorlarini ro'yxat sifatida olish uchun qaysi metod ishlatiladi?",
         "choices": ["readlines()", "readline()", "read()", "lines()"], "correct": 0},
        {"text": "CSV fayllar bilan ishlash uchun qaysi standart modul ishlatiladi?",
         "choices": ["csv", "json", "os", "sys"], "correct": 0},
        {"text": "JSON fayllar bilan ishlash uchun qaysi standart modul ishlatiladi?",
         "choices": ["json", "csv", "re", "io"], "correct": 0},
        {"text": "\"with\" konstruksiyasi (context manager) ishlatishning asosiy sababi nima?",
         "choices": ["Resursni (faylni) avtomatik to'g'ri yopish", "Kodni tezlashtirish", "Xotira sarflamaslik", "Internetga ulanish"], "correct": 0},
    ],
    "(Python) Git va GitHub asoslari": [
        {"text": "Git va GitHub o'rtasidagi asosiy farq nima?",
         "choices": ["Git — versiya nazorati tizimi, GitHub — uni onlayn joylashtirish xizmati", "Ular bir xil narsa", "GitHub — dasturlash tili", "Git faqat GitHub ichida ishlaydi"], "correct": 0},
        {"text": "Joriy papkani Git repozitoriyasiga aylantirish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git init", "git start", "git new", "git create"], "correct": 0},
        {"text": "O'zgarishlarni keyingi commit uchun tayyorlash (staging) buyrug'i qaysi?",
         "choices": ["git add", "git commit", "git push", "git stage"], "correct": 0},
        {"text": "O'zgarishlarni tarixga yozib qo'yish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git commit", "git add", "git save", "git log"], "correct": 0},
        {"text": "Lokal commit'larni masofaviy repozitoriyaga yuborish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git push", "git pull", "git fetch", "git send"], "correct": 0},
        {"text": "Masofaviy repozitoriyadan o'zgarishlarni olish uchun qaysi buyruq ishlatiladi?",
         "choices": ["git pull", "git push", "git commit", "git clone only"], "correct": 0},
        {"text": "Git kuzatmasligi kerak bo'lgan fayllar ro'yxati qaysi faylda saqlanadi?",
         "choices": [".gitignore", "README.md", "ignore.txt", "config.git"], "correct": 0},
        {"text": "Loyihani tanishtiruvchi hujjat odatda qaysi fayl nomi bilan yoziladi?",
         "choices": ["README.md", "INFO.txt", "ABOUT.py", "index.md"], "correct": 0},
        {"text": "GitHub'da loyihani mahalliy kompyuterga nusxalash uchun qaysi buyruq ishlatiladi?",
         "choices": ["git clone", "git copy", "git download", "git fetch only"], "correct": 0},
        {"text": "\"Har dars yangi commit bilan yuklash\" tavsiyasining maqsadi nima?",
         "choices": ["O'zgarishlar tarixini muntazam va tushunarli saqlash", "Faylni kattalashtirish", "Internetni tekshirish", "Loyihani sekinlashtirish"], "correct": 0},
    ],
    "(Python) OOP — Class va Object": [
        {"text": "Class'dan yaratilgan aniq nusxa qanday ataladi?",
         "choices": ["Object (obyekt)", "Function", "Module", "Variable"], "correct": 0},
        {"text": "Yangi obyekt yaratilganda avtomatik chaqiriladigan maxsus metod qaysi?",
         "choices": ["__init__", "__start__", "__new__", "__create__"], "correct": 0},
        {"text": "Class metodlarida obyektning o'zini bildiruvchi birinchi parametr odatda qanday nomlanadi?",
         "choices": ["self", "this", "me", "obj"], "correct": 0},
        {"text": "Har bir obyektga xos, alohida saqlanadigan atribut qanday ataladi?",
         "choices": ["Instance attribute", "Class attribute", "Static attribute", "Global attribute"], "correct": 0},
        {"text": "Barcha obyektlar uchun umumiy bo'lgan atribut qanday ataladi?",
         "choices": ["Class attribute", "Instance attribute", "Local attribute", "Private attribute"], "correct": 0},
        {"text": "Obyektga bog'liq bo'lmagan, klass ichida yoziladigan metod qanday ataladi?",
         "choices": ["Static method (@staticmethod)", "Instance method", "Magic method", "Property method"], "correct": 0},
        {"text": "Klassning o'ziga murojaat qiluvchi metod turi qaysi?",
         "choices": ["Class method (@classmethod)", "Static method", "Instance method", "Private method"], "correct": 0},
        {"text": "Procedural va OOP yondashuv o'rtasidagi asosiy farq nima?",
         "choices": ["OOP ma'lumot va funksiyalarni obyekt ichida birlashtiradi", "Farqi yo'q", "Procedural tezroq har doim", "OOP faqat Python'da mavjud"], "correct": 0},
        {"text": "Class e'lon qilish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["class", "object", "struct", "type"], "correct": 0},
        {"text": "@classmethod dekoratori ostidagi metodning birinchi parametri odatda nima deb ataladi?",
         "choices": ["cls", "self", "class_", "obj"], "correct": 0},
    ],
    "(Python) Encapsulation va Property": [
        {"text": "Atribut nomi oldida bitta pastki chiziq (_attr) nimani anglatadi?",
         "choices": ["Protected (himoyalangan, konventsiya bo'yicha)", "Public", "Private (majburiy)", "Static"], "correct": 0},
        {"text": "Atribut nomi oldida ikkita pastki chiziq (__attr) nimani anglatadi?",
         "choices": ["Private (name mangling qo'llaniladi)", "Public", "Protected", "Constant"], "correct": 0},
        {"text": "Name mangling nima uchun ishlatiladi?",
         "choices": ["Private atributlarni tashqi to'qnashuvdan himoyalash", "Kodni tezlashtirish", "Xotira tejash", "Internetga ulanish"], "correct": 0},
        {"text": "Metodni atribut kabi chaqirish imkonini beruvchi dekorator qaysi?",
         "choices": ["@property", "@staticmethod", "@classmethod", "@abstractmethod"], "correct": 0},
        {"text": "Property qiymatini o'zgartirish uchun ishlatiladigan dekorator qaysi?",
         "choices": ["@x.setter", "@x.getter", "@x.property", "@x.value"], "correct": 0},
        {"text": "Faqat o'qish uchun (read-only) property qanday yaratiladi?",
         "choices": ["Faqat @property berish, setter bermaslik", "__init__ ichida yozish", "Public atribut qilish", "Static method qilish"], "correct": 0},
        {"text": "Encapsulation (inkapsulyatsiya) tushunchasi nimani anglatadi?",
         "choices": ["Ma'lumot va uni boshqaruvchi metodlarni birlashtirib, tashqi kirishni cheklash", "Klasslarni meros qilib olish", "Bir nomdagi metodlar", "Obyektlarni yaratish"], "correct": 0},
        {"text": "Public, protected va private atributlar o'rtasidagi farq nima bilan bog'liq?",
         "choices": ["Tashqaridan kirish darajasi (konventsiya)", "Tezlik", "Xotira hajmi", "Rang"], "correct": 0},
        {"text": "Property qiymatini o'chirish uchun qaysi dekorator ishlatiladi?",
         "choices": ["@x.deleter", "@x.remove", "@x.clear", "@x.delete_property"], "correct": 0},
        {"text": "@property qo'llash orqali qanday afzallikka erishiladi?",
         "choices": ["Metodni oddiy atribut kabi ishlatish, validatsiya qo'shish imkoniyati", "Kod tezligini oshirish", "Xotirani kamaytirish", "Klassni yashirish"], "correct": 0},
    ],
    "(Python) Inheritance (Meros olish)": [
        {"text": "Bir klass boshqa klassning xususiyatlarini olishi qanday ataladi?",
         "choices": ["Inheritance (meros olish)", "Encapsulation", "Polymorphism", "Abstraction"], "correct": 0},
        {"text": "Ota klass metodini bola klassdan chaqirish uchun qaysi funksiya ishlatiladi?",
         "choices": ["super()", "parent()", "base()", "extend()"], "correct": 0},
        {"text": "Bola klass ota klass metodini o'zgacha amalga oshirsa, bu qanday ataladi?",
         "choices": ["Method overriding", "Method overloading", "Method hiding", "Method binding"], "correct": 0},
        {"text": "Obyekt ma'lum klass namunasi ekanligini tekshiruvchi funksiya qaysi?",
         "choices": ["isinstance()", "issubclass()", "type_of()", "is_a()"], "correct": 0},
        {"text": "Bir klass boshqasining kichik klassi ekanligini tekshiruvchi funksiya qaysi?",
         "choices": ["issubclass()", "isinstance()", "is_child()", "is_parent()"], "correct": 0},
        {"text": "Meros olishda qidiruv tartibi (qaysi metod chaqirilishi) qanday ataladi?",
         "choices": ["MRO (Method Resolution Order)", "Inheritance chain", "Class path", "Object order"], "correct": 0},
        {"text": "class Dog(Animal): konstruksiyasida Animal nima hisoblanadi?",
         "choices": ["Ota (parent/base) klass", "Bola (child) klass", "Instance", "Module"], "correct": 0},
        {"text": "Bir tomonlama meros olish (single inheritance) nimani anglatadi?",
         "choices": ["Bola klass faqat bitta ota klassdan meros oladi", "Klass hech kimdan meros olmaydi", "Bir nechta ota klassdan meros olish", "Faqat interfeys meros olish"], "correct": 0},
        {"text": "super().__init__() odatda qayerda chaqiriladi?",
         "choices": ["Bola klassning __init__ metodida", "Faqat ota klassda", "Modul boshida", "Hech qayerda"], "correct": 0},
        {"text": "Meros olishning asosiy afzalligi nima?",
         "choices": ["Kodni qayta ishlatish va tuzilmani kengaytirish", "Xotirani kamaytirish", "Faylni kichraytirish", "Tezlikni oshirish"], "correct": 0},
    ],
    "(Python) Multiple inheritance va Mixin": [
        {"text": "Bir klass bir nechta ota klassdan meros olishi qanday ataladi?",
         "choices": ["Multiple inheritance", "Single inheritance", "Polymorphism", "Encapsulation"], "correct": 0},
        {"text": "Ikki ota klassda bir xil metod bo'lsa, qaysi biri chaqirilishini aniqlaydigan algoritm qaysi?",
         "choices": ["C3 linearization (MRO)", "Alphabetical order", "Random order", "First declared only"], "correct": 0},
        {"text": "\"Diamond problem\" (olmos muammosi) qachon yuzaga keladi?",
         "choices": ["Ikki klass umumiy ota klassdan meros olib, uchinchi klass ikkalasidan meros olganda", "Bitta klassda", "Meros olish umuman bo'lmaganda", "Faqat static metodlarda"], "correct": 0},
        {"text": "Mixin klass nima uchun ishlatiladi?",
         "choices": ["Qo'shimcha funksionallikni boshqa klasslarga \"aralashtirish\" uchun", "Asosiy klass sifatida", "Faqat testlash uchun", "Xatolik ushlash uchun"], "correct": 0},
        {"text": "Composition va Inheritance o'rtasidagi farq nima?",
         "choices": ["Composition — obyektlarni birlashtiradi, Inheritance — xususiyatlarni meros oladi", "Farqi yo'q", "Composition faqat Java'da bor", "Inheritance faqat Python'da bor"], "correct": 0},
        {"text": "Mixin klasslar odatda mustaqil holda qanday ishlatiladi?",
         "choices": ["Kamdan-kam yolg'iz, ko'proq boshqa klasslar bilan birga", "Har doim yolg'iz obyekt sifatida", "Hech qachon ishlatilmaydi", "Faqat asosiy klass sifatida"], "correct": 0},
        {"text": "MRO chuqur tahlilida C3 linearization nimani ta'minlaydi?",
         "choices": ["Izchil va oldindan aytib bo'ladigan metod qidiruv tartibini", "Tasodifiy tartibni", "Faqat tezlikni", "Xotira tejashni"], "correct": 0},
        {"text": "Multiple inheritance qachon ehtiyotkorlik bilan ishlatilishi kerak?",
         "choices": ["Klasslar orasida nom to'qnashuvi yoki murakkablik xavfi bo'lganda", "Hech qachon ehtiyot bo'lish shart emas", "Faqat bitta klass bo'lganda", "Faqat static metodlarda"], "correct": 0},
        {"text": "Composition \"has-a\" munosabatini, Inheritance esa qaysi munosabatni ifodalaydi?",
         "choices": ["\"is-a\" munosabatini", "\"has-a\" munosabatini ham", "Hech qanday munosabatni", "Faqat vaqtinchalik munosabat"], "correct": 0},
        {"text": "Python'da klass bir nechta ota klassdan qanday meros oladi (sintaksis)?",
         "choices": ["class C(A, B):", "class C: extends A, B", "class C implements A, B:", "class C -> A, B:"], "correct": 0},
    ],
    "(Python) Polymorphism va Abstract Class": [
        {"text": "Turli klasslarning bir xil metod nomi bilan turlicha ishlashi qanday ataladi?",
         "choices": ["Polymorphism (polimorfizm)", "Encapsulation", "Inheritance", "Abstraction"], "correct": 0},
        {"text": "Python'da \"Duck typing\" tushunchasi nimani anglatadi?",
         "choices": ["Obyekt tipi emas, uning xatti-harakati (metodlari) muhimligi", "Faqat o'rdak klassiga tegishli kod", "Statik tiplash tizimi", "Xatolik turi"], "correct": 0},
        {"text": "Operatorlarni klass uchun qayta belgilash (masalan +) qanday ataladi?",
         "choices": ["Operator overloading", "Operator overriding", "Operator mixing", "Operator binding"], "correct": 0},
        {"text": "Abstract klass yaratish uchun qaysi modul ishlatiladi?",
         "choices": ["abc", "abstract", "typing", "collections"], "correct": 0},
        {"text": "Klassni abstract qilish uchun qaysi bazaviy klassdan meros olinadi?",
         "choices": ["ABC", "object faqat", "Base", "Interface"], "correct": 0},
        {"text": "Bola klassda albatta amalga oshirilishi shart bo'lgan metod qaysi dekorator bilan belgilanadi?",
         "choices": ["@abstractmethod", "@staticmethod", "@classmethod", "@property"], "correct": 0},
        {"text": "Abstract klassdan to'g'ridan-to'g'ri obyekt yaratib bo'ladimi?",
         "choices": ["Yo'q, abstract metodlar amalga oshirilmagunча", "Ha, har doim mumkin", "Faqat static metod bo'lsa mumkin", "Faqat bitta marta mumkin"], "correct": 0},
        {"text": "Python'da \"interfeys\" tushunchasiga eng yaqin narsa nima?",
         "choices": ["Abstract Base Class (ABC)", "Dictionary", "Tuple", "Lambda"], "correct": 0},
        {"text": "Polimorfizmning amaliy foydasi nima?",
         "choices": ["Bir xil interfeys orqali turli obyektlar bilan bir xilda ishlash", "Xotirani kamaytirish", "Kodni yashirish", "Tezlikni oshirish"], "correct": 0},
        {"text": "len(obj) chaqirilganda qaysi maxsus metod ishga tushadi (operator overloading misoli)?",
         "choices": ["__len__", "__size__", "__count__", "__length__"], "correct": 0},
    ],
    "(Python) Magic / Dunder metodlar": [
        {"text": "Obyektni foydalanuvchiga tushunarli matn sifatida ko'rsatish uchun qaysi metod ishlatiladi?",
         "choices": ["__str__", "__repr__", "__format__", "__display__"], "correct": 0},
        {"text": "Obyektni dasturchi uchun texnik/aniq ko'rinishda ko'rsatuvchi metod qaysi?",
         "choices": ["__repr__", "__str__", "__text__", "__info__"], "correct": 0},
        {"text": "len() funksiyasi ishlashi uchun klassda qaysi metod yozilishi kerak?",
         "choices": ["__len__", "__length__", "__size__", "__count__"], "correct": 0},
        {"text": "obj[i] kabi indeks orqali murojaat qilish uchun qaysi metod kerak?",
         "choices": ["__getitem__", "__setitem__", "__delitem__", "__index__"], "correct": 0},
        {"text": "obj[i] = value orqali qiymat o'rnatish uchun qaysi metod kerak?",
         "choices": ["__setitem__", "__getitem__", "__delitem__", "__update__"], "correct": 0},
        {"text": "\"==\" solishtirish operatori ishlashi uchun qaysi metod yoziladi?",
         "choices": ["__eq__", "__equal__", "__compare__", "__is__"], "correct": 0},
        {"text": "\"<\" (kichik) solishtirish operatori uchun qaysi metod yoziladi?",
         "choices": ["__lt__", "__less__", "__smaller__", "__below__"], "correct": 0},
        {"text": "Obyektni bool() ichida baholash (True/False) uchun qaysi metod ishlatiladi?",
         "choices": ["__bool__", "__truth__", "__valid__", "__check__"], "correct": 0},
        {"text": "Obyektni funksiya kabi chaqirish imkonini beruvchi metod qaysi?",
         "choices": ["__call__", "__invoke__", "__run__", "__exec__"], "correct": 0},
        {"text": "Obyekt yo'q qilinganda (garbage collection paytida) chaqiriluvchi metod qaysi?",
         "choices": ["__del__", "__delete__", "__remove__", "__destroy__"], "correct": 0},
    ],
    "(Python) References va Memory boshqaruvi": [
        {"text": "Python'da o'zgaruvchi aslida nimani saqlaydi?",
         "choices": ["Obyektga havolani (reference)", "Obyektning to'liq nusxasini har doim", "Faqat tip nomini", "Hech narsa saqlamaydi"], "correct": 0},
        {"text": "Python o'zgaruvchi tiplashida qanday yondashuv qo'llaniladi?",
         "choices": ["Dynamic typing (dinamik tiplash)", "Static typing only", "No typing", "Manual typing only"], "correct": 0},
        {"text": "list, dict kabi tiplar qanday xususiyatga ega?",
         "choices": ["Mutable (o'zgaruvchan)", "Immutable (o'zgarmas)", "Faqat readonly", "Constant"], "correct": 0},
        {"text": "int, str, tuple kabi tiplar qanday xususiyatga ega?",
         "choices": ["Immutable (o'zgarmas)", "Mutable (o'zgaruvchan)", "Har doim null", "Dinamik o'lchamli"], "correct": 0},
        {"text": "\"is\" va \"==\" operatorlari orasidagi farq nima?",
         "choices": ["is — bir xil obyekt ekanligini, == — qiymatlar tengligini tekshiradi", "Farqi yo'q", "is faqat sonlar uchun", "== faqat matnlar uchun"], "correct": 0},
        {"text": "Qiymat yo'qligini bildiruvchi maxsus konstanta qaysi?",
         "choices": ["None", "Null", "Undefined", "NaN"], "correct": 0},
        {"text": "Ishlatilmayotgan obyektlarni xotiradan avtomatik tozalash mexanizmi qanday ataladi?",
         "choices": ["Garbage collection", "Memory cleaning", "Auto delete", "Object purge"], "correct": 0},
        {"text": "Obyektning xotiradagi noyob identifikatorini olish uchun qaysi funksiya ishlatiladi?",
         "choices": ["id()", "ref()", "addr()", "mem()"], "correct": 0},
        {"text": "Obyekt qancha xotira egallashini bilish uchun qaysi funksiya ishlatiladi?",
         "choices": ["sys.getsizeof()", "len()", "size()", "memory()"], "correct": 0},
        {"text": "Mutable obyekt funksiyaga uzatilganda funksiya ichida o'zgartirilsa, nima yuz beradi?",
         "choices": ["Original obyekt ham o'zgaradi (reference orqali)", "Faqat nusxasi o'zgaradi", "Hech narsa o'zgarmaydi", "Xatolik chiqadi"], "correct": 0},
    ],
    "(Python) Sonlar chuqur va Sequence types": [
        {"text": "Python'da int tipi qanday xususiyatga ega (boshqa ko'p tillardan farqli)?",
         "choices": ["Cheksiz katta bo'lishi mumkin", "Faqat 32-bit bilan cheklangan", "Faqat manfiy bo'ladi", "Har doim 0 dan boshlanadi"], "correct": 0},
        {"text": "Aniq (dumaloqlashtirmasdan) o'nlik hisob-kitoblar uchun qaysi modul ishlatiladi?",
         "choices": ["decimal", "float built-in", "int built-in", "complex"], "correct": 0},
        {"text": "0.1 + 0.2 natijasi Python'da nima uchun aniq 0.3 ga teng emas?",
         "choices": ["Float sonlarning ikkilik tizimda taqribiy saqlanishi tufayli", "Python xato ishlaydi", "0.1 va 0.2 noto'g'ri yozilgan", "Bu Python'ga xos emas"], "correct": 0},
        {"text": "Kasrlar (fraction) bilan aniq ishlash uchun qaysi modul ishlatiladi?",
         "choices": ["fractions", "decimal", "math", "random"], "correct": 0},
        {"text": "list, tuple, str, range kabi tiplar umumiy nom bilan qanday ataladi?",
         "choices": ["Sequence types", "Mapping types", "Set types", "Numeric types"], "correct": 0},
        {"text": "collections.abc moduli nima uchun ishlatiladi?",
         "choices": ["Abstract base class'lar orqali tip tekshirish/tuzilma yaratish uchun", "Fayllar bilan ishlash uchun", "Tarmoq so'rovlari uchun", "Grafik chizish uchun"], "correct": 0},
        {"text": "Sequence turlarining umumiy xususiyati nima?",
         "choices": ["Indeks orqali tartiblangan murojaat qilish mumkinligi", "Barchasi o'zgarmas bo'lishi", "Barchasi noyob elementli bo'lishi", "Indeks ishlatib bo'lmasligi"], "correct": 0},
        {"text": "complex son qanday yoziladi (masalan)?",
         "choices": ["3 + 4j", "3 + 4i", "complex(3, 4) faqat", "3 & 4"], "correct": 0},
        {"text": "decimal moduli ayniqsa qaysi sohada muhim?",
         "choices": ["Moliyaviy/pul hisob-kitoblarida", "Grafik dasturlashda", "Tarmoq dasturlashda", "Matn qayta ishlashda"], "correct": 0},
        {"text": "range obyekti ham sequence turiga kiradimi?",
         "choices": ["Ha", "Yo'q", "Faqat Python 2'da", "Faqat manfiy sonlarda"], "correct": 0},
    ],
    "(Python) Closures va Decoratorlar — 1-qism": [
        {"text": "Python'da funksiyalar qanday obyekt hisoblanadi?",
         "choices": ["Birinchi sinf obyekti (o'zgaruvchiga tenglashtirilishi mumkin)", "Faqat maxsus tip", "Klass emas obyekt emas", "Modul"], "correct": 0},
        {"text": "Ichki funksiya tashqi funksiyaning o'zgaruvchisini \"eslab qolishi\" qanday ataladi?",
         "choices": ["Closure (yopilma)", "Decorator", "Generator", "Iterator"], "correct": 0},
        {"text": "Ichki funksiyadan tashqi (lekin global bo'lmagan) o'zgaruvchini o'zgartirish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["nonlocal", "global", "outer", "external"], "correct": 0},
        {"text": "Boshqa funksiyani \"o'rab olib\", uning xatti-harakatini kengaytiruvchi funksiya qanday ataladi?",
         "choices": ["Decorator", "Closure only", "Generator", "Mixin"], "correct": 0},
        {"text": "Decorator qo'llash uchun qaysi belgi ishlatiladi?",
         "choices": ["@", "#", "$", "&"], "correct": 0},
        {"text": "Decorator asl funksiyaning metadata'sini (nomi, docstring) saqlab qolishi uchun qaysi vosita ishlatiladi?",
         "choices": ["functools.wraps", "functools.cache", "functools.reduce", "functools.partial"], "correct": 0},
        {"text": "Funksiya bajarilish vaqtini o'lchash uchun yoziladigan decorator qanday ataladi?",
         "choices": ["Timer decorator", "Logger only", "Cache decorator", "Wrapper only"], "correct": 0},
        {"text": "Closure hosil bo'lishi uchun qanday shart bajarilishi kerak?",
         "choices": ["Ichki funksiya tashqi funksiya o'zgaruvchisiga murojaat qilishi", "Faqat global o'zgaruvchi bo'lishi", "Funksiya hech narsaga murojaat qilmasligi", "Klass ichida bo'lishi"], "correct": 0},
        {"text": "Decorator sintaksisi (@decorator) aslida nimaga teng?",
         "choices": ["func = decorator(func)", "func = func(decorator)", "decorator = func()", "import decorator"], "correct": 0},
        {"text": "Log yozuvchi (logger) decorator odatda nima qiladi?",
         "choices": ["Funksiya chaqirilishi haqida ma'lumot yozib boradi", "Funksiyani o'chiradi", "Xotirani tozalaydi", "Internetga ulanadi"], "correct": 0},
    ],
    "(Python) Decoratorlar — 2-qism": [
        {"text": "Parametr qabul qiluvchi decorator qanday ataladi?",
         "choices": ["Decorator factory (argumentli decorator)", "Simple decorator", "Static decorator", "Class only decorator"], "correct": 0},
        {"text": "Klasslarga qo'llaniladigan decoratorlar qanday ataladi?",
         "choices": ["Class decorators", "Function decorators only", "Method decorators only", "Static decorators"], "correct": 0},
        {"text": "Bitta funksiyaga bir nechta decorator qo'llash mumkinmi?",
         "choices": ["Ha, ketma-ket qo'llanadi", "Yo'q, faqat bitta", "Faqat 2 tagacha", "Hech qachon"], "correct": 0},
        {"text": "Funksiya natijalarini keshlash (keyingi chaqiruvlarda tezlashtirish) uchun qaysi tayyor decorator ishlatiladi?",
         "choices": ["functools.lru_cache", "functools.wraps", "functools.reduce", "functools.partial"], "correct": 0},
        {"text": "@property ham aslida qanday mexanizm hisoblanadi?",
         "choices": ["Bir turdagi decorator", "Klass", "Modul", "Xatolik turi"], "correct": 0},
        {"text": "Argumentli decoratorlar ichki tuzilishida odatda nechta \"qavat\" funksiya bo'ladi?",
         "choices": ["Uchta (decorator factory -> decorator -> wrapper)", "Faqat bitta", "Ikkita har doim yetarli", "To'rtta shart"], "correct": 0},
        {"text": "Bir nechta decorator qo'llanganda ular qaysi tartibda ishlaydi?",
         "choices": ["Pastdan yuqoriga (eng yaqinidan boshlab)", "Yuqoridan pastga har doim", "Tasodifiy tartibda", "Alifbo tartibida"], "correct": 0},
        {"text": "lru_cache dekoratoridagi \"lru\" nimani anglatadi?",
         "choices": ["Least Recently Used", "Long Running Unit", "Local Runtime Update", "Linked Reference Unit"], "correct": 0},
        {"text": "Class decorator odatda nimani o'zgartiradi yoki kengaytiradi?",
         "choices": ["Klassning o'zini yoki uning atributlarini", "Faqat modulni", "Faqat faylni", "Faqat operatsion tizimni"], "correct": 0},
        {"text": "Decoratorlarning asosiy maqsadi nima?",
         "choices": ["Kodni o'zgartirmasdan funksionallikni qayta ishlatiladigan tarzda kengaytirish", "Kodni sekinlashtirish", "Xatoликларни yashirish", "Faylni siqish"], "correct": 0},
    ],
    "(Python) Iteratorlar va Generatorlar": [
        {"text": "Iterable va Iterator o'rtasidagi farq nima?",
         "choices": ["Iterable — ustidan yurish mumkin bo'lgan obyekt, Iterator — joriy holatni saqlaydigan obyekt", "Farqi yo'q", "Iterator har doim ro'yxat", "Iterable faqat matn"], "correct": 0},
        {"text": "Obyektni iterable qilish uchun qaysi metod kerak?",
         "choices": ["__iter__", "__next__ faqat", "__len__", "__getitem__ faqat"], "correct": 0},
        {"text": "Iterator'dan keyingi qiymatni olish uchun qaysi metod kerak?",
         "choices": ["__next__", "__iter__", "__get__", "__step__"], "correct": 0},
        {"text": "Qiymatni funksiyadan \"chiqarib\", holatni saqlab qolish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["yield", "return", "pass", "break"], "correct": 0},
        {"text": "yield ishlatuvchi funksiya qanday ataladi?",
         "choices": ["Generator funksiya", "Iterator funksiya only", "Decorator funksiya", "Lambda funksiya"], "correct": 0},
        {"text": "Qavs o'rniga () bilan yozilgan comprehension qanday ataladi?",
         "choices": ["Generator expression", "List comprehension", "Set comprehension", "Dict comprehension"], "correct": 0},
        {"text": "Bir generatordan boshqa generatorga qiymatlarni uzatish uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["yield from", "return from", "pass from", "next from"], "correct": 0},
        {"text": "Generatorlarning asosiy afzalligi nima?",
         "choices": ["Lazy evaluation — qiymatlarni faqat kerak bo'lganda hisoblab, xotira tejaydi", "Har doim tezroq bo'ladi", "Xatolik bermaydi", "Faqat sonlar uchun ishlaydi"], "correct": 0},
        {"text": "StopIteration xatoligi qachon yuzaga keladi?",
         "choices": ["Iterator'da keyingi element qolmaganda", "Dastur boshida", "Har bir next() chaqiruvida", "Faqat xato bo'lganda"], "correct": 0},
        {"text": "Katta hajmdagi ma'lumotlar bilan ishlashda generator nima uchun list'dan afzal bo'lishi mumkin?",
         "choices": ["Barcha ma'lumotni bir vaqtda xotiraga yuklamaydi", "Har doim tezroq sortlaydi", "Индекс bilan ishlay oladi", "O'zgarmas bo'ladi"], "correct": 0},
    ],
    "(Python) Funksional dasturlash va Named Tuples": [
        {"text": "Ikki yoki undan ortiq iterable'ni juftlashtirib birlashtiruvchi funksiya qaysi?",
         "choices": ["zip()", "map()", "filter()", "reduce()"], "correct": 0},
        {"text": "Iterable elementlariga indeks bilan birga murojaat qilish uchun qaysi funksiya ishlatiladi?",
         "choices": ["enumerate()", "zip()", "range()", "index()"], "correct": 0},
        {"text": "Barcha elementlar True bo'lsa True qaytaruvchi funksiya qaysi?",
         "choices": ["all()", "any()", "sum()", "count()"], "correct": 0},
        {"text": "Kamida bitta element True bo'lsa True qaytaruvchi funksiya qaysi?",
         "choices": ["any()", "all()", "sum()", "len()"], "correct": 0},
        {"text": "sorted() funksiyasida saralash mezonini belgilash uchun qaysi parametr ishlatiladi?",
         "choices": ["key", "sort_by", "order", "index"], "correct": 0},
        {"text": "Nomlangan maydonlarga ega, immutable tuple yaratish uchun qaysi vosita ishlatiladi?",
         "choices": ["collections.namedtuple", "dict", "list", "set"], "correct": 0},
        {"text": "typing.NamedTuple namedtuple'dan qanday farq qiladi?",
         "choices": ["Tip belgilash (type hints) bilan yozilishi mumkin", "Farqi yo'q", "Mutable bo'ladi", "Faqat sonlar saqlaydi"], "correct": 0},
        {"text": "dataclasses moduli nima uchun ishlatiladi?",
         "choices": ["Klass yaratishni soddalashtirish (avtomatik __init__ va h.k.)", "Fayl o'qish uchun", "Tarmoq so'rovlari uchun", "Grafik chizish uchun"], "correct": 0},
        {"text": "map(), filter(), reduce() — bu funksiyalar qaysi dasturlash paradigmasiga xos?",
         "choices": ["Funksional dasturlash", "Faqat OOP", "Faqat procedural", "Faqat deklarativ HTML"], "correct": 0},
        {"text": "zip() funksiyasi natijada nima qaytaradi?",
         "choices": ["Juftliklardan iborat iterator", "Yagona son", "Matn", "Dictionary avtomatik"], "correct": 0},
    ],
    "(Python) Context Managers va Standart kutubxona": [
        {"text": "\"with\" konstruksiyasi ishlatilganda qaysi ikkita maxsus metod chaqiriladi?",
         "choices": ["__enter__ va __exit__", "__init__ va __del__", "__start__ va __stop__", "__open__ va __close__"], "correct": 0},
        {"text": "Oddiy funksiyani context manager'ga aylantirish uchun qaysi dekorator ishlatiladi?",
         "choices": ["contextlib.contextmanager", "functools.wraps", "functools.cache", "abc.abstractmethod"], "correct": 0},
        {"text": "Elementlar sonini avtomatik hisoblovchi standart kutubxona klassi qaysi?",
         "choices": ["collections.Counter", "collections.deque", "collections.OrderedDict", "collections.defaultdict"], "correct": 0},
        {"text": "Kalit mavjud bo'lmaganda avtomatik standart qiymat yaratuvchi dictionary turi qaysi?",
         "choices": ["collections.defaultdict", "collections.Counter", "collections.deque", "dict oddiy"], "correct": 0},
        {"text": "Ikki tomondan tez qo'shish/olib tashlashga mo'ljallangan tuzilma qaysi?",
         "choices": ["collections.deque", "collections.Counter", "list oddiy", "tuple"], "correct": 0},
        {"text": "Kiritilgan tartibni saqlovchi (Python 3.7dan oldin muhim bo'lgan) dictionary turi qaysi?",
         "choices": ["collections.OrderedDict", "collections.Counter", "collections.deque", "collections.namedtuple"], "correct": 0},
        {"text": "itertools moduli nima uchun ishlatiladi?",
         "choices": ["Iteratorlar bilan samarali ishlash uchun qulay funksiyalar to'plami", "Fayl bilan ishlash uchun", "Grafik chizish uchun", "Tarmoq so'rovlari uchun"], "correct": 0},
        {"text": "with statement resurslarni boshqarishda nimani kafolatlaydi?",
         "choices": ["Xatolik yuz bersa ham resurs (masalan fayl) to'g'ri yopilishini", "Kodni tezlashtirishni", "Xotirani ko'paytirishni", "Internetni tezlashtirishni"], "correct": 0},
        {"text": "functools moduli qanday funksiyalarni o'z ichiga oladi?",
         "choices": ["lru_cache, wraps, reduce, partial kabi funksional vositalar", "Faqat matematik funksiyalar", "Faqat tarmoq funksiyalari", "Faqat grafik funksiyalar"], "correct": 0},
        {"text": "__exit__ metodi qachon chaqiriladi?",
         "choices": ["with bloki tugaganda (xatolik bo'lsa ham)", "Faqat dastur boshida", "Faqat xatolik bo'lmaganda", "Hech qachon avtomatik chaqirilmaydi"], "correct": 0},
    ],
    "(Python) Descriptors va Meta Programming": [
        {"text": "Atributga murojaat qilinganda ishga tushuvchi maxsus metod qaysi?",
         "choices": ["__get__", "__call__", "__str__", "__init__"], "correct": 0},
        {"text": "Atributga qiymat berilganda ishga tushuvchi maxsus metod qaysi?",
         "choices": ["__set__", "__get__", "__delete__", "__init__"], "correct": 0},
        {"text": "__get__ va __set__ ikkalasini ham amalga oshirgan descriptor qanday ataladi?",
         "choices": ["Data descriptor", "Non-data descriptor", "Static descriptor", "Class descriptor"], "correct": 0},
        {"text": "Faqat __get__ metodiga ega descriptor qanday ataladi?",
         "choices": ["Non-data descriptor", "Data descriptor", "Full descriptor", "Read-write descriptor"], "correct": 0},
        {"text": "Klasslarni yaratuvchi \"klass\" (klassning klassi) qanday ataladi?",
         "choices": ["Metaclass", "Superclass", "Baseclass", "Subclass"], "correct": 0},
        {"text": "Python'da odatiy klasslarning standart metaклассi qaysi?",
         "choices": ["type", "object", "class", "meta"], "correct": 0},
        {"text": "Meta programming nima uchun ishlatiladi?",
         "choices": ["Kodning o'zini dinamik yaratish/o'zgartirish uchun", "Faqat fayl o'qish uchun", "Faqat internetga ulanish uchun", "Faqat rasm chizish uchun"], "correct": 0},
        {"text": "@property dekoratori aslida qaysi mexanizmga asoslangan?",
         "choices": ["Descriptor protokoliga", "Metaclass'ga", "Generator'ga", "Context manager'ga"], "correct": 0},
        {"text": "Descriptor yozish qachon foydali bo'lishi mumkin?",
         "choices": ["Ko'p klasslarda takrorlanadigan validatsiya/logikani markazlashtirishda", "Faqat oddiy o'zgaruvchi saqlashda", "Hech qachon foydali emas", "Faqat matn chiqarishda"], "correct": 0},
        {"text": "Metaclass qachon haqiqatan kerak bo'ladi (umumiy tavsiya)?",
         "choices": ["Kamdan-kam, murakkab freymvork darajasidagi vazifalarda", "Har doim, oddiy klasslarda ham", "Faqat kichik skriptlarda", "Faqat testlarda"], "correct": 0},
    ],
    "(Python) Concurrency — Multithreading": [
        {"text": "Concurrency va Parallelism o'rtasidagi farq nima?",
         "choices": ["Concurrency — vazifalarni almashtirib bajarish, Parallelism — bir vaqtda haqiqiy bajarish", "Farqi yo'q", "Concurrency faqat GPU'da", "Parallelism faqat 1 protsessorda"], "correct": 0},
        {"text": "Yangi oqim (thread) yaratish uchun qaysi modul ishlatiladi?",
         "choices": ["threading", "multiprocessing", "asyncio", "concurrent"], "correct": 0},
        {"text": "Bir vaqtning o'zida faqat bitta oqim resursga kirishini ta'minlovchi mexanizm qaysi?",
         "choices": ["Lock", "Queue", "Pool", "Event"], "correct": 0},
        {"text": "Bir xil oqim tomonidan qayta qulflanishi mumkin bo'lgan Lock turi qaysi?",
         "choices": ["RLock", "Lock oddiy", "Semaphore", "Event"], "correct": 0},
        {"text": "Bir vaqtda cheklangan sondagi oqimlarga ruxsat beruvchi mexanizm qaysi?",
         "choices": ["Semaphore", "Lock", "Thread", "Queue faqat"], "correct": 0},
        {"text": "Ikki oqim bir-birini abadiy kutib qolishi qanday ataladi?",
         "choices": ["Deadlock", "Race condition", "Livelock only", "Overflow"], "correct": 0},
        {"text": "Bir vaqtda bir nechta oqim umumiy ma'lumotni nazoratsiz o'zgartirishi qanday ataladi?",
         "choices": ["Race condition", "Deadlock", "Livelock", "Segfault"], "correct": 0},
        {"text": "GIL nimani anglatadi?",
         "choices": ["Global Interpreter Lock", "General Input Loop", "Grouped Instance Lock", "Global Index List"], "correct": 0},
        {"text": "GIL Python'da nimaga sabab bo'ladi?",
         "choices": ["Bir vaqtning o'zida faqat bitta Python bayt-kod bajarilishiga", "Dasturni tezlashtirishga", "Xotirani ko'paytirishga", "Xatoликларни yo'qotishga"], "correct": 0},
        {"text": "Oqimlar pulini boshqarish uchun qaysi vosita ishlatiladi?",
         "choices": ["concurrent.futures.ThreadPoolExecutor", "multiprocessing.Pool faqat", "asyncio.gather", "functools.partial"], "correct": 0},
    ],
    "(Python) Concurrency — Multiprocessing": [
        {"text": "Process va Thread o'rtasidagi asosiy farq nima?",
         "choices": ["Process alohida xotira maydoniga ega, Thread esa umumiy xotirani baham ko'radi", "Farqi yo'q", "Thread har doim tezroq", "Process har doim tezroq"], "correct": 0},
        {"text": "Yangi jarayon (process) yaratish uchun qaysi modul ishlatiladi?",
         "choices": ["multiprocessing", "threading", "asyncio", "os faqat"], "correct": 0},
        {"text": "Bir nechta jarayonni parallel boshqarish uchun qaysi vosita ishlatiladi?",
         "choices": ["Pool", "Lock", "Thread", "Event"], "correct": 0},
        {"text": "Jarayonlar orasida ma'lumot almashish uchun qaysi vositalar ishlatiladi?",
         "choices": ["Queue va Pipe", "Faqat global o'zgaruvchi", "Faqat fayl", "Lock faqat"], "correct": 0},
        {"text": "Multiprocessing GIL muammosini qanday hal qiladi?",
         "choices": ["Har bir jarayon o'z Python interpretatoriga ega bo'lgani uchun", "GIL'ni butunlay o'chiradi", "Hal qilmaydi", "Faqat Windows'da hal qiladi"], "correct": 0},
        {"text": "CPU-intensive (protsessorni ko'p band qiluvchi) vazifalar uchun qaysi yondashuv ko'proq mos?",
         "choices": ["Multiprocessing", "Threading ko'proq", "Faqat asyncio", "Hech biri"], "correct": 0},
        {"text": "I/O-intensive vazifalar uchun odatda qaysi yondashuv yetarli bo'ladi?",
         "choices": ["Threading yoki asyncio", "Faqat multiprocessing", "Hech biri", "Faqat single process"], "correct": 0},
        {"text": "Jarayon pulini boshqaruvchi zamonaviy vosita qaysi?",
         "choices": ["concurrent.futures.ProcessPoolExecutor", "threading.Thread", "asyncio.run", "functools.wraps"], "correct": 0},
        {"text": "Pipe nima uchun ishlatiladi?",
         "choices": ["Ikki jarayon o'rtasida ikki tomonlama aloqa o'rnatish uchun", "Faylni siqish uchun", "Xatolik ushlash uchun", "Klass yaratish uchun"], "correct": 0},
        {"text": "Multiprocessing.Pool.map() nima qiladi?",
         "choices": ["Funksiyani bir nechta jarayonda parallel qo'llaydi", "Faqat bitta jarayonda ishlaydi", "Hech narsa qilmaydi", "Faqat sinxron ishlaydi"], "correct": 0},
    ],
    "(Python) Async I/O — 1-qism (asoslar)": [
        {"text": "Sinxron va asinxron dasturlash o'rtasidagi asosiy farq nima?",
         "choices": ["Asinxronda vazifa kutish paytida boshqa vazifalar bajarilishi mumkin", "Farqi yo'q", "Sinxron har doim tezroq", "Asinxron faqat Python'da mavjud"], "correct": 0},
        {"text": "Asinxron dasturlash uchun Python'ning standart moduli qaysi?",
         "choices": ["asyncio", "threading", "multiprocessing", "os"], "correct": 0},
        {"text": "Asinxron funksiya e'lon qilish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["async def", "def async", "coroutine def", "await def"], "correct": 0},
        {"text": "Asinxron funksiya natijasini kutish uchun qaysi kalit so'z ishlatiladi?",
         "choices": ["await", "async", "yield", "wait"], "correct": 0},
        {"text": "async def bilan yaratilgan funksiya chaqirilganda nima qaytaradi?",
         "choices": ["Coroutine obyekti", "Darhol natija", "None har doim", "Xatolik"], "correct": 0},
        {"text": "Asinxron vazifalarni bajaradigan asosiy mexanizm qanday ataladi?",
         "choices": ["Event loop", "Thread pool", "Process pool", "Lock manager"], "correct": 0},
        {"text": "Asinxron kodni ishga tushirishning eng oddiy usuli qaysi funksiya orqali amalga oshiriladi?",
         "choices": ["asyncio.run()", "asyncio.start()", "asyncio.execute()", "asyncio.main()"], "correct": 0},
        {"text": "Asinxron kontekstda kutish (pauza) uchun qaysi funksiya ishlatiladi?",
         "choices": ["asyncio.sleep()", "time.sleep()", "threading.wait()", "os.pause()"], "correct": 0},
        {"text": "await faqat qayerda ishlatilishi mumkin?",
         "choices": ["async def funksiyasi ichida", "Har qanday funksiyada", "Faqat class ichida", "Faqat modul darajasida"], "correct": 0},
        {"text": "Asinxron dasturlash ayniqsa qaysi vazifalarda foydali?",
         "choices": ["Ko'plab tarmoq/I/O so'rovlarini kutish talab qiladigan vazifalarda", "Faqat matematik hisob-kitoblarda", "Faqat grafik chizishda", "Faqat fayl siqishda"], "correct": 0},
    ],
    "(Python) Async I/O — 2-qism (amaliyot)": [
        {"text": "Bir nechta coroutine'ni parallel bajarish va natijalarini yig'ish uchun qaysi funksiya ishlatiladi?",
         "choices": ["asyncio.gather()", "asyncio.sleep()", "asyncio.run()", "asyncio.wait_one()"], "correct": 0},
        {"text": "Coroutine'ni fon vazifasi sifatida rejalashtirish uchun qaysi funksiya ishlatiladi?",
         "choices": ["asyncio.create_task()", "asyncio.gather()", "asyncio.run()", "asyncio.sleep()"], "correct": 0},
        {"text": "Asinxron HTTP so'rovlar yuborish uchun mashhur kutubxona qaysi?",
         "choices": ["aiohttp", "requests only", "urllib faqat", "http.client faqat"], "correct": 0},
        {"text": "Asinxron fayl o'qish uchun qaysi kutubxona ishlatiladi?",
         "choices": ["aiofiles", "open() built-in only", "os.read only", "io faqat"], "correct": 0},
        {"text": "Asinxron kontekstda \"async for\" nima uchun ishlatiladi?",
         "choices": ["Async iterator ustida yurish uchun", "Oddiy list ustida yurish uchun", "Faqat dictionary uchun", "Faqat tuple uchun"], "correct": 0},
        {"text": "Async context manager qanday e'lon qilinadi?",
         "choices": ["async with", "with async", "await with", "async context"], "correct": 0},
        {"text": "requests kabi sinxron kutubxonani asyncio bilan to'g'ridan-to'g'ri ishlatish nima uchun muammoli?",
         "choices": ["Event loop'ni bloklab qo'yishi mumkin", "Umuman ishlamaydi", "Xatolik bermaydi lekin sekin", "Hech qanday muammo yo'q"], "correct": 0},
        {"text": "Sync, Threading va Async yondashuvlarni solishtirganda, Async odatda qachon eng samarali?",
         "choices": ["Ko'p sonli I/O-bog'liq so'rovlarda", "CPU-intensiv hisoblashlarda", "Har doim eng yaxshi", "Hech qachon foydali emas"], "correct": 0},
        {"text": "asyncio.gather() bir nechta coroutine'ni qanday bajaradi?",
         "choices": ["Bir vaqtda (concurrent) bajarib, barcha natijalarni kutadi", "Ketma-ket, birma-bir", "Faqat birinchisini bajaradi", "Tasodifiy tanlab bajaradi"], "correct": 0},
        {"text": "Asinxron dasturlashda xatoliklarni ushlash uchun qaysi konstruksiya ishlatiladi?",
         "choices": ["try/except (oddiy sinxrondagidek)", "async try only", "await except", "Xatolik ushlab bo'lmaydi"], "correct": 0},
    ],
}

FINAL = {
    "quiz_title": "Yakuniy test: Python dasturlash tili va algoritmlari",
    "time_limit_seconds": 4500,
    "question_count": 50,
    "questions": [
        {"text": "Ekranga matn chiqarish funksiyasi?", "choices": ["print()", "echo()", "output()", "write()"], "correct": 0},
        {"text": "Klaviaturadan ma'lumot olish funksiyasi?", "choices": ["input()", "read()", "get()", "scan()"], "correct": 0},
        {"text": "Python kod uslubi standarti?", "choices": ["PEP8", "ES6", "HTML5", "JSON Schema"], "correct": 0},
        {"text": "O'zgarmas qiymatlar odatda qanday nomlanadi?", "choices": ["UPPER_CASE", "camelCase", "lowerCase", "kebab-case"], "correct": 0},
        {"text": "Bir qatorli izoh belgisi?", "choices": ["#", "//", "--", "/*"], "correct": 0},
        {"text": "O'zgaruvchi tipini aniqlash funksiyasi?", "choices": ["type()", "kind()", "class()", "typeof()"], "correct": 0},
        {"text": "String'ning bir qismini olish texnikasi?", "choices": ["Slicing", "Splitting only", "Joining only", "Mapping"], "correct": 0},
        {"text": "O'zgaruvchini string ichiga qulay qo'shish usuli?", "choices": ["F-strings", "Concatenation only", "%s only", "join() only"], "correct": 0},
        {"text": "String'ni bo'laklarga ajratuvchi metod?", "choices": ["split()", "join()", "slice()", "divide()"], "correct": 0},
        {"text": "Bo'linmadan qolgan qoldiqni hisoblovchi operator?", "choices": ["%", "//", "**", "/"], "correct": 0},
        {"text": "Darajaga ko'tarish operatori?", "choices": ["**", "^", "%%", "^^"], "correct": 0},
        {"text": "Bo'sh string, 0, None qanday baholanadi?", "choices": ["Falsy", "Har doim Truthy", "Xatolik", "Aniqlanmaydi"], "correct": 0},
        {"text": "Qisqa shartli ifoda turi?", "choices": ["Ternary operator", "Lambda", "Generator", "Decorator"], "correct": 0},
        {"text": "match-case qaysi versiyadan qo'shilgan?", "choices": ["3.10", "2.7", "3.0", "3.5"], "correct": 0},
        {"text": "Sikldan to'liq chiqish operatori?", "choices": ["break", "continue", "pass", "stop"], "correct": 0},
        {"text": "Joriy iteratsiyani o'tkazib yuboruvchi operator?", "choices": ["continue", "break", "pass", "skip"], "correct": 0},
        {"text": "range(5) qanday sonlar beradi?", "choices": ["0,1,2,3,4", "1..5", "0..5", "5..1"], "correct": 0},
        {"text": "Ustidan iteratsiya qilinadigan obyektlar umumiy nomi?", "choices": ["Iterables", "Constants", "Functions", "Modules"], "correct": 0},
        {"text": "Ro'yxatga oxiriga element qo'shish metodi?", "choices": ["append()", "add()", "insert_end()", "push()"], "correct": 0},
        {"text": "Ro'yxatdan indeks bo'yicha olib, qaytaruvchi metod?", "choices": ["pop()", "remove()", "delete()", "cut()"], "correct": 0},
        {"text": "List comprehension qanday yoziladi?", "choices": ["[x for x in list]", "{x for x in list}", "(x for x in list)", "<x for x in list>"], "correct": 0},
        {"text": "Tuple'ning asosiy xususiyati?", "choices": ["Immutable", "Mutable", "Faqat sonlar", "Tartibsiz"], "correct": 0},
        {"text": "a, *rest = [1,2,3,4] da rest nimaga teng?", "choices": ["[2,3,4]", "[1]", "[1,2,3,4]", "4"], "correct": 0},
        {"text": "Set'ning asosiy xususiyati?", "choices": ["Faqat noyob elementlar", "Dublikat saqlaydi", "Indeksli", "Immutable"], "correct": 0},
        {"text": "O'zgarmas set turi?", "choices": ["frozenset", "constset", "fixedset", "readonlyset"], "correct": 0},
        {"text": "Dictionary asosiy tuzilmasi?", "choices": ["Kalit-qiymat juftlari", "Tartiblangan sonlar", "Noyob elementlar", "O'zgarmas ketma-ketlik"], "correct": 0},
        {"text": "Kalit mavjud bo'lmasa xatolik bermaydigan metod?", "choices": ["get()", "fetch()", "find()", "retrieve()"], "correct": 0},
        {"text": "Funksiya e'lon qilish kalit so'zi?", "choices": ["def", "function", "func", "define"], "correct": 0},
        {"text": "Qiymat qaytarish operatori?", "choices": ["return", "give", "output", "yield only"], "correct": 0},
        {"text": "Noma'lum sondagi positional argumentlar sintaksisi?", "choices": ["*args", "**kwargs", "&args", "...args"], "correct": 0},
        {"text": "Noma'lum sondagi keyword argumentlar sintaksisi?", "choices": ["**kwargs", "*args", "&kwargs", "...kwargs"], "correct": 0},
        {"text": "Bitta qatorli nomsiz funksiya?", "choices": ["Lambda", "Mini funksiya", "Anon function", "Micro function"], "correct": 0},
        {"text": "Xatolikni ushlash bloki?", "choices": ["try/except", "if/else", "for/while", "def/return"], "correct": 0},
        {"text": "Har doim bajariladigan blok?", "choices": ["finally", "else", "except", "raise"], "correct": 0},
        {"text": "Nolga bo'lish xatoligi?", "choices": ["ZeroDivisionError", "ValueError", "TypeError", "OverflowError"], "correct": 0},
        {"text": "Dasturchi o'zi xatolik chiqarish kalit so'zi?", "choices": ["raise", "throw", "error", "except"], "correct": 0},
        {"text": "Modul import qilish kalit so'zi?", "choices": ["import", "include", "require", "use"], "correct": 0},
        {"text": "Fayl to'g'ridan-to'g'ri ishga tushirilganda __name__ nimaga teng?", "choices": ['"__main__"', "Fayl nomi", "None", '"module"'], "correct": 0},
        {"text": "Faylni ochish funksiyasi?", "choices": ["open()", "read()", "file()", "load()"], "correct": 0},
        {"text": "Fayl avtomatik yopilishini ta'minlovchi konstruksiya?", "choices": ["with open() as f:", "auto_close()", "file.safe()", "try open()"], "correct": 0},
        {"text": "O'zgarishlarni tarixga yozish buyrug'i (Git)?", "choices": ["git commit", "git add", "git save", "git log"], "correct": 0},
        {"text": "Masofaviy repo'ga yuborish buyrug'i?", "choices": ["git push", "git pull", "git fetch", "git send"], "correct": 0},
        {"text": "Yangi obyekt yaratilganda chaqiriluvchi metod?", "choices": ["__init__", "__start__", "__new__", "__create__"], "correct": 0},
        {"text": "Obyektning o'zini bildiruvchi birinchi parametr?", "choices": ["self", "this", "me", "obj"], "correct": 0},
        {"text": "Ota klass metodini chaqirish funksiyasi?", "choices": ["super()", "parent()", "base()", "extend()"], "correct": 0},
        {"text": "Bola klass ota metodini o'zgacha amalga oshirishi?", "choices": ["Method overriding", "Method overloading", "Method hiding", "Method binding"], "correct": 0},
        {"text": "Metodni atribut kabi ishlatish dekoratori?", "choices": ["@property", "@staticmethod", "@classmethod", "@abstractmethod"], "correct": 0},
        {"text": "Abstract metod belgilovchi dekorator?", "choices": ["@abstractmethod", "@staticmethod", "@classmethod", "@property"], "correct": 0},
        {"text": "Obyektni matn ko'rinishida chiqaruvchi metod?", "choices": ["__str__", "__repr__ faqat", "__format__", "__display__"], "correct": 0},
        {"text": "\"is\" va \"==\" farqi?", "choices": ["is — obyekt bir xilligi, == — qiymat tengligi", "Farqi yo'q", "is faqat sonlar uchun", "== faqat matn uchun"], "correct": 0},
    ],
}
