"""Scratch bo'limi uchun mavzu testlari (10 savoldan) va yakuniy test (30 savol)."""

MODULE_TITLE = "Scratch bilan tanishuv va asosiy tushunchalar"

QUESTIONS: dict[str, list[dict]] = {
    "Scratch bilan tanishuv. Harakat bloklari": [
        {"text": "Scratch dasturida obyektlar harakatlanadigan asosiy ko'rinish maydoni qanday ataladi?",
         "choices": ["Sprite", "Sahna (Stage)", "Bloklar paneli", "Kostyum"], "correct": 1},
        {"text": "Scratch'da harakatlanuvchi obyekt (masalan, mushuk) qanday ataladi?",
         "choices": ["Stage", "Backdrop", "Sprite", "Script"], "correct": 2},
        {"text": "Sprite'ni ma'lum burchakka aylantirish uchun qaysi blok ishlatiladi?",
         "choices": ["Move", "Turn", "Go to", "Glide"], "correct": 1},
        {"text": "Sprite'ni sahnaning aniq koordinatasiga bir zumda ko'chirish uchun qaysi blok ishlatiladi?",
         "choices": ["Turn", "Go to x: y:", "Point in direction", "Change x by"], "correct": 1},
        {"text": "Scratch sahnasining markazi qaysi koordinataga to'g'ri keladi?",
         "choices": ["x:0, y:0", "x:240, y:180", "x:-240, y:-180", "x:100, y:100"], "correct": 0},
        {"text": "Sprite'ni \"n\" qadam oldinga siljitish uchun qaysi blok ishlatiladi?",
         "choices": ["Turn n degrees", "Move n steps", "Go to x:n y:n", "Point towards"], "correct": 1},
        {"text": "Scratch interfeysida tayyor harakat/ko'rinish bloklari qaysi qismda joylashgan?",
         "choices": ["Sahna", "Kostyumlar", "Bloklar paneli", "Skript maydoni"], "correct": 2},
        {"text": "Mushukni sahnaning chap tomoniga harakatlantirish uchun x koordinatasi qanday o'zgaradi?",
         "choices": ["Ortadi", "Kamayadi", "O'zgarmaydi", "0 ga teng bo'ladi"], "correct": 1},
        {"text": "Bir nechta blok birlashtirilgan holda ma'lum harakatni bajaruvchi tuzilma qanday ataladi?",
         "choices": ["Sprite", "Skript (Script)", "Backdrop", "Extension"], "correct": 1},
        {"text": "Sprite'ni sahna bo'ylab silliq (asta-sekin) harakatlantiruvchi blok qaysi?",
         "choices": ["Move", "Go to", "Glide", "Turn"], "correct": 2},
    ],
    "Tovush va tashqi ko'rinish bloklari. Hodisalar (Events)": [
        {"text": "Sprite'ning tashqi ko'rinishini (masalan rangini yoki hajmini) boshqaruvchi bloklar guruhi qanday ataladi?",
         "choices": ["Sound", "Look (Ko'rinish)", "Motion", "Control"], "correct": 1},
        {"text": "Sprite'ning turli holatlardagi rasmlari (masalan yurish animatsiyasi uchun) qanday ataladi?",
         "choices": ["Backdrop", "Kostyumlar (Costumes)", "Sprite sheet", "Layer"], "correct": 1},
        {"text": "Yashil bayroqcha bosilganda dastur ishga tushishi uchun qaysi hodisa bloki ishlatiladi?",
         "choices": ["When key pressed", "When green flag clicked", "When sprite clicked", "When I receive"], "correct": 1},
        {"text": "Klaviaturadagi tugma bosilganda amal bajarilishi uchun qaysi hodisa bloki ishlatiladi?",
         "choices": ["When key pressed", "When this sprite clicked", "When green flag clicked", "Broadcast"], "correct": 0},
        {"text": "Sprite ustiga sichqoncha bilan bosilganda ishga tushuvchi hodisa bloki qaysi?",
         "choices": ["When key pressed", "When sprite clicked", "When green flag clicked", "Forever"], "correct": 1},
        {"text": "Ovoz chiqarish uchun ishlatiladigan bloklar guruhi qanday ataladi?",
         "choices": ["Sound", "Look", "Sensing", "Operators"], "correct": 0},
        {"text": "Sprite'ning kostyumini keyingisiga almashtirish uchun qaysi blok ishlatiladi?",
         "choices": ["Next costume", "Switch backdrop", "Change color effect", "Show"], "correct": 0},
        {"text": "Bir sprite boshqa sprite'ga signal yuborib, unda harakat boshlatishi uchun qanday mexanizm ishlatiladi?",
         "choices": ["Glide", "Broadcast (xabar yuborish)", "Repeat", "Wait"], "correct": 1},
        {"text": "\"Mushuk salom beradi\" animatsiyasi odatda qaysi ikkita blok turi kombinatsiyasi bilan yaratiladi?",
         "choices": ["Motion + Sensing", "Look + Sound", "Control + Operators", "Variables + Data"], "correct": 1},
        {"text": "Sprite'ni ekranda vaqtincha yashirish uchun qaysi blok ishlatiladi?",
         "choices": ["Hide", "Delete", "Stop", "Remove"], "correct": 0},
    ],
    "Takrorlash bloklari. Shart operatorlari": [
        {"text": "Dastur to'xtovsiz (cheksiz) ishlashi uchun qaysi blok ishlatiladi?",
         "choices": ["Repeat 10", "Forever", "If then", "Wait until"], "correct": 1},
        {"text": "Ma'lum sondagi marta takrorlash uchun qaysi blok ishlatiladi?",
         "choices": ["Forever", "Repeat", "If else", "When flag clicked"], "correct": 1},
        {"text": "Faqat bir shart bajarilganda amal qilish uchun qaysi blok ishlatiladi?",
         "choices": ["If then", "Repeat", "Forever", "Wait"], "correct": 0},
        {"text": "Shart to'g'ri bo'lsa bitta, noto'g'ri bo'lsa boshqa amal bajarilishi uchun qaysi blok ishlatiladi?",
         "choices": ["If then", "If then else", "Repeat until", "Forever"], "correct": 1},
        {"text": "Ikki sprite bir-biriga tegib turganini aniqlash uchun qaysi guruh bloki ishlatiladi?",
         "choices": ["Touching (Sensing)", "Operators", "Control", "Looks"], "correct": 0},
        {"text": "Mushuk chetga urilganda yo'nalishini teskarisiga o'zgartirishi uchun odatda qaysi blok ishlatiladi?",
         "choices": ["If on edge, bounce", "Go to random position", "Glide", "Wait 1 second"], "correct": 0},
        {"text": "\"Repeat\" va \"Forever\" bloklarining asosiy farqi nimada?",
         "choices": ["Rangida", "Repeat cheklangan marta, Forever cheksiz takrorlaydi", "Repeat faqat ovoz chiqaradi", "Farqi yo'q"], "correct": 1},
        {"text": "Shart operatorlari (if/if-else) qaysi blok guruhiga kiradi?",
         "choices": ["Motion", "Control", "Sound", "Looks"], "correct": 1},
        {"text": "Mushuk to'siqqa tegganda \"oh!\" deyishi uchun qaysi ikki blok birga ishlatiladi?",
         "choices": ["Touching + Say", "Forever + Hide", "Repeat + Glide", "Broadcast + Wait"], "correct": 0},
        {"text": "Biror shart rost bo'lguncha kutish uchun qaysi blok ishlatiladi?",
         "choices": ["Wait until", "Repeat 10", "If then", "Forever"], "correct": 0},
    ],
    "Sahna bilan ishlash": [
        {"text": "Sahnaning orqa foni qanday ataladi?",
         "choices": ["Sprite", "Backdrop", "Costume", "Layer"], "correct": 1},
        {"text": "Loyihaga yangi sahna (fon) qo'shish uchun qaysi panel ishlatiladi?",
         "choices": ["Sprite paneli", "Backdrop paneli", "Sound paneli", "Code paneli"], "correct": 1},
        {"text": "Bir fondan ikkinchisiga o'tish uchun qaysi blok ishlatiladi?",
         "choices": ["Switch backdrop to", "Next costume", "Glide to", "Change color"], "correct": 0},
        {"text": "\"Kunning vaqtiga qarab fon o'zgaradi\" loyihasida asosan qaysi blok turi ishlatiladi?",
         "choices": ["Motion", "Switch backdrop + shart operatorlari", "Sound", "Data"], "correct": 1},
        {"text": "Fon o'zgarganda avtomatik ishga tushuvchi hodisa bloki qaysi?",
         "choices": ["When I start as a clone", "When backdrop switches to", "When green flag clicked", "When key pressed"], "correct": 1},
        {"text": "Sahnada bir nechta fon bo'lishi mumkinmi?",
         "choices": ["Yo'q, faqat bitta", "Ha, bir nechtasi qo'shilishi mumkin", "Faqat 2 tagacha", "Faqat premium versiyada"], "correct": 1},
        {"text": "Fon (backdrop) va kostyum (costume) o'rtasidagi farq nimada?",
         "choices": ["Farqi yo'q", "Backdrop — sahna foni, costume — sprite ko'rinishi", "Costume faqat rangli bo'ladi", "Backdrop faqat animatsiyada bo'ladi"], "correct": 1},
        {"text": "Yangi backdrop yuklash uchun qaysi manbalardan foydalanish mumkin emas?",
         "choices": ["Tayyor kutubxona", "Rasm chizish", "Fayldan yuklash", "Boshqa loyihadan nusxalash"], "correct": 3},
        {"text": "Fon o'zgarishini kuzatish uchun qaysi blok guruhi eng mos?",
         "choices": ["Events", "Sound", "Variables", "Operators"], "correct": 0},
        {"text": "Sahna bilan ishlashda loyihani tartibli qilish uchun nima tavsiya etiladi?",
         "choices": ["Har bir holatga alohida backdrop va shart ishlatish", "Faqat bitta backdrop qoldirish", "Sprite'larni o'chirish", "Ovozni o'chirish"], "correct": 0},
    ],
    "Oddiy o'yin yaratish — 1-qism": [
        {"text": "\"Sharchani tutish\" o'yinida yuqoridan tushayotgan obyekt odatda qaysi blok bilan harakatlantiriladi?",
         "choices": ["Change y by (kamaytirish)", "Turn 90 degrees", "Switch costume", "Say hello"], "correct": 0},
        {"text": "O'yin obyektining tezligini oshirish uchun odatda nima o'zgartiriladi?",
         "choices": ["Rangi", "Harakat qadam qiymati", "Ovozi", "Nomi"], "correct": 1},
        {"text": "Sharcha tagga (pastki chegaraga) tekkanini aniqlash uchun qaysi shart ishlatiladi?",
         "choices": ["If y position < chegara then", "If key pressed then", "Forever", "Wait 1 second"], "correct": 0},
        {"text": "O'yin boshlanishida sharchaning boshlang'ich holatini o'rnatish uchun qaysi blok ishlatiladi?",
         "choices": ["Go to x: y:", "Move 10 steps", "Next costume", "Play sound"], "correct": 0},
        {"text": "\"Ball\" obyekti sifatida odatda nima ishlatiladi?",
         "choices": ["Backdrop", "Yangi Sprite", "Variable nomi", "Sound fayli"], "correct": 1},
        {"text": "To'qnashuv (ball va tutuvchi obyekt orasida) qaysi blok bilan tekshiriladi?",
         "choices": ["Touching", "Key pressed", "Mouse down", "Loudness"], "correct": 0},
        {"text": "O'yin uzluksiz ishlashi uchun asosiy o'yin sikli qaysi blok ichida yoziladi?",
         "choices": ["If then", "Forever", "Wait until", "Broadcast"], "correct": 1},
        {"text": "Sharchani tasodifiy x koordinatadan boshlash uchun qaysi funksiya ishlatiladi?",
         "choices": ["pick random", "round", "length of", "join"], "correct": 0},
        {"text": "O'yinchi klaviatura orqali boshqaradigan obyekt uchun qaysi hodisa bloki mos?",
         "choices": ["When key pressed / arrow keys tekshiruvi", "When backdrop switches", "When I start as a clone", "When loudness > 10"], "correct": 0},
        {"text": "O'yin g'oyasini rejalashtirishda birinchi qadam odatda nima?",
         "choices": ["To'g'ridan-to'g'ri kod yozish", "O'yin mexanikasini va obyektlarni aniqlash", "Ovoz qo'shish", "Fonni bezash"], "correct": 1},
    ],
    "Oddiy o'yin yaratish — 2-qism": [
        {"text": "O'yinga hisoblagich (ball soni) qo'shish uchun qaysi blok turi ishlatiladi?",
         "choices": ["Variable (o'zgaruvchi)", "Backdrop", "Sound faqat", "Costume"], "correct": 0},
        {"text": "O'zgaruvchining qiymatini birga oshirish uchun qaysi blok ishlatiladi?",
         "choices": ["Set variable to 0", "Change variable by 1", "Show variable", "Hide variable"], "correct": 1},
        {"text": "\"Game over\" holatini aniqlash uchun odatda nima tekshiriladi?",
         "choices": ["Hayot yoki vaqt tugashi sharti", "Faqat rang", "Faqat ovoz balandligi", "Sprite nomi"], "correct": 0},
        {"text": "\"Game over\" bo'lganda dasturni to'xtatish uchun qaysi blok ishlatiladi?",
         "choices": ["Stop all", "Wait 1 second", "Next costume", "Broadcast only"], "correct": 0},
        {"text": "O'yinga muvaffaqiyatli/muvaffaqiyatsiz holatlar uchun tovush qo'shish qaysi blok guruhi orqali amalga oshiriladi?",
         "choices": ["Sound", "Motion", "Data", "Sensing"], "correct": 0},
        {"text": "O'yin \"ishchi holatga\" keltirilganda nima nazarda tutiladi?",
         "choices": ["Faqat grafik chiroyli bo'lishi", "Barcha mexanika (harakat, ball, game over) to'g'ri ishlashi", "Faqat ovoz to'g'ri bo'lishi", "Faqat nomi to'g'ri bo'lishi"], "correct": 1},
        {"text": "O'yinchi ball to'plaganda variable qiymatini ko'rsatish uchun nima qilinadi?",
         "choices": ["Variable checkbox (show variable) yoqiladi", "Sprite o'chiriladi", "Backdrop o'zgartiriladi", "Ovoz balandligi oshiriladi"], "correct": 0},
        {"text": "O'yinni qayta boshlash (restart) funksiyasi uchun odatda nima qilinadi?",
         "choices": ["Variable va holatlarni boshlang'ich qiymatga qaytarish", "Faqat sahnani o'chirish", "Faqat rangni o'zgartirish", "Hech narsa qilinmaydi"], "correct": 0},
        {"text": "Bir nechta shart bir vaqtda tekshirilishi kerak bo'lsa (masalan hayot va vaqt), qaysi operator ishlatiladi?",
         "choices": ["and / or (Operators)", "Motion", "Sound", "Looks"], "correct": 0},
        {"text": "Yakunlangan oddiy o'yin loyihasida odatda nechta asosiy sprite bo'ladi (kamida)?",
         "choices": ["Faqat 1 ta har doim yetarli", "Kamida 2 ta — o'yinchi va nishon/obyekt", "Hech biri kerak emas", "Faqat backdrop yetarli"], "correct": 1},
    ],
    "Matematik amallar bilan ishlash": [
        {"text": "Tasodifiy son hosil qilish uchun qaysi blok ishlatiladi?",
         "choices": ["pick random", "round", "mod", "sqrt"], "correct": 0},
        {"text": "Qiymatni saqlash va keyin ishlatish uchun nima yaratiladi?",
         "choices": ["Backdrop", "O'zgaruvchi (Variable)", "Costume", "Sound fayli"], "correct": 1},
        {"text": "Sprite'ni tasodifiy joyga sakratish uchun qaysi bloklar birga ishlatiladi?",
         "choices": ["Go to x: pick random y: pick random", "Move 10 steps", "Turn 15 degrees", "Wait 1 second"], "correct": 0},
        {"text": "Operators (matematik amallar) guruhida qaysi amal YO'Q?",
         "choices": ["Qo'shish (+)", "Ko'paytirish (×)", "Broadcast", "Bo'lish (÷)"], "correct": 2},
        {"text": "Ikki o'zgaruvchi qiymatini solishtirish uchun qaysi blok turi ishlatiladi?",
         "choices": ["Comparison operator (>, <, =)", "Motion blok", "Sound blok", "Looks blok"], "correct": 0},
        {"text": "O'zgaruvchiga boshlang'ich qiymat berish uchun qaysi blok ishlatiladi?",
         "choices": ["Set variable to", "Change variable by", "Show variable", "Ask and wait"], "correct": 0},
        {"text": "Foydalanuvchidan son kiritishni so'rash uchun qaysi blok ishlatiladi?",
         "choices": ["Ask and wait", "Say", "Think", "Broadcast"], "correct": 0},
        {"text": "\"pick random 1 to 10\" bloki nima qaytaradi?",
         "choices": ["Har doim 1 ni", "1 dan 10 gacha tasodifiy son", "Har doim 10 ni", "Matn"], "correct": 1},
        {"text": "Matematik amallar bilan ishlashda o'zgaruvchilar odatda qaysi maqsadda ishlatiladi?",
         "choices": ["Ball, tezlik, hayot kabi qiymatlarni saqlash", "Faqat fon rangini o'zgartirish uchun", "Faqat ovoz uchun", "Hech qanday maqsadda"], "correct": 0},
        {"text": "Sprite tasodifiy joyga sakraganda koordinatalar qanday diapazonda bo'lishi kerak (odatda)?",
         "choices": ["Sahna chegarasidan tashqarida", "Sahna chegarasi ichida (masalan -240..240, -180..180)", "Har doim 0,0", "Cheksiz katta"], "correct": 1},
    ],
}

FINAL = {
    "quiz_title": "Yakuniy test: Scratch bilan tanishuv va asosiy tushunchalar",
    "time_limit_seconds": 2700,
    "question_count": 30,
    "questions": [
        {"text": "Scratch'da obyektlar harakatlanadigan asosiy maydon qanday ataladi?",
         "choices": ["Sprite", "Sahna (Stage)", "Kostyum", "Skript"], "correct": 1},
        {"text": "Harakatlanuvchi obyekt Scratch'da qanday ataladi?",
         "choices": ["Backdrop", "Sprite", "Stage", "Sound"], "correct": 1},
        {"text": "Sprite'ni ma'lum burchakka aylantiruvchi blok?",
         "choices": ["Move", "Turn", "Glide", "Go to"], "correct": 1},
        {"text": "Sahnaning markaziy koordinatasi?",
         "choices": ["x:0, y:0", "x:240, y:180", "x:100, y:100", "x:-1, y:-1"], "correct": 0},
        {"text": "Sprite ko'rinishlari (rasmlari) qanday ataladi?",
         "choices": ["Backdrop", "Costumes", "Layers", "Sprites sheet"], "correct": 1},
        {"text": "Yashil bayroq bosilganda ishga tushuvchi hodisa bloki?",
         "choices": ["When key pressed", "When green flag clicked", "When sprite clicked", "Broadcast"], "correct": 1},
        {"text": "Ovoz bloklari qaysi guruhga kiradi?",
         "choices": ["Motion", "Sound", "Looks", "Sensing"], "correct": 1},
        {"text": "Bitta sprite'dan boshqasiga signal yuborish mexanizmi?",
         "choices": ["Glide", "Broadcast", "Repeat", "Wait"], "correct": 1},
        {"text": "Sprite'ni yashirish uchun blok?",
         "choices": ["Hide", "Delete", "Remove", "Stop"], "correct": 0},
        {"text": "Cheksiz takrorlanuvchi blok?",
         "choices": ["Repeat 10", "Forever", "Wait until", "If then"], "correct": 1},
        {"text": "Ma'lum marta takrorlanuvchi blok?",
         "choices": ["Forever", "Repeat", "If else", "Broadcast"], "correct": 1},
        {"text": "Faqat shart to'g'ri bo'lganda ishlaydigan blok?",
         "choices": ["If then", "Repeat", "Forever", "Wait"], "correct": 0},
        {"text": "Ikki sprite tegib turganini aniqlovchi blok guruhi?",
         "choices": ["Sensing (Touching)", "Operators", "Control", "Data"], "correct": 0},
        {"text": "Chetga urilganda qaytish uchun tayyor blok?",
         "choices": ["If on edge, bounce", "Glide to", "Wait 1 second", "Next costume"], "correct": 0},
        {"text": "Sahnaning orqa foni qanday ataladi?",
         "choices": ["Sprite", "Backdrop", "Costume", "Layer"], "correct": 1},
        {"text": "Bir fondan boshqasiga o'tuvchi blok?",
         "choices": ["Switch backdrop to", "Next costume", "Turn", "Move"], "correct": 0},
        {"text": "Fon o'zgarganda ishga tushuvchi hodisa bloki?",
         "choices": ["When backdrop switches to", "When key pressed", "When I start as a clone", "Wait until"], "correct": 0},
        {"text": "Tushayotgan obyektni pastga harakatlantirish uchun odatda nima o'zgartiriladi?",
         "choices": ["y koordinatasi kamaytiriladi", "Rangi o'zgartiriladi", "Ovozi oshiriladi", "Nomi o'zgartiriladi"], "correct": 0},
        {"text": "Sharcha va tutuvchi obyekt orasidagi to'qnashuv qaysi blok bilan tekshiriladi?",
         "choices": ["Touching", "Key pressed", "Loudness", "Timer"], "correct": 0},
        {"text": "O'yinning asosiy sikli odatda qaysi blok ichida yoziladi?",
         "choices": ["If then", "Forever", "Wait until", "Broadcast"], "correct": 1},
        {"text": "Tasodifiy son hosil qiluvchi blok?",
         "choices": ["pick random", "round", "mod", "sqrt"], "correct": 0},
        {"text": "Qiymatni saqlash uchun yaratiladigan element?",
         "choices": ["Costume", "Variable", "Backdrop", "Sound"], "correct": 1},
        {"text": "O'zgaruvchi qiymatini birga oshiruvchi blok?",
         "choices": ["Set variable to 0", "Change variable by 1", "Hide variable", "Show variable"], "correct": 1},
        {"text": "Ball/hisob ko'rsatkichini ekranda ko'rsatish uchun nima yoqiladi?",
         "choices": ["Show variable checkbox", "Hide sprite", "Mute sound", "Delete costume"], "correct": 0},
        {"text": "\"Game over\" holatini aniqlash uchun odatda nima tekshiriladi?",
         "choices": ["Hayot yoki vaqt tugashi sharti", "Sprite rangi", "Fon nomi", "Ovoz balandligi"], "correct": 0},
        {"text": "Dasturni to'liq to'xtatuvchi blok?",
         "choices": ["Stop all", "Wait 1 second", "Hide", "Next costume"], "correct": 0},
        {"text": "Foydalanuvchidan matn/son so'rash uchun blok?",
         "choices": ["Ask and wait", "Say", "Think", "Broadcast"], "correct": 0},
        {"text": "Ikki shartni birga tekshirish uchun ishlatiladigan operator?",
         "choices": ["and / or", "Motion", "Sound", "Looks"], "correct": 0},
        {"text": "Sprite'ni sahna bo'ylab silliq harakatlantiruvchi blok?",
         "choices": ["Move", "Glide", "Turn", "Go to"], "correct": 1},
        {"text": "Loyihani rejalashtirishda birinchi qadam odatda nima?",
         "choices": ["Kod yozishdan boshlash", "O'yin mexanikasi va obyektlarni aniqlash", "Fonni bezash", "Ovoz qo'shish"], "correct": 1},
    ],
}
