# Generated by Django 5.1.4 on 2026-08-17 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Foiz'), ('amount', 'Summa')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('course_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'payments_promo',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('fulfilled', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz'), ('expired', 'Muddati tugagan'), ('refunded', 'Qaytarildi')], default='created', max_length=20)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.promo')),
            ],
            options={
                'db_table': 'payments_order',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(choices=[('platform_cash', 'Platforma kassasi'), ('course_revenue', 'Kurs daromadi'), ('teacher_payable', "O'qituvchiga to'lanadigan"), ('platform_commission', 'Platforma komissiyasi'), ('teacher_payout_cash', "O'qituvchiga to'langan")], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_id', models.CharField(max_length=64)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_ledger_entry',
                'indexes': [models.Index(fields=['account', 'teacher'], name='payments_le_account_28e1aa_idx'), models.Index(fields=['ref_type', 'ref_id'], name='payments_le_ref_typ_6bd57b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='payme', max_length=30)),
                ('provider_txn_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('succeeded', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], default='pending', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
            options={
                'db_table': 'payments_payment',
                'indexes': [models.Index(fields=['provider', 'provider_txn_id'], name='payments_pa_provide_9c4ccf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='payments_or_user_id_0f08a8_idx'),
        ),
    ]
